import puppeteer from '@cloudflare/puppeteer';

type PI={text:string;x:number;y:number;width:number;height:number};
type Line={y:number;items:PI[];text:string};
type Kind='description'|'method'|'basis'|'legal'|'responsible'|'other';
type Col={kind:Kind;x:number};
const TARGET=new Set(['4.1','5.1','5.2','5.4','6.1']);
const clean=(s:string)=>s.replace(/\s+/g,' ').trim();
function codeIn(s:string){const n=s.replace(/(\d{1,2})\s*\.\s*(\d{1,2})/g,'$1.$2');return n.match(/(?:^|\s)(\d{1,2}\.\d{1,2})(?=\s|$|[^0-9A-Za-z])/)?.[1]||''}
function lines(items:PI[]):Line[]{const out:Line[]=[];for(const it of items){let l=out.find(x=>Math.abs(x.y-it.y)<=2.2);if(!l){l={y:it.y,items:[],text:''};out.push(l)}l.items.push(it)}out.sort((a,b)=>b.y-a.y);for(const l of out){l.items.sort((a,b)=>a.x-b.x);l.text=clean(l.items.map(x=>x.text).join(' '))}return out}
function cols(ls:Line[],pageWidth:number){const found=new Map<Kind,number>();for(const l of ls){for(const it of l.items){const t=it.text.toLowerCase();let k:Kind|null=null;if(/moment|kontrollpunkt/.test(t))k='description';else if(/hur.*kontroll|kontroll.*sker/.test(t))k='method';else if(/mot vad|kontrolleras mot|underlag/.test(t))k='basis';else if(/pbl.*bbr|avsnitt|lagrum|föreskrift|regelverk/.test(t))k='legal';else if(/kontrolleras av|ansvarig/.test(t))k='responsible';if(k&&!found.has(k))found.set(k,it.x)}}if(!found.has('description'))found.set('description',pageWidth*.04);return [...found].map(([kind,x])=>({kind,x})).sort((a,b)=>a.x-b.x)}
function colFor(cs:Col[],x:number):Kind{for(let i=0;i<cs.length;i++){const left=i?(cs[i-1].x+cs[i].x)/2:-Infinity,right=i<cs.length-1?(cs[i].x+cs[i+1].x)/2:Infinity;if(x>=left&&x<right)return cs[i].kind}return'other'}
export function registerControlPlanLayoutDiagnosticsRoutes(app:any){app.get('/api/studio/governing-documents/:id/layout-geometry',async(c:any)=>{try{const id=c.req.param('id');const row=await c.env.DB.prepare(`SELECT d.document_type,f.object_key FROM governing_documents d JOIN governing_document_files f ON f.document_id=d.id WHERE d.id=?`).bind(id).first<any>();if(!row)return c.json({ok:false,error:'not found'},404);const obj=await c.env.FILES.get(String(row.object_key));if(!obj)return c.json({ok:false,error:'file missing'},404);const browser=await puppeteer.launch(c.env.BROWSER),p=await browser.newPage();try{await p.setContent(`<!doctype html><script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"></script>`,{waitUntil:'networkidle0'});await p.waitForFunction(()=>Boolean((globalThis as any).pdfjsLib),{timeout:20000});const bytes=Array.from(new Uint8Array(await obj.arrayBuffer()));const pages=await p.evaluate(async(bytes:number[])=>{const pdfjs=(globalThis as any).pdfjsLib;pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjs.getDocument({data:new Uint8Array(bytes)}).promise,out:any[]=[];for(let n=1;n<=pdf.numPages;n++){const pg=await pdf.getPage(n),v=pg.getViewport({scale:1}),ct=await pg.getTextContent();out.push({page:n,width:v.width,items:(ct.items||[]).map((x:any)=>({text:String(x.str||'').trim(),x:Number(x.transform?.[4]||0),y:Number(x.transform?.[5]||0),width:Number(x.width||0),height:Number(x.height||Math.abs(x.transform?.[3]||0)||0)})).filter((x:any)=>x.text)})}return out},bytes);const result:any[]=[];for(const page of pages){const ls=lines(page.items),cs=cols(ls,page.width),anchors=ls.map((line:any,index:number)=>({line,index,code:codeIn(line.text)})).filter((x:any)=>TARGET.has(x.code));for(const a of anchors){let next:any;for(let i=a.index+1;i<ls.length;i++){if(codeIn(ls[i].text)){next=ls[i];break}}const top=a.line.y+2.5,bottom=next?next.y+2.5:-Infinity;const objects=page.items.filter((x:any)=>x.y<=top&&x.y>bottom).map((x:any)=>({chars:x.text.length,x:+x.x.toFixed(2),y:+x.y.toFixed(2),width:+x.width.toFixed(2),height:+x.height.toFixed(2),column:colFor(cs,x.x)}));result.push({page:page.page,code:a.code,columns:cs,objects})}}return c.json({ok:true,diagnostics:result})}finally{await browser.close().catch(()=>undefined)}}catch(e){return c.json({ok:false,error:e instanceof Error?e.message:String(e)},500)}})}
