type RouteApp={get:(path:string,handler:(c:any)=>unknown)=>void;put:(path:string,handler:(c:any)=>unknown)=>void};
const EXCEPTIONS=['not_applicable','cannot_verify','alternative_evidence'];
async function addColumn(db:D1Database,sql:string){try{await db.prepare(sql).run()}catch(e){const m=(e instanceof Error?e.message:String(e)).toLowerCase();if(!m.includes('duplicate column')&&!m.includes('already exists'))throw e}}
async function schema(db:D1Database){await addColumn(db,"ALTER TABLE governing_items ADD COLUMN source_note TEXT NOT NULL DEFAULT ''");await addColumn(db,"ALTER TABLE governing_item_activity_links ADD COLUMN mapping_source TEXT NOT NULL DEFAULT 'manual'");await addColumn(db,'ALTER TABLE governing_item_activity_links ADD COLUMN confidence INTEGER');await addColumn(db,"ALTER TABLE governing_item_activity_links ADD COLUMN mapping_comment TEXT NOT NULL DEFAULT ''");await addColumn(db,'ALTER TABLE governing_item_activity_links ADD COLUMN confirmed_at TEXT')}
function norm(v:unknown){return String(v||'').toLocaleLowerCase('sv-SE').replace(/[–—]/g,'-').replace(/[^a-zåäö0-9+\-/ ]/g,' ').replace(/\s+/g,' ').trim()}
const STOP=new Set(['enligt','eller','samt','skall','ska','utförd','utföras','erforderlig','erforderliga','byggnaden','byggnadens','projektet','punkt','under','gällande','handling','handlingar','se']);
function words(v:unknown){return norm(v).split(/\s+/).filter(w=>w.length>=4&&!STOP.has(w))}
type Rule={code:string;domain:string;patterns:RegExp[]};
const RULES:Rule[]=[
 {code:'setout',domain:'location',patterns:[/utsätt/,/utstakn/,/referenshöjd/]},{code:'location_control',domain:'location',patterns:[/lägeskontroll/,/kontrollmät/,/mätintyg/]},
 {code:'bas_p',domain:'administration',patterns:[/bas-p/,/bas p/]},{code:'bas_u',domain:'administration',patterns:[/bas-u/,/bas u/]},{code:'work_environment',domain:'administration',patterns:[/arbetsmiljö/]},{code:'start_meeting',domain:'administration',patterns:[/startmöte/]},{code:'contractor_self_control',domain:'administration',patterns:[/totalentreprenör.*egenkontroll/,/entreprenör.*egenkontroll/]},
 {code:'ka_ground_visit',domain:'ground',patterns:[/besök.*grundbotten/,/grundbotten.*ka/]},{code:'ka_frame_visit',domain:'structure',patterns:[/besök.*stomm.*rest/,/stomm.*rest.*ka/]},{code:'ka_interior_visit',domain:'interior',patterns:[/besök.*invänd/,/invänd.*ka/]},{code:'final_consultation',domain:'authority',patterns:[/slutsamråd/]},{code:'authority_site_visit',domain:'authority',patterns:[/arbetsplatsbesök/,/byggnadsnämnd.*besök/]},{code:'permit_conformance',domain:'authority',patterns:[/överensstämmelse.*bygglov/,/bygglov.*överensstämmelse/,/färdig.*mot.*lov/]},
 {code:'geotechnical',domain:'ground',patterns:[/geotekn/]},{code:'radon',domain:'ground',patterns:[/radon/]},{code:'foundation',domain:'ground',patterns:[/grundlägg/,/torpargrund/,/krypgrund/,/grundkonstruk/]},{code:'moisture_planning',domain:'moisture',patterns:[/fuktsäkerhetsprojekter/]},{code:'moisture',domain:'moisture',patterns:[/fuktsäker/,/fuktskydd/,/fukt/]},
 {code:'log_frame',domain:'structure',patterns:[/timmerstom/]},{code:'frame',domain:'structure',patterns:[/bärande stom/,/stomme/,/stomkontroll/]},{code:'log_joint',domain:'structure',patterns:[/dragstag/,/gängstång/,/skarvar.*stom/,/konstruktiva förband/]},{code:'floor_structure',domain:'structure',patterns:[/bjälklag/,/golvbär/,/avväxling/]},
 {code:'roof_structure',domain:'roof',patterns:[/takstol/,/takkonstruk/,/takås/,/åstak/,/bärande tak/]},{code:'roof_cover',domain:'roof',patterns:[/plåttak/,/taktäck/,/undertak/,/väggtäck/,/panel/]},{code:'openings',domain:'envelope',patterns:[/fönster/,/ytterdörr/,/dörrar/]},{code:'insulation',domain:'envelope',patterns:[/värmeisol/,/isolering.*täthet/,/klimatskal/,/lufttäthet/,/lufttät/,/ångtät/]},
 {code:'ventilation',domain:'ventilation',patterns:[/ventilation/,/självdrag/,/frånluft/,/ftx/]},
 {code:'fire_planning',domain:'fire',patterns:[/brandskyddsbeskriv.*projekter/,/brandskydd.*projekter/]},{code:'fire_description',domain:'fire',patterns:[/brandskyddsbeskriv/]},{code:'fire_documentation',domain:'fire',patterns:[/brandskyddsdokument/]},{code:'chimney_certificate',domain:'fire',patterns:[/intyg.*sotar/,/sotar.*intyg/,/sotarbesikt/,/protokoll.*sotar/]},{code:'fireplace',domain:'fire',patterns:[/eldstad/,/vedkamin/,/rökkanal/,/skorsten/]},{code:'fire',domain:'fire',patterns:[/brandskydd/,/brandvarn/]},
 {code:'stormwater',domain:'stormwater',patterns:[/dagvatten/,/markfall/,/\blod\b/]},{code:'wetroom_qualification',domain:'wetroom',patterns:[/byggkeramik/,/behörighet.*våtrum/,/våtrumsmetod/,/redovisning.*metod/]},{code:'wetroom',domain:'wetroom',patterns:[/tätskikt/,/våtrum/,/golvbrunn/]},
 {code:'vvs_pressure',domain:'vvs',patterns:[/provtryck/,/täthets.*vvs/,/vvs.*täthet/]},{code:'va_inspection',domain:'vvs',patterns:[/va-inspektion/,/va inspektion/,/före övertäckning/]},{code:'vvs',domain:'vvs',patterns:[/\bvvs\b/,/spillvatten/,/vatteninstallation/,/vatten och avlopp/,/\bva\b/]},
 {code:'electrical_contractor',domain:'electrical',patterns:[/elinstallationsföretag/,/registrerat.*el/]},{code:'electrical_insulation',domain:'electrical',patterns:[/isolationsprov/]},{code:'electrical_rcd',domain:'electrical',patterns:[/jordfelsbryt/]},{code:'electrical',domain:'electrical',patterns:[/elinstallation/,/elarbet/,/elintyg/,/elsäker/]},
 {code:'architect_control',domain:'architecture',patterns:[/arkitektens egenkontroll/,/arkitektrit/]},{code:'accessibility',domain:'architecture',patterns:[/tillgänglighet/,/användbarhet/]},{code:'broadband',domain:'broadband',patterns:[/bredband/,/fiberanslut/,/fiber/]},
 {code:'completion',domain:'completion',patterns:[/färdigställande/,/avsluta projekt/,/färdigställandekontroll/]},{code:'signed_control_plan',domain:'final_docs',patterns:[/signerad kontrollplan/,/ifylld.*kontrollplan/]},{code:'final_evidence',domain:'final_docs',patterns:[/egenkontroller.*intyg/,/slutdokument/,/slutbesked/,/samla.*intyg/]},{code:'final_photos',domain:'final_docs',patterns:[/fotografier/,/fotodokumentation/]},{code:'relations',domain:'final_docs',patterns:[/relationshandling/]},{code:'sewage_authority_doc',domain:'final_docs',patterns:[/miljöenheten.*avlopp/,/myndighetsintyg.*avlopp/,/myndighetsintyg.*va/]},{code:'self_control',domain:'final_docs',patterns:[/egenkontroll/]}
];
function conceptInfo(v:unknown){const t=norm(v),concepts=new Set<string>(),domains=new Set<string>();for(const r of RULES)if(r.patterns.some(p=>p.test(t))){concepts.add(r.code);domains.add(r.domain)}return{concepts,domains}}
function overlap<T>(a:Set<T>,b:Set<T>){for(const x of a)if(b.has(x))return true;return false}
function intersection<T>(a:Set<T>,b:Set<T>){const out:T[]=[];for(const x of a)if(b.has(x))out.push(x);return out}
type Intent='perform'|'check'|'document'|'measurement'|'visit'|'other';
function sourceIntent(item:any):Intent{const t=norm(item.description);
 if(item.item_type==='visit'||/besök|slutsamråd|inspektion/.test(t))return'visit';
 if(item.item_type==='measurement'||/lägeskontroll|kontrollmät|utsättning|utstakning/.test(t))return'measurement';
 if(/installation|grundlägg|stomme|bjälklag|takstol|takkonstruk|täckning|fönster|dörr|ventilation|värmeisol|eldstad|vatten och avlopp|färdigställande/.test(t))return'perform';
 if(/signerad|lämnas in|fotografier|relationshandling|intyg|protokoll|upprättad/.test(t))return'document';
 if(/behörighetskontroll|egenkontroll|beaktad|överensstämmelse|registrerat|kontroll|bedömning|radonklass/.test(t))return'check';
 if(item.item_type==='documentation')return'document';return'other'}
function targetIntent(a:any):Intent{const t=norm(a.title);if(/installera|utför elinstallation|montera vatten|utför vvs|utför enskilt avlopp|färdigställ/.test(t))return'perform';if(a.activity_type==='document'||/spara.*intyg|spara.*protokoll|samla.*intyg|samla.*kontrollplan|fotodokument/.test(t))return'document';if(/besök|slutsamråd|inspektion/.test(t)||a.activity_type==='approval')return'visit';if(a.activity_type==='measurement')return'measurement';if(a.activity_type==='check')return'check';if(a.activity_type==='perform')return'perform';return'other'}
const GENERIC=new Set(['frame','fire','vvs','electrical','wetroom','moisture','completion','self_control']);
const STRICT=new Set(['moisture_planning','fire_planning','contractor_self_control','wetroom_qualification','chimney_certificate','signed_control_plan','final_photos','sewage_authority_doc','va_inspection','electrical_contractor','electrical_insulation','electrical_rcd','location_control','setout']);
type Features={primaryConcepts:Set<string>;primaryDomains:Set<string>;contextConcepts:Set<string>;contextDomains:Set<string>;words:Set<string>;intent:Intent;area:string};
function sourceFeatures(item:any):Features{const primary=`${item.description||''}`,context=`${item.section_title||''} ${item.source_note||''}`;const p=conceptInfo(primary),c=conceptInfo(context);return{primaryConcepts:p.concepts,primaryDomains:p.domains,contextConcepts:c.concepts,contextDomains:c.domains,words:new Set(words(primary)),intent:sourceIntent(item),area:''}}
function targetFeatures(a:any):Features{const primary=`${a.title} ${a.description||''}`,context=`${a.task_title||''} ${a.section_name||''}`;const p=conceptInfo(primary),c=conceptInfo(context);return{primaryConcepts:p.concepts,primaryDomains:p.domains,contextConcepts:c.concepts,contextDomains:c.domains,words:new Set(words(primary)),intent:targetIntent(a),area:norm(a.area_name)}}
function areaAllows(sourceDomains:Set<string>,area:string){if(!sourceDomains.size||!area)return true;const d=[...sourceDomains];if(area.includes('mark och grund'))return d.some(x=>['ground','moisture','stormwater','vvs','final_docs'].includes(x));if(area.includes('bärande stomme'))return d.some(x=>['structure','final_docs'].includes(x));if(area==='tak'||area.startsWith('tak '))return d.some(x=>['roof','fire','final_docs'].includes(x));if(area.includes('klimatskal'))return d.some(x=>['envelope','moisture','final_docs'].includes(x));if(area.includes('installationer'))return d.some(x=>['electrical','vvs','ventilation','broadband','stormwater','final_docs'].includes(x));if(area.includes('invändiga'))return d.some(x=>['interior','wetroom','fire','final_docs','architecture'].includes(x));if(area.includes('säkerhet och färdigställande'))return d.some(x=>['authority','architecture','fire','final_docs','completion','administration'].includes(x));return true}
function similarity(sf:Features,tf:Features){if(!areaAllows(sf.primaryDomains,tf.area))return 0;const sharedPrimary=intersection(sf.primaryConcepts,tf.primaryConcepts),sharedDomain=overlap(sf.primaryDomains,tf.primaryDomains),sharedContext=overlap(sf.primaryConcepts,tf.contextConcepts)||overlap(sf.contextConcepts,tf.primaryConcepts);const required=[...sf.primaryConcepts].filter(x=>STRICT.has(x));if(required.length&&!required.some(x=>tf.primaryConcepts.has(x)))return 0;if(sf.primaryDomains.size&&tf.primaryDomains.size&&!sharedDomain&&!sharedPrimary.length)return 0;let hits=0;for(const w of sf.words)if(tf.words.has(w))hits++;const lexical=sf.words.size&&tf.words.size?Math.round(24*hits/Math.max(2,Math.min(sf.words.size,tf.words.size))):0;let score=lexical;if(sharedPrimary.length){score+=64;if(sharedPrimary.some(x=>!GENERIC.has(String(x))))score+=12;if(sharedPrimary.length>1)score+=4}else if(sharedDomain)score+=28;else if(sharedContext)score+=10;else if(sf.primaryConcepts.size)return 0;if(sf.intent!=='other'&&tf.intent!=='other'){if(sf.intent===tf.intent)score+=16;else if(sf.intent==='document')score-=sharedPrimary.length?20:40;else if(sf.intent==='visit')score-=sharedPrimary.length?16:32;else if(sf.intent==='measurement')score-=sharedPrimary.length?14:26;else if(sf.intent==='perform'&&tf.intent!=='perform')score-=52;else if(sf.intent==='check'&&tf.intent==='perform')score-=30}return Math.max(0,Math.min(98,score))}
export function registerGoverningMappingRoutesV8(app:RouteApp){
 app.get('/api/studio/projects/:projectId/governing-mapping',async c=>{try{await schema(c.env.DB);const projectId=c.req.param('projectId');const [dr,ir,ar,lr]=await Promise.all([
  c.env.DB.prepare(`SELECT id,document_type,title,issuer,reference,imported_at FROM governing_documents WHERE project_id=? ORDER BY CASE document_type WHEN 'control_plan' THEN 0 ELSE 1 END,imported_at,title`).bind(projectId).all(),
  c.env.DB.prepare(`SELECT i.id,i.governing_document_id,i.code,i.description,i.section_code,i.section_title,i.item_type,i.responsible_role,i.handling_status,i.source_note,i.sort_order,d.imported_at FROM governing_items i JOIN governing_documents d ON d.id=i.governing_document_id WHERE d.project_id=? ORDER BY d.imported_at,i.sort_order,i.id`).bind(projectId).all(),
  c.env.DB.prepare(`SELECT a.id,a.title,a.description,a.activity_type,t.title task_title,ws.name section_name,wa.name area_name,wa.sort_order area_order,ws.sort_order section_order,t.sort_order task_order,a.sort_order activity_order FROM activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections ws ON ws.id=t.work_section_id JOIN work_areas wa ON wa.id=ws.work_area_id WHERE wa.project_id=? ORDER BY wa.sort_order,ws.sort_order,t.sort_order,a.sort_order`).bind(projectId).all(),
  c.env.DB.prepare(`SELECT l.governing_item_id,l.activity_id,a.title activity_title FROM governing_item_activity_links l JOIN governing_items i ON i.id=l.governing_item_id JOIN governing_documents d ON d.id=i.governing_document_id JOIN activities a ON a.id=l.activity_id WHERE d.project_id=?`).bind(projectId).all()]);
  const documents=dr.results as any[],items=ir.results as any[],activities=ar.results as any[],links=lr.results as any[];const linksByItem=new Map<string,any[]>(),linkCountByActivity=new Map<string,number>();for(const l of links){const k=String(l.governing_item_id),xs=linksByItem.get(k)||[];xs.push(l);linksByItem.set(k,xs);const aid=String(l.activity_id);linkCountByActivity.set(aid,(linkCountByActivity.get(aid)||0)+1)}
  const itemRows=items.map(i=>{const ls=linksByItem.get(String(i.id))||[];return{...i,mapped_activity_count:ls.length,mapped_activity_titles:ls.map(x=>x.activity_title).join(' || ')||null}}),activityRows=activities.map(a=>({...a,governing_item_count:linkCountByActivity.get(String(a.id))||0}));const af=new Map<string,Features>();for(const a of activityRows)af.set(String(a.id),targetFeatures(a));
  const suggestions:Record<string,any[]>={};for(const item of itemRows){if(Number(item.mapped_activity_count)>0||EXCEPTIONS.includes(String(item.handling_status||'')))continue;const sf=sourceFeatures(item);let ranked=activityRows.map(a=>({a,confidence:similarity(sf,af.get(String(a.id))!)})).filter(x=>x.confidence>=60).sort((x,y)=>y.confidence-x.confidence);if(ranked.length){const top=ranked[0].confidence;ranked=ranked.filter(x=>x.confidence>=top-5).slice(0,3);if(ranked.length>1&&ranked[0].confidence-ranked[1].confidence>=4)ranked=ranked.slice(0,1)}if(ranked.length)suggestions[String(item.id)]=ranked.map(x=>({activity_id:x.a.id,title:x.a.title,task_title:x.a.task_title,section_name:x.a.section_name,area_name:x.a.area_name,confidence:x.confidence}))}
  const documentRows=documents.map(d=>{const di=itemRows.filter(i=>String(i.governing_document_id)===String(d.id)),item_count=di.length,exception_count=di.filter(i=>EXCEPTIONS.includes(String(i.handling_status||''))).length,mapped_count=di.filter(i=>!EXCEPTIONS.includes(String(i.handling_status||''))&&Number(i.mapped_activity_count)>0).length,uncovered_count=di.filter(i=>!EXCEPTIONS.includes(String(i.handling_status||''))&&Number(i.mapped_activity_count)===0).length,covered_count=mapped_count+exception_count;return{...d,item_count,mapped_count,exception_count,uncovered_count,covered_count,coverage_percent:item_count?Math.round(covered_count*100/item_count):100}});const total=documentRows.reduce((s,r)=>s+r.item_count,0),mapped=documentRows.reduce((s,r)=>s+r.mapped_count,0),exceptions=documentRows.reduce((s,r)=>s+r.exception_count,0),uncovered=documentRows.reduce((s,r)=>s+r.uncovered_count,0),covered=mapped+exceptions;return c.json({ok:true,runtime:'mapping-v8',summary:{item_count:total,mapped_count:mapped,exception_count:exceptions,covered_count:covered,uncovered_count:uncovered,coverage_percent:total?Math.round(covered*100/total):100},documents:documentRows,items:itemRows,activities:activityRows,suggestions})}catch(e){console.error('Governing mapping v8 read failed',e);return c.json({ok:false,runtime:'mapping-v8',error:`Kartläggning v8: ${e instanceof Error?e.message:String(e)}`},500)}});
 app.put('/api/studio/governing-items/:itemId/mappings/:activityId',async c=>{try{await schema(c.env.DB);const itemId=c.req.param('itemId'),activityId=c.req.param('activityId'),body=await c.req.json<Record<string,unknown>>().catch(()=>({}));const pair=await c.env.DB.prepare(`SELECT i.id item_id,a.id activity_id FROM governing_items i JOIN governing_documents d ON d.id=i.governing_document_id CROSS JOIN activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections ws ON ws.id=t.work_section_id JOIN work_areas wa ON wa.id=ws.work_area_id WHERE i.id=? AND a.id=? AND d.project_id=wa.project_id`).bind(itemId,activityId).first();if(!pair)return c.json({ok:false,error:'Posten och aktiviteten tillhör inte samma projekt.'},409);const raw=Number(body.confidence),confidence=Number.isFinite(raw)?Math.max(0,Math.min(100,Math.round(raw))):null,source=String(body.mappingSource||'manual')==='suggested'?'suggested':'manual',comment=typeof body.comment==='string'?body.comment.trim():'';await c.env.DB.prepare(`INSERT INTO governing_item_activity_links(id,governing_item_id,activity_id,link_type,mapping_source,confidence,mapping_comment,created_at,confirmed_at) VALUES(?,?,?,'supports',?,?,?,datetime('now'),datetime('now')) ON CONFLICT(governing_item_id,activity_id) DO UPDATE SET mapping_source=excluded.mapping_source,confidence=excluded.confidence,mapping_comment=excluded.mapping_comment,confirmed_at=datetime('now')`).bind(crypto.randomUUID(),itemId,activityId,source,confidence,comment).run();return c.json({ok:true,runtime:'mapping-v8'})}catch(e){console.error('Governing mapping v8 write failed',e);return c.json({ok:false,runtime:'mapping-v8',error:`Koppling v8: ${e instanceof Error?e.message:String(e)}`},500)}})
}
