type RouteApp={get:(path:string,handler:(c:any)=>unknown)=>void;put:(path:string,handler:(c:any)=>unknown)=>void};
const EXCEPTIONS=['not_applicable','cannot_verify','alternative_evidence'];
async function addColumn(db:D1Database,sql:string){try{await db.prepare(sql).run()}catch(e){const m=(e instanceof Error?e.message:String(e)).toLowerCase();if(!m.includes('duplicate column')&&!m.includes('already exists'))throw e}}
async function schema(db:D1Database){await addColumn(db,"ALTER TABLE governing_items ADD COLUMN source_note TEXT NOT NULL DEFAULT ''");await addColumn(db,"ALTER TABLE governing_item_activity_links ADD COLUMN mapping_source TEXT NOT NULL DEFAULT 'manual'");await addColumn(db,'ALTER TABLE governing_item_activity_links ADD COLUMN confidence INTEGER');await addColumn(db,"ALTER TABLE governing_item_activity_links ADD COLUMN mapping_comment TEXT NOT NULL DEFAULT ''");await addColumn(db,'ALTER TABLE governing_item_activity_links ADD COLUMN confirmed_at TEXT')}
function norm(v:unknown){return String(v||'').toLocaleLowerCase('sv-SE').replace(/[–—]/g,'-').replace(/[^a-zåäö0-9+\-/ ]/g,' ').replace(/\s+/g,' ').trim()}
const STOP=new Set(['enligt','eller','samt','skall','ska','utförd','utföras','erforderlig','erforderliga','byggnaden','byggnadens','projektet','punkt','se']);
function words(v:unknown){return norm(v).split(/\s+/).filter(w=>w.length>=4&&!STOP.has(w))}
type Rule={code:string;domain:string;patterns:RegExp[]};
const RULES:Rule[]=[
 {code:'setout',domain:'location',patterns:[/utsätt/,/referenshöjd/]},{code:'location_control',domain:'location',patterns:[/lägeskontroll/,/kontrollmät/,/mätintyg/]},
 {code:'bas_p',domain:'administration',patterns:[/bas-p/,/bas p/]},{code:'bas_u',domain:'administration',patterns:[/bas-u/,/bas u/]},{code:'work_environment',domain:'administration',patterns:[/arbetsmiljö/]},{code:'start_meeting',domain:'administration',patterns:[/startmöte/]},
 {code:'ka_ground_visit',domain:'ground',patterns:[/besök.*grundbotten/,/grundbotten.*ka/]},{code:'ka_frame_visit',domain:'structure',patterns:[/besök.*stomm.*rest/,/stomm.*rest.*ka/]},{code:'ka_interior_visit',domain:'interior',patterns:[/besök.*invänd/,/invänd.*ka/]},{code:'final_consultation',domain:'authority',patterns:[/slutsamråd/]},{code:'authority_site_visit',domain:'authority',patterns:[/arbetsplatsbesök/,/byggnadsnämnd.*besök/]},{code:'permit_conformance',domain:'authority',patterns:[/överensstämmelse.*bygglov/,/bygglov.*överensstämmelse/,/färdig.*mot.*lov/]},
 {code:'geotechnical',domain:'ground',patterns:[/geotekn/]},{code:'radon',domain:'ground',patterns:[/radon/]},{code:'foundation',domain:'ground',patterns:[/grundlägg/,/torpargrund/,/krypgrund/,/grundkonstruk/]},{code:'moisture_planning',domain:'moisture',patterns:[/fuktsäkerhetsprojekter/]},{code:'moisture',domain:'moisture',patterns:[/fuktsäker/,/fuktskydd/,/fukt/]},
 {code:'frame',domain:'structure',patterns:[/bärande stom/,/stomme/,/stomkontroll/]},{code:'log_joint',domain:'structure',patterns:[/dragstag/,/gängstång/,/skarvar.*stom/,/konstruktiva förband/]},{code:'floor_structure',domain:'structure',patterns:[/bjälklag/,/golvbär/,/avväxling/]},
 {code:'roof_structure',domain:'roof',patterns:[/takstol/,/takkonstruk/,/takås/,/åstak/,/bärande tak/]},{code:'roof_cover',domain:'roof',patterns:[/plåttak/,/taktäck/,/undertak/,/väggtäck/,/panel/]},{code:'openings',domain:'envelope',patterns:[/fönster/,/ytterdörr/,/dörrar/]},{code:'insulation',domain:'envelope',patterns:[/värmeisol/,/isolering.*täthet/,/klimatskal/,/ångtät/,/lufttät/]},
 {code:'ventilation',domain:'ventilation',patterns:[/ventilation/,/självdrag/,/frånluft/,/ftx/]},
 {code:'fire_description',domain:'fire',patterns:[/brandskyddsbeskriv/]},{code:'fire_documentation',domain:'fire',patterns:[/brandskyddsdokument/]},{code:'chimney_certificate',domain:'fire',patterns:[/intyg.*sotar/,/sotar.*intyg/,/sotarbesikt/,/protokoll.*sotar/]},{code:'fireplace',domain:'fire',patterns:[/eldstad/,/vedkamin/,/rökkanal/,/skorsten/]},{code:'fire',domain:'fire',patterns:[/brandskydd/,/brandvarn/]},
 {code:'stormwater',domain:'stormwater',patterns:[/dagvatten/,/markfall/,/lod/]},{code:'wetroom_qualification',domain:'wetroom',patterns:[/byggkeramik/,/behörighet.*våtrum/,/våtrumsmetod/,/redovisning.*metod/]},{code:'wetroom',domain:'wetroom',patterns:[/tätskikt/,/våtrum/,/golvbrunn/]},
 {code:'vvs_pressure',domain:'vvs',patterns:[/provtryck/,/täthets.*vvs/,/vvs.*täthet/]},{code:'va_inspection',domain:'vvs',patterns:[/va-inspektion/,/va inspektion/,/före övertäckning/]},{code:'vvs',domain:'vvs',patterns:[/\bvvs\b/,/spillvatten/,/vatteninstallation/,/vatten och avlopp/,/\bva\b/]},
 {code:'electrical_contractor',domain:'electrical',patterns:[/elinstallationsföretag/,/registrerat.*el/]},{code:'electrical_insulation',domain:'electrical',patterns:[/isolationsprov/]},{code:'electrical_rcd',domain:'electrical',patterns:[/jordfelsbryt/]},{code:'electrical',domain:'electrical',patterns:[/elinstallation/,/elarbet/,/elintyg/,/elsäker/]},
 {code:'architect_control',domain:'architecture',patterns:[/arkitektens egenkontroll/,/arkitektrit/]},{code:'accessibility',domain:'architecture',patterns:[/tillgänglighet/,/användbarhet/]},{code:'broadband',domain:'broadband',patterns:[/bredband/,/fiberanslut/,/fiber/]},
 {code:'completion',domain:'completion',patterns:[/färdigställande/,/avsluta projekt/]},{code:'signed_control_plan',domain:'final_docs',patterns:[/signerad kontrollplan/,/ifylld.*kontrollplan/]},{code:'final_evidence',domain:'final_docs',patterns:[/egenkontroller.*intyg/,/slutdokument/,/slutbesked/,/samla.*intyg/]},{code:'final_photos',domain:'final_docs',patterns:[/fotografier/,/fotodokumentation/]},{code:'relations',domain:'final_docs',patterns:[/relationshandling/]},{code:'sewage_authority_doc',domain:'final_docs',patterns:[/miljöenheten.*avlopp/,/myndighetsintyg.*avlopp/]},{code:'self_control',domain:'final_docs',patterns:[/egenkontroll/]}
];
function conceptInfo(v:unknown){const t=norm(v),concepts=new Set<string>(),domains=new Set<string>();for(const r of RULES)if(r.patterns.some(p=>p.test(t))){concepts.add(r.code);domains.add(r.domain)}return{concepts,domains}}
type Intent='perform'|'check'|'document'|'measurement'|'visit'|'other';
function sourceIntent(item:any):Intent{const t=norm(`${item.description} ${item.source_note||''}`);if(item.item_type==='visit'||/besök|slutsamråd/.test(t))return'visit';if(item.item_type==='measurement'||/lägeskontroll|kontrollmät|utsättning/.test(t))return'measurement';if(item.item_type==='documentation'||/intyg|protokoll|relationshandling|signerad kontrollplan|lämnas in|fotografier|upprättad/.test(t))return'document';if(/behörighetskontroll|egenkontroll|beaktad|kontroll|bedömning/.test(t))return'check';if(/installation|grundlägg|stomme|bjälklag|takstol|takkonstruk|täckning|fönster|dörr|ventilation|värmeisol|eldstad|vatten och avlopp|färdigställande/.test(t))return'perform';return'other'}
function targetIntent(a:any):Intent{const t=norm(a.title);if(a.activity_type==='document'||/spara.*intyg|spara.*protokoll|samla.*intyg|samla.*kontrollplan|fotodokument/.test(t))return'document';if(/besök|slutsamråd|sotarbesiktning/.test(t))return'visit';if(a.activity_type==='measurement')return'measurement';if(a.activity_type==='check')return'check';if(a.activity_type==='perform')return'perform';if(a.activity_type==='approval')return'visit';return'other'}
function overlap<T>(a:Set<T>,b:Set<T>){for(const x of a)if(b.has(x))return true;return false}
type Features={concepts:Set<string>;domains:Set<string>;words:Set<string>;intent:Intent};
function sourceFeatures(item:any):Features{const text=`${item.description} ${item.section_title} ${item.source_note||''}`;const ci=conceptInfo(text);return{...ci,words:new Set(words(text)),intent:sourceIntent(item)}}
function targetFeatures(a:any):Features{const text=`${a.title} ${a.description||''} ${a.task_title} ${a.section_name} ${a.area_name}`;const ci=conceptInfo(text);return{...ci,words:new Set(words(text)),intent:targetIntent(a)}}
function similarity(sf:Features,tf:Features){
 if(sf.domains.size&&tf.domains.size&&!overlap(sf.domains,tf.domains))return 0;
 let hits=0;for(const w of sf.words)if(tf.words.has(w))hits++;
 const lexical=sf.words.size&&tf.words.size?Math.round(28*hits/Math.max(2,Math.min(sf.words.size,tf.words.size))):0;
 const exactConcept=overlap(sf.concepts,tf.concepts),sameDomain=overlap(sf.domains,tf.domains);
 let score=lexical;if(exactConcept)score+=60;else if(sameDomain)score+=24;
 if(sf.intent!=='other'&&tf.intent!=='other'){
  if(sf.intent===tf.intent)score+=20;
  else if(sf.intent==='document')score-=38;
  else if(sf.intent==='visit')score-=38;
  else if(sf.intent==='measurement'&&tf.intent!=='check')score-=24;
  else if(sf.intent==='perform'&&tf.intent==='check')score-=22;
  else if(sf.intent==='check'&&tf.intent==='perform')score-=24;
 }
 if(sf.concepts.size&&!tf.concepts.size)score=Math.min(score,lexical>=22?44:0);
 return Math.max(0,Math.min(98,score));
}

export function registerGoverningMappingRoutesV5(app:RouteApp){
app.get('/api/studio/projects/:projectId/governing-mapping',async c=>{try{await schema(c.env.DB);const projectId=c.req.param('projectId');const [documentsResult,itemsResult,activitiesResult,linksResult]=await Promise.all([
 c.env.DB.prepare(`SELECT id,document_type,title,issuer,reference,imported_at FROM governing_documents WHERE project_id=? ORDER BY CASE document_type WHEN 'control_plan' THEN 0 ELSE 1 END,imported_at,title`).bind(projectId).all(),
 c.env.DB.prepare(`SELECT i.id,i.governing_document_id,i.code,i.description,i.section_code,i.section_title,i.item_type,i.responsible_role,i.handling_status,i.source_note,i.sort_order,d.imported_at FROM governing_items i JOIN governing_documents d ON d.id=i.governing_document_id WHERE d.project_id=? ORDER BY d.imported_at,i.sort_order,i.id`).bind(projectId).all(),
 c.env.DB.prepare(`SELECT a.id,a.title,a.description,a.activity_type,t.title task_title,ws.name section_name,wa.name area_name,wa.sort_order area_order,ws.sort_order section_order,t.sort_order task_order,a.sort_order activity_order FROM activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections ws ON ws.id=t.work_section_id JOIN work_areas wa ON wa.id=ws.work_area_id WHERE wa.project_id=? ORDER BY wa.sort_order,ws.sort_order,t.sort_order,a.sort_order`).bind(projectId).all(),
 c.env.DB.prepare(`SELECT l.governing_item_id,l.activity_id,a.title activity_title FROM governing_item_activity_links l JOIN governing_items i ON i.id=l.governing_item_id JOIN governing_documents d ON d.id=i.governing_document_id JOIN activities a ON a.id=l.activity_id WHERE d.project_id=?`).bind(projectId).all()]);
 const documents=documentsResult.results as any[],items=itemsResult.results as any[],activities=activitiesResult.results as any[],links=linksResult.results as any[];const linksByItem=new Map<string,any[]>(),linkCountByActivity=new Map<string,number>();for(const l of links){const k=String(l.governing_item_id),arr=linksByItem.get(k)||[];arr.push(l);linksByItem.set(k,arr);const aid=String(l.activity_id);linkCountByActivity.set(aid,(linkCountByActivity.get(aid)||0)+1)}
 const itemRows=items.map(i=>{const ls=linksByItem.get(String(i.id))||[];return{...i,mapped_activity_count:ls.length,mapped_activity_titles:ls.map(x=>x.activity_title).join(' || ')||null}});const activityRows=activities.map(a=>({...a,governing_item_count:linkCountByActivity.get(String(a.id))||0}));const af=new Map<string,Features>();for(const a of activityRows)af.set(String(a.id),targetFeatures(a));
 const suggestions:Record<string,any[]>={};for(const item of itemRows){if(Number(item.mapped_activity_count)>0||EXCEPTIONS.includes(String(item.handling_status||'')))continue;const sf=sourceFeatures(item);let ranked=activityRows.map(a=>({a,confidence:similarity(sf,af.get(String(a.id))!)})).filter(x=>x.confidence>=54).sort((x,y)=>y.confidence-x.confidence);if(ranked.length){const top=ranked[0].confidence;ranked=ranked.filter(x=>x.confidence>=top-8).slice(0,3)}if(ranked.length)suggestions[String(item.id)]=ranked.map(x=>({activity_id:x.a.id,title:x.a.title,task_title:x.a.task_title,section_name:x.a.section_name,area_name:x.a.area_name,confidence:x.confidence}))}
 const documentRows=documents.map(d=>{const di=itemRows.filter(i=>String(i.governing_document_id)===String(d.id));const item_count=di.length,exception_count=di.filter(i=>EXCEPTIONS.includes(String(i.handling_status||''))).length,mapped_count=di.filter(i=>!EXCEPTIONS.includes(String(i.handling_status||''))&&Number(i.mapped_activity_count)>0).length,uncovered_count=di.filter(i=>!EXCEPTIONS.includes(String(i.handling_status||''))&&Number(i.mapped_activity_count)===0).length,covered_count=mapped_count+exception_count;return{...d,item_count,mapped_count,exception_count,uncovered_count,covered_count,coverage_percent:item_count?Math.round(covered_count*100/item_count):100}});const total=documentRows.reduce((s,r)=>s+r.item_count,0),mapped=documentRows.reduce((s,r)=>s+r.mapped_count,0),exceptions=documentRows.reduce((s,r)=>s+r.exception_count,0),uncovered=documentRows.reduce((s,r)=>s+r.uncovered_count,0),covered=mapped+exceptions;return c.json({ok:true,runtime:'mapping-v5',summary:{item_count:total,mapped_count:mapped,exception_count:exceptions,covered_count:covered,uncovered_count:uncovered,coverage_percent:total?Math.round(covered*100/total):100},documents:documentRows,items:itemRows,activities:activityRows,suggestions})}catch(e){console.error('Governing mapping v5 read failed',e);return c.json({ok:false,runtime:'mapping-v5',error:`Kartläggning v5: ${e instanceof Error?e.message:String(e)}`},500)}});
app.put('/api/studio/governing-items/:itemId/mappings/:activityId',async c=>{try{await schema(c.env.DB);const itemId=c.req.param('itemId'),activityId=c.req.param('activityId'),body=await c.req.json<Record<string,unknown>>().catch(()=>({}));const pair=await c.env.DB.prepare(`SELECT i.id item_id,a.id activity_id FROM governing_items i JOIN governing_documents d ON d.id=i.governing_document_id CROSS JOIN activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections ws ON ws.id=t.work_section_id JOIN work_areas wa ON wa.id=ws.work_area_id WHERE i.id=? AND a.id=? AND d.project_id=wa.project_id`).bind(itemId,activityId).first();if(!pair)return c.json({ok:false,error:'Posten och aktiviteten tillhör inte samma projekt.'},409);const raw=Number(body.confidence),confidence=Number.isFinite(raw)?Math.max(0,Math.min(100,Math.round(raw))):null,source=String(body.mappingSource||'manual')==='suggested'?'suggested':'manual',comment=typeof body.comment==='string'?body.comment.trim():'';await c.env.DB.prepare(`INSERT INTO governing_item_activity_links(id,governing_item_id,activity_id,link_type,mapping_source,confidence,mapping_comment,created_at,confirmed_at) VALUES(?,?,?,'supports',?,?,?,datetime('now'),datetime('now')) ON CONFLICT(governing_item_id,activity_id) DO UPDATE SET mapping_source=excluded.mapping_source,confidence=excluded.confidence,mapping_comment=excluded.mapping_comment,confirmed_at=datetime('now')`).bind(crypto.randomUUID(),itemId,activityId,source,confidence,comment).run();return c.json({ok:true,runtime:'mapping-v5'})}catch(e){console.error('Governing mapping v5 write failed',e);return c.json({ok:false,runtime:'mapping-v5',error:`Koppling v5: ${e instanceof Error?e.message:String(e)}`},500)}})}
