type RouteApp={get:(path:string,handler:(c:any)=>unknown)=>void;put:(path:string,handler:(c:any)=>unknown)=>void};
const EXCEPTIONS=['not_applicable','cannot_verify','alternative_evidence'];
async function addColumn(db:D1Database,sql:string){try{await db.prepare(sql).run()}catch(e){const m=(e instanceof Error?e.message:String(e)).toLowerCase();if(!m.includes('duplicate column')&&!m.includes('already exists'))throw e}}
async function schema(db:D1Database){await addColumn(db,"ALTER TABLE governing_items ADD COLUMN source_note TEXT NOT NULL DEFAULT ''");await addColumn(db,"ALTER TABLE governing_item_activity_links ADD COLUMN mapping_source TEXT NOT NULL DEFAULT 'manual'");await addColumn(db,'ALTER TABLE governing_item_activity_links ADD COLUMN confidence INTEGER');await addColumn(db,"ALTER TABLE governing_item_activity_links ADD COLUMN mapping_comment TEXT NOT NULL DEFAULT ''");await addColumn(db,'ALTER TABLE governing_item_activity_links ADD COLUMN confirmed_at TEXT')}
function norm(v:unknown){return String(v||'').toLocaleLowerCase('sv-SE').replace(/[–—]/g,'-').replace(/[^a-zåäö0-9+\-/ ]/g,' ').replace(/\s+/g,' ').trim()}
const STOP=new Set(['enligt','eller','samt','skall','ska','utförd','utföras','kontroll','kontrollera','dokumentation','upprättad','beaktad','genomför','genomförd','erforderlig','erforderliga','byggnaden','byggnadens','projektet']);
function words(v:unknown){return norm(v).split(/\s+/).filter(w=>w.length>=4&&!STOP.has(w))}
type R={code:string;patterns:RegExp[]};
const RULES:R[]=[
{code:'setout',patterns:[/utsätt/,/referenshöjd/]},{code:'location_control',patterns:[/lägeskontroll/,/kontrollmät/,/mätintyg/,/byggnadens placering/]},{code:'bas_p',patterns:[/bas-p/,/bas p/]},{code:'bas_u',patterns:[/bas-u/,/bas u/]},{code:'work_environment',patterns:[/arbetsmiljö/]},{code:'start_meeting',patterns:[/startmöte/]},{code:'ka_ground_visit',patterns:[/besök.*grundbotten/,/grundbotten.*ka/]},{code:'ka_frame_visit',patterns:[/besök.*stomm.*rest/,/stomm.*rest.*ka/]},{code:'authority_site_visit',patterns:[/arbetsplatsbesök/,/byggnadsnämnd.*besök/]},{code:'permit_conformance',patterns:[/överensstämmelse.*bygglov/,/bygglov.*överensstämmelse/,/färdig.*mot.*lov/]},{code:'geotechnical',patterns:[/geotekn/]},{code:'radon',patterns:[/radon/]},{code:'structural_control',patterns:[/bärande stom/,/konstruktionshandling/,/stomkontroll/]},{code:'fire_description',patterns:[/brandskyddsbeskriv/]},{code:'fire_documentation',patterns:[/brandskyddsdokument/]},{code:'fire',patterns:[/brandskydd/,/brandvarn/,/rökkanal/,/sotar/,/eldstad/]},{code:'stormwater',patterns:[/dagvatten/,/markfall/,/\blod\b/]},{code:'wetroom_method',patterns:[/byggkeramik/,/våtrumsmetod/,/tätskikt/]},{code:'moisture',patterns:[/fuktsäker/,/fuktskydd/,/fukt/]},{code:'vvs_pressure',patterns:[/provtryck/,/täthets.*vvs/,/vvs.*täthet/]},{code:'vvs',patterns:[/\bvvs\b/,/spillvatten/,/vatteninstallation/,/\bva\b/]},{code:'electrical_contractor',patterns:[/elinstallationsföretag/,/registrerat.*el/]},{code:'electrical_insulation',patterns:[/isolationsprov/]},{code:'electrical_rcd',patterns:[/jordfelsbryt/]},{code:'electrical',patterns:[/elinstallation/,/elarbet/,/elintyg/,/elsäker/]},{code:'architect_control',patterns:[/arkitektens egenkontroll/]},{code:'accessibility',patterns:[/tillgänglighet/,/användbarhet/]},{code:'broadband',patterns:[/bredband/,/fiberanslut/,/fiber/]},{code:'final_docs',patterns:[/slutdokument/,/relationshandling/,/intyg.*protokoll/]}
];
function concepts(v:unknown){const t=norm(v),s=new Set<string>();for(const r of RULES)if(r.patterns.some(p=>p.test(t)))s.add(r.code);return s}
function domain(c:string){if(['setout','location_control'].includes(c))return'location';if(['bas_p','bas_u','work_environment','start_meeting'].includes(c))return'administration';if(['ka_ground_visit','geotechnical','radon'].includes(c))return'ground';if(['ka_frame_visit','structural_control'].includes(c))return'structure';if(['authority_site_visit','permit_conformance'].includes(c))return'authority';if(c.startsWith('fire'))return'fire';if(c==='stormwater')return'stormwater';if(c==='wetroom_method')return'wetroom';if(c==='moisture')return'moisture';if(c.startsWith('vvs'))return'vvs';if(c.startsWith('electrical'))return'electrical';if(['architect_control','accessibility'].includes(c))return'architecture';if(c==='broadband')return'broadband';return c}
function overlap<T>(a:Set<T>,b:Set<T>){for(const x of a)if(b.has(x))return true;return false}
type Features={concepts:Set<string>;domains:Set<string>;words:Set<string>};
function features(v:string):Features{const c=concepts(v);return{concepts:c,domains:new Set([...c].map(domain)),words:new Set(words(v))}}
function similarity(sf:Features,tf:Features){if(sf.domains.size&&tf.domains.size&&!overlap(sf.domains,tf.domains))return 0;let hits=0;for(const w of sf.words)if(tf.words.has(w))hits++;const lexical=sf.words.size&&tf.words.size?Math.round(35*hits/Math.max(2,Math.min(sf.words.size,tf.words.size))):0;let score=lexical;if(overlap(sf.concepts,tf.concepts))score+=62;else if(overlap(sf.domains,tf.domains))score+=36;if(sf.concepts.size&&!tf.concepts.size)score=Math.min(score,lexical>=24?48:0);return Math.max(0,Math.min(98,score))}
export function registerGoverningMappingRoutesV3(app:RouteApp){
app.get('/api/studio/projects/:projectId/governing-mapping',async c=>{try{await schema(c.env.DB);const projectId=c.req.param('projectId');
const [documentsResult,itemsResult,activitiesResult,linksResult]=await Promise.all([
c.env.DB.prepare(`SELECT id,document_type,title,issuer,reference,imported_at FROM governing_documents WHERE project_id=? ORDER BY CASE document_type WHEN 'control_plan' THEN 0 ELSE 1 END,imported_at,title`).bind(projectId).all(),
c.env.DB.prepare(`SELECT i.id,i.governing_document_id,i.code,i.description,i.section_code,i.section_title,i.item_type,i.responsible_role,i.handling_status,i.source_note,i.sort_order,d.imported_at FROM governing_items i JOIN governing_documents d ON d.id=i.governing_document_id WHERE d.project_id=? ORDER BY d.imported_at,i.sort_order,i.id`).bind(projectId).all(),
c.env.DB.prepare(`SELECT a.id,a.title,a.description,a.activity_type,t.title task_title,ws.name section_name,wa.name area_name,wa.sort_order area_order,ws.sort_order section_order,t.sort_order task_order,a.sort_order activity_order FROM activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections ws ON ws.id=t.work_section_id JOIN work_areas wa ON wa.id=ws.work_area_id WHERE wa.project_id=? ORDER BY wa.sort_order,ws.sort_order,t.sort_order,a.sort_order`).bind(projectId).all(),
c.env.DB.prepare(`SELECT l.governing_item_id,l.activity_id,a.title activity_title FROM governing_item_activity_links l JOIN governing_items i ON i.id=l.governing_item_id JOIN governing_documents d ON d.id=i.governing_document_id JOIN activities a ON a.id=l.activity_id WHERE d.project_id=?`).bind(projectId).all()
]);
const documents=documentsResult.results as any[],items=itemsResult.results as any[],activities=activitiesResult.results as any[],links=linksResult.results as any[];
const linksByItem=new Map<string,any[]>(),linkCountByActivity=new Map<string,number>();for(const l of links){const key=String(l.governing_item_id),arr=linksByItem.get(key)||[];arr.push(l);linksByItem.set(key,arr);const aid=String(l.activity_id);linkCountByActivity.set(aid,(linkCountByActivity.get(aid)||0)+1)}
const itemRows=items.map(i=>{const ls=linksByItem.get(String(i.id))||[];return{...i,mapped_activity_count:ls.length,mapped_activity_titles:ls.map(x=>x.activity_title).join(' || ')||null}});
const activityRows=activities.map(a=>({...a,governing_item_count:linkCountByActivity.get(String(a.id))||0}));
const activityFeatures=new Map<string,Features>();for(const a of activityRows)activityFeatures.set(String(a.id),features(`${a.title} ${a.description||''} ${a.task_title} ${a.section_name} ${a.area_name}`));
const suggestions:Record<string,any[]>={};for(const item of itemRows){if(Number(item.mapped_activity_count)>0||EXCEPTIONS.includes(String(item.handling_status||'')))continue;const sf=features(`${item.description} ${item.section_title} ${item.source_note||''}`);const ranked=activityRows.map(a=>({a,confidence:similarity(sf,activityFeatures.get(String(a.id))!)})).filter(x=>x.confidence>=48).sort((x,y)=>y.confidence-x.confidence).slice(0,3).map(x=>({activity_id:x.a.id,title:x.a.title,task_title:x.a.task_title,section_name:x.a.section_name,area_name:x.a.area_name,confidence:x.confidence}));if(ranked.length)suggestions[String(item.id)]=ranked}
const documentRows=documents.map(d=>{const di=itemRows.filter(i=>String(i.governing_document_id)===String(d.id));const item_count=di.length,exception_count=di.filter(i=>EXCEPTIONS.includes(String(i.handling_status||''))).length,mapped_count=di.filter(i=>!EXCEPTIONS.includes(String(i.handling_status||''))&&Number(i.mapped_activity_count)>0).length,uncovered_count=di.filter(i=>!EXCEPTIONS.includes(String(i.handling_status||''))&&Number(i.mapped_activity_count)===0).length,covered_count=mapped_count+exception_count;return{...d,item_count,mapped_count,exception_count,uncovered_count,covered_count,coverage_percent:item_count?Math.round(covered_count*100/item_count):100}});
const total=documentRows.reduce((s,r)=>s+r.item_count,0),mapped=documentRows.reduce((s,r)=>s+r.mapped_count,0),exceptions=documentRows.reduce((s,r)=>s+r.exception_count,0),uncovered=documentRows.reduce((s,r)=>s+r.uncovered_count,0),covered=mapped+exceptions;
return c.json({ok:true,runtime:'mapping-v3',summary:{item_count:total,mapped_count:mapped,exception_count:exceptions,covered_count:covered,uncovered_count:uncovered,coverage_percent:total?Math.round(covered*100/total):100},documents:documentRows,items:itemRows,activities:activityRows,suggestions})}catch(e){console.error('Governing mapping v3 read failed',e);return c.json({ok:false,runtime:'mapping-v3',error:`Kartläggning v3: ${e instanceof Error?e.message:String(e)}`},500)}});
app.put('/api/studio/governing-items/:itemId/mappings/:activityId',async c=>{try{await schema(c.env.DB);const itemId=c.req.param('itemId'),activityId=c.req.param('activityId'),body=await c.req.json<Record<string,unknown>>().catch(()=>({}));const pair=await c.env.DB.prepare(`SELECT i.id item_id,a.id activity_id FROM governing_items i JOIN governing_documents d ON d.id=i.governing_document_id CROSS JOIN activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections ws ON ws.id=t.work_section_id JOIN work_areas wa ON wa.id=ws.work_area_id WHERE i.id=? AND a.id=? AND d.project_id=wa.project_id`).bind(itemId,activityId).first();if(!pair)return c.json({ok:false,error:'Posten och aktiviteten tillhör inte samma projekt.'},409);const raw=Number(body.confidence),confidence=Number.isFinite(raw)?Math.max(0,Math.min(100,Math.round(raw))):null,source=String(body.mappingSource||'manual')==='suggested'?'suggested':'manual',comment=typeof body.comment==='string'?body.comment.trim():'';await c.env.DB.prepare(`INSERT INTO governing_item_activity_links(id,governing_item_id,activity_id,link_type,mapping_source,confidence,mapping_comment,created_at,confirmed_at) VALUES(?,?,?,'supports',?,?,?,datetime('now'),datetime('now')) ON CONFLICT(governing_item_id,activity_id) DO UPDATE SET mapping_source=excluded.mapping_source,confidence=excluded.confidence,mapping_comment=excluded.mapping_comment,confirmed_at=datetime('now')`).bind(crypto.randomUUID(),itemId,activityId,source,confidence,comment).run();return c.json({ok:true,runtime:'mapping-v3'})}catch(e){console.error('Governing mapping v3 write failed',e);return c.json({ok:false,runtime:'mapping-v3',error:`Koppling v3: ${e instanceof Error?e.message:String(e)}`},500)}})}
