type RouteApp={get:(path:string,handler:(c:any)=>unknown)=>void;post:(path:string,handler:(c:any)=>unknown)=>void};
function clean(v:unknown){return typeof v==='string'?v.trim():''}
function norm(v:unknown){return clean(v).toLocaleLowerCase('sv-SE').replace(/\s+/g,' ').trim()}
async function tableExists(db:D1Database,name:string){return Boolean(await db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").bind(name).first())}
async function ensureSchema(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS governing_document_version_activation_log(id TEXT PRIMARY KEY,document_id TEXT NOT NULL,version_id TEXT NOT NULL,summary_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT (datetime('now')))`).run()}
async function candidate(db:D1Database,documentId:string,versionId:string){return db.prepare("SELECT v.*,d.title document_title FROM governing_document_versions v JOIN governing_documents d ON d.id=v.document_id WHERE v.id=? AND v.document_id=? AND v.status='candidate'").bind(versionId,documentId).first<any>()}
async function currentItems(db:D1Database,documentId:string){const r=await db.prepare('SELECT * FROM governing_items WHERE governing_document_id=? ORDER BY sort_order,id').bind(documentId).all();return r.results as any[]}
async function draftItems(db:D1Database,versionId:string){const r=await db.prepare('SELECT * FROM governing_document_version_items WHERE version_id=? ORDER BY sort_order,id').bind(versionId).all();return r.results as any[]}
function changed(a:any,b:any){return ['description','section_code','section_title','item_type','responsible_role','evidence_required','source_note'].some(k=>norm(a?.[k])!==norm(b?.[k]))}
async function decisionMap(db:D1Database,versionId:string){const r=await db.prepare('SELECT change_key,action,selected_activity_ids,comment FROM governing_document_version_decisions WHERE version_id=?').bind(versionId).all();return new Map((r.results as any[]).map(x=>[String(x.change_key),x]))}
function parseIds(v:unknown){try{const x=JSON.parse(String(v||'[]'));return Array.isArray(x)?x.map(clean).filter(Boolean):[]}catch{return[]}}
function instruction(item:any){const bits=[`Kontrollplan ${clean(item.code)}`.trim()+`: ${clean(item.description)}`];if(clean(item.source_note))bits.push(`Kontroll mot: ${clean(item.source_note)}`);if(clean(item.evidence_required))bits.push(`Verifiering/dokumentation: ${clean(item.evidence_required)}`);return bits.join('. ')+'.'}
function childSafety(item:any){return /knivlåda|medicinskåp|klassat glas|barnsäker/i.test(`${item.description||''} ${item.section_title||''}`)}
async function targetTask(db:D1Database,projectId:string,item:any){if(childSafety(item)){return db.prepare(`SELECT t.id,t.title,s.name section_name,w.name area_name FROM tasks t JOIN work_sections s ON s.id=t.work_section_id JOIN work_areas w ON w.id=s.work_area_id WHERE w.project_id=? AND lower(trim(w.name))=lower(trim('Säkerhet och färdigställande')) AND lower(trim(s.name))=lower(trim('Säkerhet')) AND lower(trim(t.title))=lower(trim('Kontrollera säkerhet vid användning')) LIMIT 1`).bind(projectId).first<any>()}return null}
async function preview(db:D1Database,documentId:string,versionId:string){const cand=await candidate(db,documentId,versionId);if(!cand)return null;const current=await currentItems(db,documentId),draft=await draftItems(db,versionId),decisions=await decisionMap(db,versionId),currentById=new Map(current.map(x=>[String(x.id),x])),draftBySource=new Map(draft.filter(x=>x.source_item_id).map(x=>[String(x.source_item_id),x]));const actions:any[]=[];let unresolved=0;
 for(const old of current){const next=draftBySource.get(String(old.id));if(!next){const key=`removed:${old.id}`,d=decisions.get(key),action=String(d?.action||'defer');if(action==='defer')unresolved++;actions.push({key,kind:'removed',code:old.code,description:old.description,action,effect:action==='keep_historical'?'Tas bort ur aktiv version men finns kvar i versionshistoriken.':action==='unlink_only'?'Tas bort ur aktiv version; aktiviteter lämnas kvar.':'Inget genomförs förrän beslut fattats.'});continue}if(changed(old,next)){const key=`changed:${old.id}`,d=decisions.get(key),action=String(d?.action||'defer');if(action==='defer'||action==='review_links')unresolved++;actions.push({key,kind:'changed',code:next.code,description:next.description,action,effect:action==='update_keep_links'?'Styrpunkten uppdateras på samma ID; befintliga aktivitetskopplingar och utförandedata bevaras.':action==='keep_old'?'Gamla styrpunkten behålls oförändrad.':'Kräver slutligt beslut.'})}}
 for(const next of draft)if(!next.source_item_id||!currentById.has(String(next.source_item_id))){const key=`added:${next.id}`,d=decisions.get(key),action=String(d?.action||'defer'),ids=parseIds(d?.selected_activity_ids);if(action==='defer'||(action==='link_existing'&&!ids.length))unresolved++;let effect='Kräver slutligt beslut.';if(action==='link_existing')effect=`Ny styrpunkt skapas och kopplas till ${ids.length} befintlig aktivitet${ids.length===1?'':'er'}. Kontrollplanens instruktion läggs till i aktivitetens beskrivning.`;if(action==='create_activity'){const task=await targetTask(db,String(cand.project_id),next);effect=task?`Ny styrpunkt och ny aktivitet skapas under ${task.area_name} › ${task.section_name} › ${task.title}. Kontrollplanens instruktion används som aktivitetsbeskrivning.`:'Placeringsförslag saknas; aktivering spärras.';if(!task)unresolved++}actions.push({key,kind:'added',code:next.code,description:next.description,action,effect,instruction:instruction(next),selectedActivityIds:ids})}
 return{candidate:cand,actions,unresolved,summary:{added:actions.filter(x=>x.kind==='added').length,changed:actions.filter(x=>x.kind==='changed').length,removed:actions.filter(x=>x.kind==='removed').length}}}
async function appendInstruction(db:D1Database,activityId:string,text:string){const row=await db.prepare('SELECT description FROM activities WHERE id=?').bind(activityId).first<any>();if(!row)return false;const current=String(row.description||'').trim();if(norm(current).includes(norm(text)))return true;const next=current?`${current}\n\nStyrdokument – tillkommande kontroll:\n• ${text}`:`Styrdokument – kontrollinstruktion:\n• ${text}`;await db.prepare('UPDATE activities SET description=? WHERE id=?').bind(next,activityId).run();return true}
async function snapshotActive(db:D1Database,documentId:string,current:any[]){const active=await db.prepare("SELECT id FROM governing_document_versions WHERE document_id=? AND status='active' ORDER BY version_no DESC LIMIT 1").bind(documentId).first<any>();if(!active)return;const count=await db.prepare('SELECT COUNT(*) n FROM governing_document_version_items WHERE version_id=?').bind(active.id).first<any>();if(Number(count?.n||0)>0)return;for(let i=0;i<current.length;i++){const x=current[i];await db.prepare(`INSERT INTO governing_document_version_items(id,version_id,source_item_id,code,description,section_code,section_title,item_type,responsible_role,evidence_required,source_note,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),active.id,x.id,x.code||'',x.description||'',x.section_code||'',x.section_title||'',x.item_type||'other',x.responsible_role||'',x.evidence_required||'',x.source_note||'',Number(x.sort_order||((i+1)*10))).run()}}
export function registerGoverningVersionApplyRoutes(app:RouteApp){
 app.get('/api/studio/governing-documents/:id/version-candidates/:versionId/apply-preview',async c=>{await ensureSchema(c.env.DB);const p=await preview(c.env.DB,String(c.req.param('id')),String(c.req.param('versionId')));if(!p)return c.json({ok:false,error:'Kandidatversionen hittades inte.'},404);return c.json({ok:true,...p,safeToApply:p.unresolved===0})});
 app.post('/api/studio/governing-documents/:id/version-candidates/:versionId/apply',async c=>{await ensureSchema(c.env.DB);const documentId=String(c.req.param('id')),versionId=String(c.req.param('versionId')),p=await preview(c.env.DB,documentId,versionId);if(!p)return c.json({ok:false,error:'Kandidatversionen hittades inte.'},404);if(p.unresolved>0)return c.json({ok:false,error:`Versionsbytet har ${p.unresolved} olösta beslut och kan inte genomföras.`},409);const current=await currentItems(c.env.DB,documentId),draft=await draftItems(c.env.DB,versionId),decisions=await decisionMap(c.env.DB,versionId),currentById=new Map(current.map(x=>[String(x.id),x])),draftBySource=new Map(draft.filter(x=>x.source_item_id).map(x=>[String(x.source_item_id),x]));await snapshotActive(c.env.DB,documentId,current);
  for(const old of current){const next=draftBySource.get(String(old.id));if(!next){const d=decisions.get(`removed:${old.id}`),action=String(d?.action||'defer');if(action==='keep_historical'||action==='unlink_only')await c.env.DB.prepare('DELETE FROM governing_items WHERE id=?').bind(old.id).run();continue}if(changed(old,next)){const action=String(decisions.get(`changed:${old.id}`)?.action||'defer');if(action==='update_keep_links')await c.env.DB.prepare(`UPDATE governing_items SET code=?,description=?,section_code=?,section_title=?,item_type=?,responsible_role=?,evidence_required=?,source_note=?,sort_order=?,updated_at=datetime('now') WHERE id=?`).bind(next.code||'',next.description||'',next.section_code||'',next.section_title||'',next.item_type||'other',next.responsible_role||'',next.evidence_required||'',next.source_note||'',Number(next.sort_order||0),old.id).run()}}
  for(const next of draft)if(!next.source_item_id||!currentById.has(String(next.source_item_id))){const d=decisions.get(`added:${next.id}`),action=String(d?.action||'defer'),itemId=crypto.randomUUID();await c.env.DB.prepare(`INSERT INTO governing_items(id,governing_document_id,code,description,section_code,section_title,item_type,responsible_role,evidence_required,source_note,handling_status,handling_comment,sort_order,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'unhandled','',?,datetime('now'))`).bind(itemId,documentId,next.code||'',next.description||'',next.section_code||'',next.section_title||'',next.item_type||'other',next.responsible_role||'',next.evidence_required||'',next.source_note||'',Number(next.sort_order||0)).run();const ins=instruction(next);if(action==='link_existing'){for(const activityId of parseIds(d?.selected_activity_ids)){const a=await c.env.DB.prepare(`SELECT a.id FROM activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections s ON s.id=t.work_section_id JOIN work_areas w ON w.id=s.work_area_id WHERE a.id=? AND w.project_id=?`).bind(activityId,p.candidate.project_id).first();if(!a)continue;await c.env.DB.prepare(`INSERT OR IGNORE INTO governing_item_activity_links(id,governing_item_id,activity_id,link_type,mapping_source,confidence,mapping_comment,created_at) VALUES(?,?,?,'supports','version_update',100,?,datetime('now'))`).bind(crypto.randomUUID(),itemId,activityId,`Tillagd vid aktivering av ${p.candidate.version_label}`).run();await appendInstruction(c.env.DB,activityId,ins)}}else if(action==='create_activity'){const task=await targetTask(c.env.DB,String(p.candidate.project_id),next);if(!task)return c.json({ok:false,error:`Kunde inte hitta föreslagen placering för ${next.code}.`},409);const activityId=crypto.randomUUID(),order=await c.env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+10 n FROM activities WHERE task_id=?').bind(task.id).first<any>(),title=`Kontrollera ${String(next.description||'styrpunkt').replace(/^Kontrollera\s+/i,'')}`;await c.env.DB.prepare(`INSERT INTO activities(id,task_id,title,description,activity_type,required,blocking,irreversible,sort_order) VALUES(?,?,?,?, 'check',1,0,0,?)`).bind(activityId,task.id,title,ins,Number(order?.n||10)).run();await c.env.DB.prepare(`INSERT OR IGNORE INTO governing_item_activity_links(id,governing_item_id,activity_id,link_type,mapping_source,confidence,mapping_comment,created_at) VALUES(?,?,?,'supports','version_update',100,?,datetime('now'))`).bind(crypto.randomUUID(),itemId,activityId,`Skapad vid aktivering av ${p.candidate.version_label}`).run()}}
  const previous=await c.env.DB.prepare("SELECT id FROM governing_document_versions WHERE document_id=? AND status='active'").bind(documentId).all();for(const r of previous.results as any[])await c.env.DB.prepare("UPDATE governing_document_versions SET status='historical' WHERE id=?").bind(r.id).run();await c.env.DB.prepare("UPDATE governing_document_versions SET status='active',activated_at=datetime('now') WHERE id=?").bind(versionId).run();await c.env.DB.prepare("UPDATE governing_documents SET source_filename=?,source_mime_type=?,updated_at=datetime('now') WHERE id=?").bind(p.candidate.original_name,p.candidate.content_type,documentId).run();const summary={version:p.candidate.version_label,added:p.summary.added,changed:p.summary.changed,removed:p.summary.removed};await c.env.DB.prepare('INSERT INTO governing_document_version_activation_log(id,document_id,version_id,summary_json) VALUES(?,?,?,?)').bind(crypto.randomUUID(),documentId,versionId,JSON.stringify(summary)).run();return c.json({ok:true,summary})
 })
}
