type RouteApp={get:(path:string,handler:(c:any)=>unknown)=>void;put:(path:string,handler:(c:any)=>unknown)=>void};
const EXCEPTIONS=['not_applicable','cannot_verify','alternative_evidence'];
async function addColumn(db:D1Database,sql:string){try{await db.prepare(sql).run()}catch(e){const m=(e instanceof Error?e.message:String(e)).toLowerCase();if(!m.includes('duplicate column')&&!m.includes('already exists'))throw e}}
async function schema(db:D1Database){await addColumn(db,"ALTER TABLE governing_items ADD COLUMN source_note TEXT NOT NULL DEFAULT ''");await addColumn(db,"ALTER TABLE governing_item_activity_links ADD COLUMN mapping_source TEXT NOT NULL DEFAULT 'manual'");await addColumn(db,'ALTER TABLE governing_item_activity_links ADD COLUMN confidence INTEGER');await addColumn(db,"ALTER TABLE governing_item_activity_links ADD COLUMN mapping_comment TEXT NOT NULL DEFAULT ''");await addColumn(db,'ALTER TABLE governing_item_activity_links ADD COLUMN confirmed_at TEXT');await db.prepare("UPDATE governing_item_activity_links SET mapping_source=COALESCE(NULLIF(mapping_source,''),'manual'),confirmed_at=COALESCE(confirmed_at,created_at) WHERE mapping_source IS NULL OR mapping_source='' OR confirmed_at IS NULL").run()}
function norm(v:unknown){return String(v||'').toLocaleLowerCase('sv-SE').replace(/[–—]/g,'-').replace(/[^a-zåäö0-9+\-/ ]/g,' ').replace(/\s+/g,' ').trim()}
const STOP=new Set(['enligt','eller','samt','skall','ska','utförd','utföras','kontroll','kontrollera','dokumentation','upprättad','beaktad','genomför','genomförd','erforderlig','erforderliga','byggnaden','byggnadens','projektet']);
function words(v:unknown){return norm(v).split(/\s+/).filter(w=>w.length>=4&&!STOP.has(w))}
type R={code:string;patterns:RegExp[]};
const RULES:R[]=[
{code:'setout',patterns:[/utsätt/,/referenshöjd/]},{code:'location_control',patterns:[/lägeskontroll/,/kontrollmät/,/mätintyg/,/byggnadens placering/]},{code:'bas_p',patterns:[/bas-p/,/bas p/]},{code:'bas_u',patterns:[/bas-u/,/bas u/]},{code:'work_environment',patterns:[/arbetsmiljö/]},{code:'start_meeting',patterns:[/startmöte/]},{code:'ka_ground_visit',patterns:[/besök.*grundbotten/,/grundbotten.*ka/]},{code:'ka_frame_visit',patterns:[/besök.*stomm.*rest/,/stomm.*rest.*ka/]},{code:'authority_site_visit',patterns:[/arbetsplatsbesök/,/byggnadsnämnd.*besök/]},{code:'permit_conformance',patterns:[/överensstämmelse.*bygglov/,/bygglov.*överensstämmelse/,/färdig.*mot.*lov/]},{code:'geotechnical',patterns:[/geotekn/]},{code:'radon',patterns:[/radon/]},{code:'structural_control',patterns:[/bärande stom/,/konstruktionshandling/,/stomkontroll/]},{code:'fire_description',patterns:[/brandskyddsbeskriv/]},{code:'fire_documentation',patterns:[/brandskyddsdokument/]},{code:'fire',patterns:[/brandskydd/,/brandvarn/,/rökkanal/,/sotar/,/eldstad/]},{code:'stormwater',patterns:[/dagvatten/,/markfall/,/\blod\b/]},{code:'wetroom_method',patterns:[/byggkeramik/,/våtrumsmetod/,/tätskikt/]},{code:'moisture',patterns:[/fuktsäker/,/fuktskydd/,/fukt/]},{code:'vvs_pressure',patterns:[/provtryck/,/täthets.*vvs/,/vvs.*täthet/]},{code:'vvs',patterns:[/\bvvs\b/,/spillvatten/,/vatteninstallation/,/\bva\b/]},{code:'electrical_contractor',patterns:[/elinstallationsföretag/,/registrerat.*el/]},{code:'electrical_insulation',patterns:[/isolationsprov/]},{code:'electrical_rcd',patterns:[/jordfelsbryt/]},{code:'electrical',patterns:[/elinstallation/,/elarbet/,/elintyg/,/elsäker/]},{code:'architect_control',patterns:[/arkitektens egenkontroll/]},{code:'accessibility',patterns:[/tillgänglighet/,/användbarhet/]},{code:'broadband',patterns:[/bredband/,/fiberanslut/,/fiber/]},{code:'final_docs',patterns:[/slutdokument/,/relationshandling/,/intyg.*protokoll/]}
];
function concepts(v:unknown){const t=norm(v),s=new Set<string>();for(const r of RULES)if(r.patterns.some(p=>p.test(t)))s.add(r.code);return s}
function domain(c:string){if(['setout','location_control'].includes(c))return'location';if(['bas_p','bas_u','work_environment','start_meeting'].includes(c))return'administration';if(['ka_ground_visit','geotechnical','radon'].includes(c))return'ground';if(['ka_frame_visit','structural_control'].includes(c))return'structure';if(['authority_site_visit','permit_conformance'].includes(c))return'authority';if(c.startsWith('fire'))return'fire';if(c==='stormwater')return'stormwater';if(c==='wetroom_method')return'wetroom';if(c==='moisture')return'moisture';if(c.startsWith('vvs'))return'vvs';if(c.startsWith('electrical'))return'electrical';if(['architect_control','accessibility'].includes(c))return'architecture';if(c==='broadband')return'broadband';return c}
function overlap<T>(a:Set<T>,b:Set<T>){for(const x of a)if(b.has(x))return true;return false}
function similarity(item:any,a:any){const st=`${item.description} ${item.section_title} ${item.source_note||''}`,tt=`${a.title} ${a.description||''} ${a.task_title} ${a.section_name} ${a.area_name}`;const sc=concepts(st),tc=concepts(tt),sd=new Set([...sc].map(domain)),td=new Set([...tc].map(domain));if(sd.size&&td.size&&!overlap(sd,td))return 0;const sw=new Set(words(st)),tw=new Set(words(tt));let hits=0;for(const w of sw)if(tw.has(w))hits++;const lexical=sw.size&&tw.size?Math.round(35*hits/Math.max(2,Math.min(sw.size,tw.size))):0;let score=lexical;if(overlap(sc,tc))score+=62;else if(overlap(sd,td))score+=36;if(sc.size&&!tc.size)score=Math.min(score,lexical>=24?48:0);return Math.max(0,Math.min(98,score))}
export function registerGoverningMappingRoutesV2(app:RouteApp){
app.get('/api/studio/projects/:projectId/governing-mapping',async c=>{try{await schema(c.env.DB);const projectId=c.req.param('projectId');const documents=await c.env.DB.prepare(`SELECT d.id,d.document_type,d.title,d.issuer,d.reference,
 (SELECT COUNT(*) FROM governing_items i WHERE i.governing_document_id=d.id) item_count,
 (SELECT COUNT(*) FROM governing_items i WHERE i.governing_document_id=d.id AND i.handling_status NOT IN ('not_applicable','cannot_verify','alternative_evidence') AND EXISTS(SELECT 1 FROM governing_item_activity_links l WHERE l.governing_item_id=i.id)) mapped_count,
 (SELECT COUNT(*) FROM governing_items i WHERE i.governing_document_id=d.id AND i.handling_status IN ('not_applicable','cannot_verify','alternative_evidence')) exception_count,
 (SELECT COUNT(*) FROM governing_items i WHERE i.governing_document_id=d.id AND i.handling_status NOT IN ('not_applicable','cannot_verify','alternative_evidence') AND NOT EXISTS(SELECT 1 FROM governing_item_activity_links l WHERE l.governing_item_id=i.id)) uncovered_count
 FROM governing_documents d WHERE d.project_id=? ORDER BY CASE d.document_type WHEN 'control_plan' THEN 0 ELSE 1 END,d.imported_at,d.title`).bind(projectId).all();
const items=await c.env.DB.prepare(`SELECT i.id,i.governing_document_id,i.code,i.description,i.section_code,i.section_title,i.item_type,i.responsible_role,i.handling_status,i.source_note,
 (SELECT COUNT(*) FROM governing_item_activity_links l WHERE l.governing_item_id=i.id) mapped_activity_count,
 (SELECT GROUP_CONCAT(a.title,' || ') FROM governing_item_activity_links l JOIN activities a ON a.id=l.activity_id WHERE l.governing_item_id=i.id) mapped_activity_titles
 FROM governing_items i JOIN governing_documents d ON d.id=i.governing_document_id WHERE d.project_id=? ORDER BY d.imported_at,i.sort_order,i.id`).bind(projectId).all();
const activities=await c.env.DB.prepare(`SELECT a.id,a.title,a.description,a.activity_type,t.title task_title,ws.name section_name,wa.name area_name,
 (SELECT COUNT(*) FROM governing_item_activity_links l WHERE l.activity_id=a.id) governing_item_count
 FROM activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections ws ON ws.id=t.work_section_id JOIN work_areas wa ON wa.id=ws.work_area_id WHERE wa.project_id=? ORDER BY wa.sort_order,ws.sort_order,t.sort_order,a.sort_order`).bind(projectId).all();
const ar=activities.results as any[],suggestions:Record<string,any[]>={};for(const item of items.results as any[]){if(Number(item.mapped_activity_count||0)>0||EXCEPTIONS.includes(String(item.handling_status||'')))continue;const ranked=ar.map(a=>({a,confidence:similarity(item,a)})).filter(x=>x.confidence>=48).sort((x,y)=>y.confidence-x.confidence).slice(0,3).map(x=>({activity_id:x.a.id,title:x.a.title,task_title:x.a.task_title,section_name:x.a.section_name,area_name:x.a.area_name,confidence:x.confidence}));if(ranked.length)suggestions[String(item.id)]=ranked}
const dr=(documents.results as any[]).map(r=>{const item_count=Number(r.item_count||0),mapped_count=Number(r.mapped_count||0),exception_count=Number(r.exception_count||0),uncovered_count=Number(r.uncovered_count||0),covered_count=mapped_count+exception_count;return{...r,item_count,mapped_count,exception_count,uncovered_count,covered_count,coverage_percent:item_count?Math.round(covered_count*100/item_count):100}});const total=dr.reduce((s,r)=>s+r.item_count,0),mapped=dr.reduce((s,r)=>s+r.mapped_count,0),exceptions=dr.reduce((s,r)=>s+r.exception_count,0),uncovered=dr.reduce((s,r)=>s+r.uncovered_count,0),covered=mapped+exceptions;return c.json({ok:true,summary:{item_count:total,mapped_count:mapped,exception_count:exceptions,covered_count:covered,uncovered_count:uncovered,coverage_percent:total?Math.round(covered*100/total):100},documents:dr,items:items.results,activities:ar,suggestions})}catch(e){console.error('Governing mapping read failed',e);return c.json({ok:false,error:`Kartläggning: ${e instanceof Error?e.message:String(e)}`},500)}});
app.put('/api/studio/governing-items/:itemId/mappings/:activityId',async c=>{try{await schema(c.env.DB);const itemId=c.req.param('itemId'),activityId=c.req.param('activityId'),body=await c.req.json<Record<string,unknown>>().catch(()=>({}));const pair=await c.env.DB.prepare(`SELECT i.id item_id,a.id activity_id FROM governing_items i JOIN governing_documents d ON d.id=i.governing_document_id CROSS JOIN activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections ws ON ws.id=t.work_section_id JOIN work_areas wa ON wa.id=ws.work_area_id WHERE i.id=? AND a.id=? AND d.project_id=wa.project_id`).bind(itemId,activityId).first();if(!pair)return c.json({ok:false,error:'Posten och aktiviteten tillhör inte samma projekt.'},409);const raw=Number(body.confidence),confidence=Number.isFinite(raw)?Math.max(0,Math.min(100,Math.round(raw))):null,source=String(body.mappingSource||'manual')==='suggested'?'suggested':'manual',comment=typeof body.comment==='string'?body.comment.trim():'';await c.env.DB.prepare(`INSERT INTO governing_item_activity_links(id,governing_item_id,activity_id,link_type,mapping_source,confidence,mapping_comment,created_at,confirmed_at) VALUES(?,?,?,'supports',?,?,?,datetime('now'),datetime('now')) ON CONFLICT(governing_item_id,activity_id) DO UPDATE SET mapping_source=excluded.mapping_source,confidence=excluded.confidence,mapping_comment=excluded.mapping_comment,confirmed_at=datetime('now')`).bind(crypto.randomUUID(),itemId,activityId,source,confidence,comment).run();return c.json({ok:true})}catch(e){console.error('Governing mapping write failed',e);return c.json({ok:false,error:`Koppling: ${e instanceof Error?e.message:String(e)}`},500)}})}
