type RouteApp={get:(path:string,handler:(c:any)=>unknown)=>void;put:(path:string,handler:(c:any)=>unknown)=>void};

type ChangeKind='changed'|'added'|'removed';
type DecisionAction='defer'|'link_existing'|'create_activity'|'update_keep_links'|'review_links'|'keep_old'|'keep_historical'|'unlink_only';

function clean(v:unknown){return typeof v==='string'?v.trim():''}
function norm(v:unknown){return clean(v).toLocaleLowerCase('sv-SE').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9åäö]+/g,' ').replace(/\s+/g,' ').trim()}
const STOP=new Set(['och','med','för','från','som','ska','skall','enligt','utförd','kontroll','egenkontroll','intyg','bevis','samt','eller','den','det','vid','mot','under']);
function tokens(v:unknown){return new Set(norm(v).split(' ').filter(x=>x.length>=4&&!STOP.has(x)))}
function intersectionSize(a:Set<string>,b:Set<string>){let n=0;for(const x of a)if(b.has(x))n++;return n}

async function tableExists(db:D1Database,name:string){return Boolean(await db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").bind(name).first())}
async function ensureSchema(db:D1Database){
 await db.prepare(`CREATE TABLE IF NOT EXISTS governing_document_version_decisions(
  id TEXT PRIMARY KEY,version_id TEXT NOT NULL,change_key TEXT NOT NULL,change_kind TEXT NOT NULL,action TEXT NOT NULL DEFAULT 'defer',selected_activity_ids TEXT NOT NULL DEFAULT '[]',comment TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(version_id,change_key),FOREIGN KEY(version_id) REFERENCES governing_document_versions(id) ON DELETE CASCADE
 )`).run();
 await db.prepare('CREATE INDEX IF NOT EXISTS idx_gov_version_decisions_version ON governing_document_version_decisions(version_id)').run();
}
async function getCandidate(db:D1Database,documentId:string,versionId:string){if(!await tableExists(db,'governing_document_versions'))return null;return db.prepare("SELECT id,project_id,status FROM governing_document_versions WHERE id=? AND document_id=? AND status='candidate'").bind(versionId,documentId).first<any>()}
async function currentItems(db:D1Database,documentId:string){const r=await db.prepare('SELECT id,code,description,section_code,section_title,item_type,responsible_role,evidence_required,source_note FROM governing_items WHERE governing_document_id=? ORDER BY sort_order,id').bind(documentId).all();return r.results as any[]}
async function draftItems(db:D1Database,versionId:string){if(!await tableExists(db,'governing_document_version_items'))return[];const r=await db.prepare('SELECT id,source_item_id,code,description,section_code,section_title,item_type,responsible_role,evidence_required,source_note FROM governing_document_version_items WHERE version_id=? ORDER BY sort_order,id').bind(versionId).all();return r.results as any[]}
function changed(oldRow:any,newRow:any){for(const k of ['description','section_code','section_title','item_type','responsible_role','evidence_required','source_note'])if(norm(oldRow?.[k])!==norm(newRow?.[k]))return true;return false}
async function projectActivities(db:D1Database,projectId:string){const r=await db.prepare(`SELECT a.id,a.title,a.activity_type,t.title task_title,ws.name section_name,wa.name area_name,COALESCE(e.done,0) done FROM activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections ws ON ws.id=t.work_section_id JOIN work_areas wa ON wa.id=ws.work_area_id LEFT JOIN activity_entries e ON e.activity_id=a.id WHERE wa.project_id=? ORDER BY wa.sort_order,ws.sort_order,t.sort_order,a.sort_order`).bind(projectId).all();return r.results as any[]}
async function linksForItems(db:D1Database,itemIds:string[]){const out:Record<string,any[]>={};if(!itemIds.length)return out;for(let i=0;i<itemIds.length;i+=60){const ids=itemIds.slice(i,i+60),ph=ids.map(()=>'?').join(',');const r=await db.prepare(`SELECT l.governing_item_id,a.id,a.title,a.activity_type,t.title task_title,ws.name section_name,wa.name area_name,COALESCE(e.done,0) done FROM governing_item_activity_links l JOIN activities a ON a.id=l.activity_id JOIN tasks t ON t.id=a.task_id JOIN work_sections ws ON ws.id=t.work_section_id JOIN work_areas wa ON wa.id=ws.work_area_id LEFT JOIN activity_entries e ON e.activity_id=a.id WHERE l.governing_item_id IN (${ph})`).bind(...ids).all();for(const row of r.results as any[])(out[String(row.governing_item_id)]||=[]).push(row)}return out}
function childSafety(text:string){return /barnsaker|knivlada|medicinskap|klassat glas|lagt sittande|sakerhetsbeslag/.test(norm(text).replace(/ /g,''))||/barn saker|kniv lada|medicin skap|klassat glas|lagt sittande|sakerhetsbeslag/.test(norm(text))}
function scoreActivity(item:any,a:any){const source=tokens(`${item.description} ${item.section_title} ${item.evidence_required} ${item.source_note}`),target=tokens(`${a.title} ${a.task_title} ${a.section_name} ${a.area_name}`);let score=intersectionSize(source,target)*12;const s=norm(`${item.description} ${item.section_title}`),t=norm(`${a.title} ${a.task_title} ${a.section_name}`);if(s&&t&&(t.includes(s)||s.includes(t)))score+=30;if(childSafety(s)){if(/barn|sakerhet|sakerhets|anvandning/.test(t))score+=45;if(/fonster|glas/.test(s)&&/fonster|glas/.test(t))score+=35;if(/kniv|medicin|skap|beslag/.test(s)&&/inredning|kök|kok|sakerhet|slutkontroll/.test(t))score+=25;if(/slutkontroll|sakerhet vid anvandning/.test(t))score+=20}if(norm(item.section_title)&&t.includes(norm(item.section_title)))score+=15;return score}
function suggestions(item:any,activities:any[]){return activities.map(a=>({...a,score:scoreActivity(item,a)})).filter(a=>a.score>0).sort((a,b)=>b.score-a.score||String(a.title).localeCompare(String(b.title),'sv')).slice(0,5)}
function keyFor(kind:ChangeKind,oldRow:any,newRow:any){return kind==='added'?`added:${newRow.id}`:`${kind}:${oldRow.id}`}
function validAction(kind:ChangeKind,action:string):DecisionAction{const allowed:Record<ChangeKind,DecisionAction[]>={added:['defer','link_existing','create_activity'],changed:['defer','update_keep_links','review_links','keep_old'],removed:['defer','keep_historical','unlink_only']};return allowed[kind].includes(action as DecisionAction)?action as DecisionAction:'defer'}

export function registerGoverningVersionDecisionRoutes(app:RouteApp){
 app.get('/api/studio/governing-documents/:id/version-candidates/:versionId/decision-plan',async c=>{
  await ensureSchema(c.env.DB);const documentId=String(c.req.param('id')),versionId=String(c.req.param('versionId'));const candidate=await getCandidate(c.env.DB,documentId,versionId);if(!candidate)return c.json({ok:false,error:'Kandidatversionen hittades inte.'},404);
  const current=await currentItems(c.env.DB,documentId),draft=await draftItems(c.env.DB,versionId);if(!draft.length)return c.json({ok:false,error:'Jämförelseutkast saknas. Granska skillnaderna först.'},409);
  const currentById=new Map(current.map(x=>[String(x.id),x])),draftBySource=new Map(draft.filter(x=>x.source_item_id).map(x=>[String(x.source_item_id),x]));const links=await linksForItems(c.env.DB,current.map(x=>String(x.id))),activities=await projectActivities(c.env.DB,String(candidate.project_id));const changes:any[]=[];
  for(const oldRow of current){const next=draftBySource.get(String(oldRow.id));if(!next){changes.push({kind:'removed' as ChangeKind,oldItem:oldRow,newItem:null});continue}if(changed(oldRow,next))changes.push({kind:'changed' as ChangeKind,oldItem:oldRow,newItem:next})}
  for(const next of draft)if(!next.source_item_id||!currentById.has(String(next.source_item_id)))changes.push({kind:'added' as ChangeKind,oldItem:null,newItem:next});
  const saved=await c.env.DB.prepare('SELECT change_key,action,selected_activity_ids,comment FROM governing_document_version_decisions WHERE version_id=?').bind(versionId).all();const savedMap=new Map((saved.results as any[]).map(x=>[String(x.change_key),x]));
  const decisions=changes.map(change=>{const key=keyFor(change.kind,change.oldItem,change.newItem),existing=change.oldItem?links[String(change.oldItem.id)]||[]:[],matches=change.newItem?suggestions(change.newItem,activities):[];const defaultAction:DecisionAction=change.kind==='changed'?(existing.length?'update_keep_links':'review_links'):change.kind==='removed'?'keep_historical':'defer';const stored=savedMap.get(key);let selectedActivityIds:string[]=[];try{selectedActivityIds=stored?JSON.parse(String(stored.selected_activity_ids||'[]')):[]}catch{}return{key,kind:change.kind,oldItem:change.oldItem,newItem:change.newItem,existingActivities:existing,suggestions:matches,recommendation:change.kind==='added'?(matches.length?`Kontrollera om ”${matches[0].title}” kan återanvändas. Skapa inte en ny aktivitet förrän detta är granskat.`:'Ingen tydlig befintlig aktivitet hittades. Överväg ny aktivitet.'):change.kind==='changed'?(existing.length?'Behåll befintliga aktivitetskopplingar och uppdatera styrpunkten efter godkännande.':'Granska aktivitetskopplingen innan styrpunkten uppdateras.'):'Behåll punkten historiskt. Ingen aktivitet ska raderas automatiskt.',decision:{action:stored?validAction(change.kind,String(stored.action)):defaultAction,selectedActivityIds,comment:stored?String(stored.comment||''):''}}});
  return c.json({ok:true,versionId,summary:{changed:decisions.filter(x=>x.kind==='changed').length,added:decisions.filter(x=>x.kind==='added').length,removed:decisions.filter(x=>x.kind==='removed').length},decisions,safety:{projectChanged:false,activitiesChanged:false,executionPreserved:true}})
 });
 app.put('/api/studio/governing-documents/:id/version-candidates/:versionId/decisions/:changeKey',async c=>{
  await ensureSchema(c.env.DB);const documentId=String(c.req.param('id')),versionId=String(c.req.param('versionId')),changeKey=decodeURIComponent(String(c.req.param('changeKey')));if(!await getCandidate(c.env.DB,documentId,versionId))return c.json({ok:false,error:'Kandidatversionen hittades inte.'},404);const kind=(changeKey.split(':',1)[0]||'') as ChangeKind;if(!['added','changed','removed'].includes(kind))return c.json({ok:false,error:'Ogiltigt ändringsbeslut.'},400);const body=await c.req.json<{action?:string;selectedActivityIds?:string[];comment?:string}>().catch(()=>({}));const action=validAction(kind,clean(body.action)),ids=[...new Set((body.selectedActivityIds||[]).map(clean).filter(Boolean))];await c.env.DB.prepare(`INSERT INTO governing_document_version_decisions(id,version_id,change_key,change_kind,action,selected_activity_ids,comment,updated_at) VALUES(?,?,?,?,?,?,?,datetime('now')) ON CONFLICT(version_id,change_key) DO UPDATE SET action=excluded.action,selected_activity_ids=excluded.selected_activity_ids,comment=excluded.comment,updated_at=datetime('now')`).bind(crypto.randomUUID(),versionId,changeKey,kind,action,JSON.stringify(ids),clean(body.comment)).run();return c.json({ok:true,decision:{changeKey,kind,action,selectedActivityIds:ids},safety:{projectChanged:false,activitiesChanged:false}})
 });
}
