import { registerMasterProjectV2UpgradeRoutes } from './master-project-v2-upgrade-routes';

type RouteApp={post:(path:string,handler:(c:any)=>unknown)=>void};
type Seed={title:string;type:string;lifecycle?:string;surface?:string;applicability?:string;condition?:string;description?:string};

async function ensureSchema(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS master_activity_contexts(master_activity_id TEXT PRIMARY KEY,lifecycle_stage TEXT NOT NULL DEFAULT 'build',surface TEXT NOT NULL DEFAULT 'field',applicability TEXT NOT NULL DEFAULT 'always',condition_text TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(master_activity_id) REFERENCES master_activities(id) ON DELETE CASCADE)`).run()}
function defaults(s:Seed){return{lifecycle:s.lifecycle||(s.type==='administration'?'administration':s.type==='perform'?'build':'control'),surface:s.surface||(s.type==='administration'?'studio':'field'),applicability:s.applicability||'always',condition:s.condition||''}}
async function addToTask(db:D1Database,masterId:string,taskTitle:string,s:Seed){const task=await db.prepare(`SELECT t.id FROM master_tasks t JOIN master_work_sections ws ON ws.id=t.master_work_section_id JOIN master_work_areas wa ON wa.id=ws.master_work_area_id WHERE wa.master_project_id=? AND t.title=? LIMIT 1`).bind(masterId,taskTitle).first<any>();if(!task)return 0;let row=await db.prepare('SELECT id FROM master_activities WHERE master_task_id=? AND title=?').bind(task.id,s.title).first<any>();let id=row?.id?String(row.id):'';let created=0;if(!id){const order=await db.prepare('SELECT COALESCE(MAX(sort_order),0)+10 AS n FROM master_activities WHERE master_task_id=?').bind(task.id).first<any>();id=crypto.randomUUID();await db.prepare('INSERT INTO master_activities(id,master_task_id,title,description,activity_type,required,sort_order) VALUES(?,?,?,?,?,1,?)').bind(id,task.id,s.title,s.description||'',s.type,Number(order?.n||10)).run();created=1}const m=defaults(s);await db.prepare(`INSERT INTO master_activity_contexts(master_activity_id,lifecycle_stage,surface,applicability,condition_text,updated_at) VALUES(?,?,?,?,?,datetime('now')) ON CONFLICT(master_activity_id) DO UPDATE SET lifecycle_stage=excluded.lifecycle_stage,surface=excluded.surface,applicability=excluded.applicability,condition_text=excluded.condition_text,updated_at=datetime('now')`).bind(id,m.lifecycle,m.surface,m.applicability,m.condition).run();return created}
async function extend(db:D1Database,masterId:string){await ensureSchema(db);let created=0;const sewage:Seed[]=[
 {title:'Bevaka avloppstillståndets start- och färdigställandefrister',type:'administration',surface:'studio',description:'Registrera tillståndets beslutsdatum och bevaka sista dag för påbörjande och färdigställande.'},
 {title:'Kontrollera att avloppsanläggningen utförs enligt tillstånd, ansökan och tillverkarens anvisningar',type:'check'},
 {title:'Dokumentera sakkunskap hos den person som utför avloppsinstallationen',type:'administration',surface:'studio',description:'Dokumentera erfarenhet, utbildning eller annan grund som visar att personen har tillräcklig kunskap för arbetet.'},
 {title:'Kontrollera att avloppsanläggningen är tät fram till efterföljande rening',type:'check'},
 {title:'Kontrollera att dag-, dränerings- och annat främmande vatten inte leds till avloppsanläggningen',type:'check'},
 {title:'Kontrollera åtkomlighet för slamtömning och uppställningsplats',type:'check'},
 {title:'Fotografera varje installerad brunn',type:'document',lifecycle:'control',surface:'field'},
 {title:'Fotografera ledningar före återfyllning',type:'document',lifecycle:'control',surface:'field'},
 {title:'Ta översiktsbild av avloppsanläggningens placering',type:'document',lifecycle:'control',surface:'field'},
 {title:'Fotografera infiltrationsgrop innan uppbyggnad',type:'document',lifecycle:'control',surface:'field',applicability:'conditional',condition:'När en ny infiltration eller markbädd anläggs.'},
 {title:'Fotografera lager och spridningsledningar i ny infiltration eller markbädd',type:'document',lifecycle:'control',surface:'field',applicability:'conditional',condition:'När en ny infiltration eller markbädd anläggs.'},
 {title:'Skicka entreprenörsrapport och fotodokumentation till miljö- och byggnämnden',type:'administration',surface:'studio'},
 {title:'Planera och dokumentera drift och skötsel av avloppsanläggningen',type:'administration',lifecycle:'operation',surface:'studio'},
 {title:'Säkerställ slamtömning enligt tillstånd och tillverkarens anvisningar',type:'administration',lifecycle:'operation',surface:'studio'},
 {title:'Bevara avloppstillståndet och överlämna det vid ägarbyte',type:'administration',lifecycle:'operation',surface:'studio'},
 {title:'Kontakta miljömyndigheten före större ändring som kan kräva anmälan',type:'administration',lifecycle:'operation',surface:'studio',applicability:'conditional',condition:'Vid större ingrepp, materialbyte eller annan ändring som kan påverka anläggningens funktion.'}
 ];for(const s of sewage)created+=await addToTask(db,masterId,'Utför enskilt avlopp',s);
 created+=await addToTask(db,masterId,'Kontrollera markförutsättningar',{title:'Avbryt markarbete och kontakta länsstyrelsen om fornlämning påträffas',type:'check',applicability:'conditional',condition:'Om en misstänkt fornlämning påträffas under grävning eller annat markarbete.'});
 await db.prepare("UPDATE master_projects SET version=CASE WHEN version<10 THEN 10 ELSE version END,updated_at=datetime('now') WHERE id=?").bind(masterId).run();return created}

export async function ensureMasterV10(db:D1Database,masterId:string){return extend(db,masterId)}
export function registerMasterProjectV2UpgradeRoutesV10(app:RouteApp){const proxy:RouteApp={post(path,handler){if(path!=='/api/studio/master-projects/upgrade-fritidshus-v2'){app.post(path,handler);return}app.post(path,async c=>{const response:any=await handler(c);if(!response||typeof response.clone!=='function'||!response.ok)return response;const data:any=await response.clone().json().catch(()=>null);if(!data?.id)return response;const created=await extend(c.env.DB,String(data.id));return c.json({...data,version:10,createdActivities:Number(data.createdActivities||0)+created},response.status)})}};registerMasterProjectV2UpgradeRoutes(proxy)}
