import { ensureMasterV24, registerMasterProjectV2UpgradeRoutesV24 } from './master-project-v2-upgrade-routes-v24';

type RouteApp={post:(path:string,handler:(c:any)=>unknown)=>void};

const DESCRIPTIONS:Record<string,string>={
 'Hantera generella byggstartskontroller':'Säkerställ de formella och administrativa förutsättningar som måste vara klara innan det praktiska byggarbetet startar. Kontrollera startbesked, roller, kontrollplan och andra byggstartskrav och registrera den dokumentation som hör till startskedet. Momentet ska inte innehålla kontroller som först kan genomföras efter schakt eller under grundläggningen.',
 'Planera etablering och arbetsplats':'Planera hur byggarbetsplatsen ska fungera innan mark- och byggarbetena tar fart. Ordna tillträde, upplag, avfallshantering och andra tillfälliga funktioner och kontrollera risker, ledningar och eventuella tillstånd. Momentet är klart när arbetsplatsen kan användas säkert utan att hindra de kommande markarbetena.',
 'Kontrollera markförutsättningar':'Gå igenom de underlag som styr markarbetet innan schaktningen påbörjas. Kontrollera geotekniska förutsättningar, radon, marknivåer och andra förhållanden som kan påverka grundläggningen och fånga upp avvikelser innan de byggs in i lösningen. Momentet ska ge ett tydligt beslutsunderlag för schakt och grund.',
 'Genomför extern kontroll av grund':'Samordna den externa eller KA-ledda kontroll som ska ske under grundskedet vid den tidpunkt kontrollplanen anger. Säkerställ att rätt delar är synliga och möjliga att kontrollera och hantera eventuella anmärkningar innan arbetet fortsätter. Dokumentera kontrollen som underlag för projektets verifiering.',
 'Bygg och kontrollera grund':'Bygg grundkonstruktionen enligt konstruktionshandlingarna med rätt mått, nivåer, form, armering och genomföringar. Genomför de kontroller och stoppunkter som krävs innan gjutning eller innan delar byggs in. Momentet är klart när grunden är utförd, kontrollerad och redo för stomstart.',
 'Utför och kontrollera dagvattenlösning':'Utför den projekterade dagvattenlösningen och kontrollera ledningar, brunnar, utlopp och andra dolda delar innan de täcks. Säkerställ att slutliga markfall och avledningsvägar leder vatten bort från byggnaden. Dokumentera sådant som inte längre kan verifieras efter återfyllnad.',
 'Dokumentera bärande konstruktion':'Samla och kontrollera den konstruktionsdokumentation som beskriver byggnadens bärande system innan och under stomarbetet. Säkerställ att dimensioneringsförutsättningar, kritiska anslutningar och relevanta konstruktionshandlingar finns tillgängliga för utförande och kontroll. Momentet är klart när bärverket kan byggas och verifieras mot ett sammanhållet underlag.',
 'Genomför extern stomkontroll':'Samordna den externa eller KA-ledda kontroll som ska göras när den bärande stommen nått rätt skede. Se till att kritiska delar fortfarande är synliga, hantera eventuella anmärkningar och spara kontrollunderlaget innan konstruktionen byggs vidare eller täcks.',
 'Bygg och kontrollera bärande bjälklag':'Bygg bärande bjälklag och golvbärning enligt konstruktionshandlingarna. Kontrollera dimensioner, upplag, avväxlingar och infästningar medan konstruktionen är åtkomlig och dokumentera kritiska delar innan de döljs. Momentet lämnar ett stabilt och verifierat bärverk för fortsatt byggnation.',
 'Bygg bärande tak':'Bygg takets bärande konstruktion enligt konstruktionshandlingarna och kontrollera geometri, upplag, förankring, stabilisering och avväxlingar. Dokumentera kritiska bärande detaljer innan undertak och andra skikt döljer dem. Momentet är klart när takstommen är stabil och kan kläs in.',
 'Färdigställ yttertak':'Färdigställ takets väderskyddande lager med underlag, taktäckning, beslag och tätningar enligt vald lösning. Kontrollera särskilt genomföringar och anslutningar där vatten kan tränga in. Momentet är klart när taket är sammanhängande och vädertätt.',
 'Utför och kontrollera taksäkerhet':'Montera de taksäkerhets- och tillträdesanordningar som projektet kräver och kontrollera deras placering och infästning. Komplettera med snörasskydd där det behövs, särskilt över entréer och gångstråk. Momentet avslutas när taket kan beträdas och användas på ett säkert sätt.',
 'Montera fönster och ytterdörrar':'Kontrollera öppningsmått och montera fönster och ytterdörrar med rätt infästning, rörelsemån och tätning mot stommen. Kontrollera funktion, regn- och lufttäthet samt särskilda krav på utrymningsfönster där de gäller. Dokumentera kritiska anslutningar innan de kläs in.',
 'Färdigställ klimatskal':'Färdigställ byggnadens isolerande och lufttätande skikt och kontrollera anslutningar mellan väggar, tak, fönster, dörrar och genomföringar. Dokumentera kritiska detaljer innan invändiga skikt döljer dem. Momentet är klart när klimatskalet har den avsedda värme-, luft- och fuktsäkerheten.',
 'Dokumentera VVS-provning':'Genomför eller samla resultatet från föreskriven provning av VA- och VVS-installationerna. Säkerställ att provningen avser rätt installation och skede och spara protokollet som underlag inför igenbyggnad och slutbesked.',
 'Kontrollera VA före övertäckning':'Kontrollera VA-installationer medan ledningar, anslutningar och andra kritiska delar fortfarande är synliga. Genomför den inspektion eller egenkontroll som projektet kräver och dokumentera resultatet innan ledningar eller konstruktioner täcks.',
 'Kontrollera VVS-utformning och funktion':'Kontrollera att VVS-installationen är utformad och utförd så att den fungerar säkert i drift. Verifiera bland annat golvbrunnar, blindledningar, temperaturer och andra hygien- eller funktionskrav som gäller projektet. Åtgärda avvikelser innan installationen tas i permanent bruk.',
 'Verifiera elinstallationen':'Verifiera att elarbetet utförs av rätt registrerat företag där det krävs och genomför de kontroller som ska göras innan anläggningen tas i bruk. Samla resultat från isolationsprovning, jordfelsbrytarkontroll och annan föreskriven dokumentation. Momentet är klart när elinstallationen kan styrkas som kontrollerad.',
 'Utför ventilation':'Utför och kontrollera byggnadens ventilationslösning enligt projekterade förutsättningar. Kontrollera luftvägar, ventiler, fläktar och funktion och samla det intyg eller den dokumentation som behövs inför slutbesked. Momentet avslutas när ventilationens avsedda funktion kan verifieras.',
 'Genomför kontroll under invändiga arbeten':'Genomför den kontroll som ska ske medan invändiga konstruktioner fortfarande är öppna och kritiska detaljer går att inspektera. Samordna KA eller annan föreskriven kontroll, hantera eventuella anmärkningar och dokumentera resultatet innan större igenbyggnad fortsätter.',
 'Kontrollera utformning och tillgänglighet':'Kontrollera den färdiga eller nästan färdiga byggnadens utformning mot gällande handlingar. Verifiera tillgänglighet, användbarhet, barnsäkerhet och andra personsäkerhetskrav som gäller projektet och åtgärda avvikelser innan slutkontrollen.',
 'Hantera myndighetskontroller och avslut':'Samordna de myndighets- och KA-kontroller som återstår när byggnaden närmar sig färdigställande. Säkerställ att arbetsplatsbesök görs innan relevanta delar byggs igen, kontrollera överensstämmelse med bygglov och förbered eventuellt slutsamråd. Hantera krav och avvikelser innan slutbesked begärs.',
 'Samla slutdokumentation':'Samla och kontrollera all dokumentation som ska finnas inför slutbesked: signerad kontrollplan, egenkontroller, intyg, foton, myndighetsunderlag och eventuella relationshandlingar. Kontrollera samtidigt att avvikelser från bygglov eller projektering är hanterade och redovisade. Momentet är klart när slutunderlaget är sammanhållet och kan lämnas vidare till KA eller byggnadsnämnden.',
 'Avsluta projektet':'Gör den sista samlade färdigställandekontrollen och säkerställ att kvarstående fel och dokumentationsbrister är hanterade. Avsluta projektet först när byggnaden och dess underlag uppfyller de krav som behövs för slutbesked och fortsatt förvaltning.'
};

function fallbackDescription(title:string,section:string){const action=title.trim().replace(/\.$/,'');return `${action}. Genomför arbetet och tillhörande kontroller i det skede som hör till ${section||'den aktuella delen av byggprocessen'}, och dokumentera sådant som blir dolt eller behöver verifieras senare. Momentet är klart när förutsättningarna för nästa byggskede är uppfyllda.`}

async function ensureTask(db:D1Database,sectionId:string,title:string,description:string,sortOrder:number){let row=await db.prepare('SELECT id FROM master_tasks WHERE master_work_section_id=? AND title=?').bind(sectionId,title).first<any>();if(row?.id){await db.prepare('UPDATE master_tasks SET description=?,sort_order=? WHERE id=?').bind(description,sortOrder,row.id).run();return String(row.id)}const id=crypto.randomUUID();await db.prepare('INSERT INTO master_tasks(id,master_work_section_id,title,description,sort_order) VALUES(?,?,?,?,?)').bind(id,sectionId,title,description,sortOrder).run();return id}
async function moveActivity(db:D1Database,masterId:string,title:string,targetTaskId:string,sortOrder:number){const row=await db.prepare(`SELECT a.id FROM master_activities a JOIN master_tasks t ON t.id=a.master_task_id JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas w ON w.id=s.master_work_area_id WHERE w.master_project_id=? AND lower(trim(a.title))=lower(trim(?)) ORDER BY a.id LIMIT 1`).bind(masterId,title).first<any>();if(row?.id)await db.prepare('UPDATE master_activities SET master_task_id=?,sort_order=? WHERE id=?').bind(targetTaskId,sortOrder,row.id).run()}

async function extend(db:D1Database,masterId:string){
 const rows=await db.prepare(`SELECT t.id,t.title,t.description,s.name section_name FROM master_tasks t JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas w ON w.id=s.master_work_area_id WHERE w.master_project_id=? ORDER BY w.sort_order,s.sort_order,t.sort_order,t.id`).bind(masterId).all();
 for(const row of rows.results as any[]){const title=String(row.title||'').trim(),current=String(row.description||'').trim(),explicit=DESCRIPTIONS[title];const generic=!current||/generell (aktivitet|kontrollpunkt)/i.test(current)||/kopplas till styrdokument/i.test(current);if(explicit||generic)await db.prepare('UPDATE master_tasks SET description=? WHERE id=?').bind(explicit||fallbackDescription(title,String(row.section_name||'')),row.id).run()}

 const groundSection=await db.prepare(`SELECT s.id FROM master_work_sections s JOIN master_work_areas w ON w.id=s.master_work_area_id WHERE w.master_project_id=? AND s.number='20.20' LIMIT 1`).bind(masterId).first<any>();
 if(groundSection?.id){
  const existingOrders=await db.prepare('SELECT COALESCE(MIN(sort_order),10) first_order FROM master_tasks WHERE master_work_section_id=?').bind(groundSection.id).first<any>();const base=Math.max(1,Number(existingOrders?.first_order||10)-2);
  const setout=await ensureTask(db,String(groundSection.id),'Utför finutsättning inför grund','När schakten och underlaget är färdiga sätts grundens exakta läge och höjd ut inför formarbetet. Kontrollera bygglinjer, hörn, diagonaler och referenshöjd så att formen kan byggas på rätt plats. Momentet är klart när formens placering kan tas direkt från utsättningen.',base);
  const location=await ensureTask(db,String(groundSection.id),'Genomför lägeskontroll före gjutning','När gjutformen eller motsvarande grundgeometri är färdig kontrolleras byggnadens verkliga läge mot beviljade handlingar. Beställ och genomför föreskriven lägeskontroll och spara mätintyget innan gjutningen låser konstruktionens position. Eventuella avvikelser ska hanteras före gjutning.',base+1);
  await moveActivity(db,masterId,'Utför utsättning av byggnaden enligt gällande handling',setout,10);
  await moveActivity(db,masterId,'Beställ och genomför lägeskontroll samt spara mätintyg',location,10);
 }
 const finalTask=await db.prepare(`SELECT t.id FROM master_tasks t JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas w ON w.id=s.master_work_area_id WHERE w.master_project_id=? AND lower(trim(t.title))=lower(trim('Samla slutdokumentation')) ORDER BY t.id LIMIT 1`).bind(masterId).first<any>();if(finalTask?.id)await moveActivity(db,masterId,'Hantera avvikelser från bygglov och upprätta relationshandling vid behov',String(finalTask.id),5);

 await db.prepare("UPDATE master_projects SET version=CASE WHEN version<25 THEN 25 ELSE version END,updated_at=datetime('now') WHERE id=?").bind(masterId).run();
}

export async function ensureMasterV25(db:D1Database,masterId:string){const row=await db.prepare('SELECT version FROM master_projects WHERE id=?').bind(masterId).first<any>();if(Number(row?.version||0)<24)await ensureMasterV24(db,masterId);await extend(db,masterId)}
export function registerMasterProjectV2UpgradeRoutesV25(app:RouteApp){const proxy:RouteApp={post(path,handler){if(path!=='/api/studio/master-projects/upgrade-fritidshus-v2'){app.post(path,handler);return}app.post(path,async c=>{const response:any=await handler(c);if(!response||typeof response.clone!=='function'||!response.ok)return response;const data:any=await response.clone().json().catch(()=>null);if(!data?.id)return response;await extend(c.env.DB,String(data.id));return c.json({...data,version:25},response.status)})}};registerMasterProjectV2UpgradeRoutesV24(proxy)}
