import { ensureMasterV21, registerMasterProjectV2UpgradeRoutesV21 } from './master-project-v2-upgrade-routes-v21';

type RouteApp={post:(path:string,handler:(c:any)=>unknown)=>void};
async function ensureContextSchema(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS master_activity_contexts(master_activity_id TEXT PRIMARY KEY,lifecycle_stage TEXT NOT NULL DEFAULT 'build',surface TEXT NOT NULL DEFAULT 'field',applicability TEXT NOT NULL DEFAULT 'always',condition_text TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(master_activity_id) REFERENCES master_activities(id) ON DELETE CASCADE)`).run()}
async function deprecate(db:D1Database,id:string,reason:string){await db.prepare(`INSERT INTO master_activity_contexts(master_activity_id,lifecycle_stage,surface,applicability,condition_text,updated_at) VALUES(?,'build','field','deprecated',?,datetime('now')) ON CONFLICT(master_activity_id) DO UPDATE SET applicability='deprecated',condition_text=excluded.condition_text,updated_at=datetime('now')`).bind(id,reason).run()}
async function mergeTaskModules(db:D1Database,sourceId:string,targetId:string){try{await db.prepare('INSERT OR IGNORE INTO master_task_modules(master_task_id,module_id) SELECT ?,module_id FROM master_task_modules WHERE master_task_id=?').bind(targetId,sourceId).run();await db.prepare('DELETE FROM master_task_modules WHERE master_task_id=?').bind(sourceId).run()}catch{}}
async function mergeTask(db:D1Database,masterId:string){const rows=await db.prepare(`SELECT t.id,t.title FROM master_tasks t JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas w ON w.id=s.master_work_area_id WHERE w.master_project_id=? AND lower(trim(w.name))=lower(trim('Bärande stomme')) AND lower(trim(s.name))=lower(trim('Stomme')) AND lower(trim(t.title)) IN (lower(trim('Utför timmerstomme')),lower(trim('Res bärande stomme'))) ORDER BY t.sort_order,t.id`).bind(masterId).all();const list=rows.results as any[];const target=list.find(r=>String(r.title).trim().toLowerCase()==='res bärande stomme');const sources=list.filter(r=>String(r.title).trim().toLowerCase()==='utför timmerstomme');if(!target)return;for(const source of sources){const acts=await db.prepare('SELECT id,title FROM master_activities WHERE master_task_id=? ORDER BY sort_order,id').bind(source.id).all();for(const a of acts.results as any[]){const dup=await db.prepare(`SELECT a.id FROM master_activities a LEFT JOIN master_activity_contexts ac ON ac.master_activity_id=a.id WHERE a.master_task_id=? AND lower(trim(a.title))=lower(trim(?)) AND COALESCE(ac.applicability,'always')<>'deprecated' ORDER BY a.sort_order,a.id LIMIT 1`).bind(target.id,a.title).first<any>();if(dup)await deprecate(db,String(a.id),'Dublett efter sammanslagning av ”Utför timmerstomme” med ”Res bärande stomme” i Master v22.');await db.prepare('UPDATE master_activities SET master_task_id=? WHERE id=?').bind(target.id,a.id).run()}await mergeTaskModules(db,String(source.id),String(target.id));await db.prepare('DELETE FROM master_tasks WHERE id=? AND NOT EXISTS(SELECT 1 FROM master_activities WHERE master_task_id=?)').bind(source.id,source.id).run()}}
async function deprecateGeneric(db:D1Database,masterId:string){const specific=await db.prepare(`SELECT a.id FROM master_activities a JOIN master_tasks t ON t.id=a.master_task_id JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas w ON w.id=s.master_work_area_id LEFT JOIN master_activity_contexts ac ON ac.master_activity_id=a.id WHERE w.master_project_id=? AND lower(trim(a.title))=lower(trim('Kontrollera färdig timmerstomme mot konstruktionshandling')) AND COALESCE(ac.applicability,'always')<>'deprecated' LIMIT 1`).bind(masterId).first<any>();if(!specific)return;const rows=await db.prepare(`SELECT a.id FROM master_activities a JOIN master_tasks t ON t.id=a.master_task_id JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas w ON w.id=s.master_work_area_id LEFT JOIN master_activity_contexts ac ON ac.master_activity_id=a.id WHERE w.master_project_id=? AND lower(trim(a.title))=lower(trim('Kontrollera färdig timmerstomme')) AND COALESCE(ac.applicability,'always')<>'deprecated'`).bind(masterId).all();for(const row of rows.results as any[])await deprecate(db,String(row.id),'Ersatt av specifik kontroll mot konstruktionshandling i Master v22.')}
async function extend(db:D1Database,masterId:string){await ensureContextSchema(db);await mergeTask(db,masterId);await deprecateGeneric(db,masterId);await db.prepare("UPDATE master_projects SET version=CASE WHEN version<22 THEN 22 ELSE version END,updated_at=datetime('now') WHERE id=?").bind(masterId).run()}
export async function ensureMasterV22(db:D1Database,masterId:string){const row=await db.prepare('SELECT version FROM master_projects WHERE id=?').bind(masterId).first<any>();if(Number(row?.version||0)<21)await ensureMasterV21(db,masterId);await extend(db,masterId)}
export function registerMasterProjectV2UpgradeRoutesV22(app:RouteApp){const proxy:RouteApp={post(path,handler){if(path!=='/api/studio/master-projects/upgrade-fritidshus-v2'){app.post(path,handler);return}app.post(path,async c=>{const response:any=await handler(c);if(!response||typeof response.clone!=='function'||!response.ok)return response;const data:any=await response.clone().json().catch(()=>null);if(!data?.id)return response;await extend(c.env.DB,String(data.id));return c.json({...data,version:22},response.status)})}};registerMasterProjectV2UpgradeRoutesV21(proxy)}
