import { ensureMasterV18, registerMasterProjectV2UpgradeRoutesV18 } from './master-project-v2-upgrade-routes-v18';

type RouteApp={post:(path:string,handler:(c:any)=>unknown)=>void};

async function ensureContextSchema(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS master_activity_contexts(master_activity_id TEXT PRIMARY KEY,lifecycle_stage TEXT NOT NULL DEFAULT 'build',surface TEXT NOT NULL DEFAULT 'field',applicability TEXT NOT NULL DEFAULT 'always',condition_text TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(master_activity_id) REFERENCES master_activities(id) ON DELETE CASCADE)`).run()}
async function deprecate(db:D1Database,id:string,reason:string){await db.prepare(`INSERT INTO master_activity_contexts(master_activity_id,lifecycle_stage,surface,applicability,condition_text,updated_at) VALUES(?,'build','field','deprecated',?,datetime('now')) ON CONFLICT(master_activity_id) DO UPDATE SET applicability='deprecated',condition_text=excluded.condition_text,updated_at=datetime('now')`).bind(id,reason).run()}

async function mergeDuplicateMasterTasks(db:D1Database,masterId:string,sectionName:string,title:string){const rows=await db.prepare(`SELECT t.id FROM master_tasks t JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas a ON a.id=s.master_work_area_id WHERE a.master_project_id=? AND lower(trim(s.name))=lower(trim(?)) AND lower(trim(t.title))=lower(trim(?)) ORDER BY t.sort_order,t.id`).bind(masterId,sectionName,title).all();const tasks=rows.results as any[];if(tasks.length<2)return;const keeper=tasks[0];for(const source of tasks.slice(1)){const activities=await db.prepare('SELECT id,title FROM master_activities WHERE master_task_id=? ORDER BY sort_order,id').bind(source.id).all();for(const activity of activities.results as any[]){const duplicate=await db.prepare('SELECT id FROM master_activities WHERE master_task_id=? AND lower(trim(title))=lower(trim(?)) ORDER BY sort_order,id LIMIT 1').bind(keeper.id,activity.title).first<any>();if(duplicate)await deprecate(db,String(activity.id),`Dublett efter sammanslagning av dubbla Master-momentet ”${title}” i v19.`);await db.prepare('UPDATE master_activities SET master_task_id=? WHERE id=?').bind(keeper.id,activity.id).run()}try{await db.prepare('INSERT OR IGNORE INTO master_task_modules(master_task_id,module_id) SELECT ?,module_id FROM master_task_modules WHERE master_task_id=?').bind(keeper.id,source.id).run();await db.prepare('DELETE FROM master_task_modules WHERE master_task_id=?').bind(source.id).run()}catch{}await db.prepare('DELETE FROM master_tasks WHERE id=? AND NOT EXISTS(SELECT 1 FROM master_activities WHERE master_task_id=?)').bind(source.id,source.id).run()}}

async function deprecateAllButPreferred(db:D1Database,masterId:string,oldTitle:string,preferredTitle:string){const preferred=await db.prepare(`SELECT a.id FROM master_activities a JOIN master_tasks t ON t.id=a.master_task_id JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas w ON w.id=s.master_work_area_id WHERE w.master_project_id=? AND lower(trim(a.title))=lower(trim(?)) ORDER BY a.sort_order,a.id LIMIT 1`).bind(masterId,preferredTitle).first<any>();if(!preferred)return;const old=await db.prepare(`SELECT a.id FROM master_activities a JOIN master_tasks t ON t.id=a.master_task_id JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas w ON w.id=s.master_work_area_id LEFT JOIN master_activity_contexts ac ON ac.master_activity_id=a.id WHERE w.master_project_id=? AND lower(trim(a.title))=lower(trim(?)) AND COALESCE(ac.applicability,'always')<>'deprecated'`).bind(masterId,oldTitle).all();for(const row of old.results as any[])await deprecate(db,String(row.id),`Ersatt av ”${preferredTitle}” i Master v19.`)}

async function extend(db:D1Database,masterId:string){await ensureContextSchema(db);await mergeDuplicateMasterTasks(db,masterId,'Stomme','Bygg och kontrollera bärande bjälklag');await deprecateAllButPreferred(db,masterId,'Kontrollera färdig timmerstomme','Kontrollera färdig timmerstomme mot konstruktionshandling');await db.prepare("UPDATE master_projects SET version=CASE WHEN version<19 THEN 19 ELSE version END,updated_at=datetime('now') WHERE id=?").bind(masterId).run()}

export async function ensureMasterV19(db:D1Database,masterId:string){const previous=await ensureMasterV18(db,masterId);await extend(db,masterId);return previous}

export function registerMasterProjectV2UpgradeRoutesV19(app:RouteApp){const proxy:RouteApp={post(path,handler){if(path!=='/api/studio/master-projects/upgrade-fritidshus-v2'){app.post(path,handler);return;}app.post(path,async c=>{const response:any=await handler(c);if(!response||typeof response.clone!=='function'||!response.ok)return response;const data:any=await response.clone().json().catch(()=>null);if(!data?.id)return response;await extend(c.env.DB,String(data.id));return c.json({...data,version:19},response.status)})}};registerMasterProjectV2UpgradeRoutesV18(proxy)}
