function parseObject(raw:unknown){try{const value=JSON.parse(String(raw||'{}'));return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,any>:{} }catch{return{}}}
function graphRefs(graph:any){const refs=new Set<string>(),dependencies=parseObject(graph?.dependencies_json),positions=parseObject(graph?.positions_json),routes=parseObject(graph?.routes_json);for(const[child,parents]of Object.entries(dependencies)){refs.add(child);for(const parent of Array.isArray(parents)?parents:[])refs.add(String(parent))}for(const id of Object.keys(positions))refs.add(id);for(const key of Object.keys(routes)){const[a,b]=key.split('->');if(a)refs.add(a);if(b)refs.add(b)}return refs}
function replaceGraphNode(graph:any,oldId:string,newId:string){const dependencies=parseObject(graph?.dependencies_json),positions=parseObject(graph?.positions_json),routes=parseObject(graph?.routes_json);const nextDependencies:Record<string,string[]>={};for(const[child,parents]of Object.entries(dependencies)){const mappedChild=child===oldId?newId:child;const mappedParents=(Array.isArray(parents)?parents:[]).map(x=>String(x)===oldId?newId:String(x)).filter(x=>x!==mappedChild);nextDependencies[mappedChild]=[...new Set([...(nextDependencies[mappedChild]||[]),...mappedParents])]};const nextPositions:Record<string,unknown>={...positions};if(nextPositions[oldId]!==undefined&&nextPositions[newId]===undefined)nextPositions[newId]=nextPositions[oldId];delete nextPositions[oldId];const nextRoutes:Record<string,unknown>={};for(const[key,value]of Object.entries(routes)){const[source,target]=key.split('->');const s=source===oldId?newId:source,t=target===oldId?newId:target;if(s&&t&&s!==t)nextRoutes[`${s}->${t}`]=value}return{dependencies:nextDependencies,positions:nextPositions,routes:nextRoutes}}
function removeGraphNode(graph:any,removeId:string){const dependencies=parseObject(graph?.dependencies_json),positions=parseObject(graph?.positions_json),routes=parseObject(graph?.routes_json);const parents=(Array.isArray(dependencies[removeId])?dependencies[removeId]:[]).map((x:any)=>String(x));const nextDependencies:Record<string,string[]>={};for(const[child,rawParents]of Object.entries(dependencies)){if(child===removeId)continue;const list=(Array.isArray(rawParents)?rawParents:[]).flatMap(x=>String(x)===removeId?parents:[String(x)]).filter(x=>x!==child);nextDependencies[child]=[...new Set(list)]}const nextPositions:Record<string,unknown>={...positions};delete nextPositions[removeId];const nextRoutes:Record<string,unknown>={};for(const[key,value]of Object.entries(routes)){const[source,target]=key.split('->');if(source===removeId||target===removeId)continue;nextRoutes[key]=value}return{dependencies:nextDependencies,positions:nextPositions,routes:nextRoutes}}

export async function normalizeStableMasterBase(db:D1Database,masterProjectId:string){
 const master=await db.prepare('SELECT id FROM master_projects WHERE id=?').bind(masterProjectId).first<any>();if(!master)return{changed:false,repairs:[] as string[]};
 let graph=await db.prepare('SELECT dependencies_json,positions_json,routes_json FROM master_graph_states WHERE master_project_id=?').bind(masterProjectId).first<any>();
 const repairs:string[]=[];let graphChanged=false;
 const ventilationTasks=(await db.prepare(`SELECT t.id,t.master_work_section_id,t.sort_order FROM master_tasks t JOIN master_task_modules mtm ON mtm.master_task_id=t.id JOIN master_modules mm ON mm.id=mtm.module_id WHERE mm.master_project_id=? AND mm.group_code='ventilation' ORDER BY t.sort_order,t.id`).bind(masterProjectId).all()).results as any[];
 let ventilationBase=await db.prepare(`SELECT t.id,t.master_work_section_id FROM master_tasks t JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas a ON a.id=s.master_work_area_id LEFT JOIN master_task_modules mtm ON mtm.master_task_id=t.id WHERE a.master_project_id=? AND lower(trim(t.title))=lower(trim('Utför ventilation')) AND mtm.master_task_id IS NULL LIMIT 1`).bind(masterProjectId).first<any>();
 if(!ventilationBase){const preferredSection=await db.prepare(`SELECT s.id FROM master_work_sections s JOIN master_work_areas a ON a.id=s.master_work_area_id WHERE a.master_project_id=? AND lower(trim(s.name))=lower(trim('Ventilation')) LIMIT 1`).bind(masterProjectId).first<any>();const fallback=ventilationTasks[0];const sectionId=String(preferredSection?.id||fallback?.master_work_section_id||'');if(sectionId){const id=crypto.randomUUID();await db.prepare(`INSERT INTO master_tasks(id,master_work_section_id,title,description,sort_order) VALUES(?,?,?,?,?)`).bind(id,sectionId,'Utför ventilation','Gemensamt basmoment för vald ventilationsprincip.',Number(fallback?.sort_order||10)).run();const activities=[['Montera vald ventilationslösning','perform'],['Funktionskontrollera ventilation','measurement'],['Samla erforderligt ventilationsunderlag','document']];for(let i=0;i<activities.length;i++)await db.prepare(`INSERT INTO master_activities(id,master_task_id,title,description,activity_type,required,sort_order) VALUES(?,?,?,?,?,1,?)`).bind(crypto.randomUUID(),id,activities[i][0],'',activities[i][1],(i+1)*10).run();ventilationBase={id,master_work_section_id:sectionId};repairs.push('Skapade stabilt basmoment: Utför ventilation.')}}
 if(ventilationBase){for(const activity of [['Montera vald ventilationslösning','perform'],['Funktionskontrollera ventilation','measurement'],['Samla erforderligt ventilationsunderlag','document']] as const){const exists=await db.prepare('SELECT id FROM master_activities WHERE master_task_id=? AND lower(trim(title))=lower(trim(?)) LIMIT 1').bind(String(ventilationBase.id),activity[0]).first<any>();if(!exists){const order=await db.prepare('SELECT COALESCE(MAX(sort_order),0)+10 n FROM master_activities WHERE master_task_id=?').bind(String(ventilationBase.id)).first<any>();await db.prepare(`INSERT INTO master_activities(id,master_task_id,title,description,activity_type,required,sort_order) VALUES(?,?,?,?,?,1,?)`).bind(crypto.randomUUID(),String(ventilationBase.id),activity[0],'',activity[1],Number(order?.n||10)).run();repairs.push(`Kompletterade Utför ventilation med aktiviteten: ${activity[0]}.`)}}
 if(graph&&ventilationBase&&ventilationTasks.length){const refs=graphRefs(graph),anchor=ventilationTasks.find(t=>refs.has(String(t.id)));if(anchor&&String(anchor.id)!==String(ventilationBase.id)){const mapped=replaceGraphNode(graph,String(anchor.id),String(ventilationBase.id));graph={...graph,dependencies_json:JSON.stringify(mapped.dependencies),positions_json:JSON.stringify(mapped.positions),routes_json:JSON.stringify(mapped.routes)};graphChanged=true;repairs.push('Flyttade ventilationsankaret i Master-grafen till basmomentet Utför ventilation.')}}
 const conditional=await db.prepare(`SELECT t.id FROM master_tasks t JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas a ON a.id=s.master_work_area_id LEFT JOIN master_task_modules mtm ON mtm.master_task_id=t.id WHERE a.master_project_id=? AND mtm.master_task_id IS NULL AND lower(trim(t.title))=lower(trim('Gjut grundsulor och bygg grundmurar')) LIMIT 1`).bind(masterProjectId).first<any>();
 if(conditional){const id=String(conditional.id);if(graph){const mapped=removeGraphNode(graph,id);graph={...graph,dependencies_json:JSON.stringify(mapped.dependencies),positions_json:JSON.stringify(mapped.positions),routes_json:JSON.stringify(mapped.routes)};graphChanged=true}const activityIds=(await db.prepare('SELECT id FROM master_activities WHERE master_task_id=?').bind(id).all()).results as any[];for(const activity of activityIds)await db.prepare("DELETE FROM project_master_node_links WHERE entity_type='activity' AND master_entity_id=?").bind(String(activity.id)).run();await db.prepare("DELETE FROM project_master_node_links WHERE entity_type='task' AND master_entity_id=?").bind(id).run();await db.prepare('DELETE FROM master_activities WHERE master_task_id=?').bind(id).run();await db.prepare('DELETE FROM master_task_modules WHERE master_task_id=?').bind(id).run();await db.prepare('DELETE FROM master_tasks WHERE id=?').bind(id).run();repairs.push('Tog bort byggmetodsspecifika basmomentet Gjut grundsulor och bygg grundmurar och bryggade grafen förbi det.')}
 if(graphChanged&&graph)await db.prepare(`UPDATE master_graph_states SET dependencies_json=?,positions_json=?,routes_json=?,updated_at=datetime('now') WHERE master_project_id=?`).bind(graph.dependencies_json,graph.positions_json,graph.routes_json,masterProjectId).run();
 if(repairs.length)await db.prepare('UPDATE master_projects SET version=version+1,updated_at=datetime(\'now\') WHERE id=?').bind(masterProjectId).run().catch(async()=>{await db.prepare('UPDATE master_projects SET version=version+1 WHERE id=?').bind(masterProjectId).run()});
 return{changed:repairs.length>0,repairs};
}

export async function normalizeStableMasterBaseMiddleware(c:any,next:any){
 const path=String(c.req.path||'');const validation=path.match(/^\/api\/studio\/master-projects\/([^/]+)\/module-validation$/),create=path.match(/^\/api\/studio\/master-projects\/([^/]+)\/create-project$/),sync=path.match(/^\/api\/studio\/master-projects\/([^/]+)\/sync-from-project\/[^/]+$/);
 try{if(validation||create)await normalizeStableMasterBase(c.env.DB,decodeURIComponent(String((validation||create)![1])))}catch(error){console.error('Stable Master normalization before request failed',error)}
 await next();
 try{if(sync&&c.res?.ok)await normalizeStableMasterBase(c.env.DB,decodeURIComponent(String(sync[1])))}catch(error){console.error('Stable Master normalization after sync failed',error)}
}
