import { ensureMasterV19, registerMasterProjectV2UpgradeRoutesV19 } from './master-project-v2-upgrade-routes-v19';

type RouteApp={post:(path:string,handler:(c:any)=>unknown)=>void};

async function ensureContextSchema(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS master_activity_contexts(master_activity_id TEXT PRIMARY KEY,lifecycle_stage TEXT NOT NULL DEFAULT 'build',surface TEXT NOT NULL DEFAULT 'field',applicability TEXT NOT NULL DEFAULT 'always',condition_text TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(master_activity_id) REFERENCES master_activities(id) ON DELETE CASCADE)`).run()}
async function deprecate(db:D1Database,id:string,reason:string){await db.prepare(`INSERT INTO master_activity_contexts(master_activity_id,lifecycle_stage,surface,applicability,condition_text,updated_at) VALUES(?,'build','field','deprecated',?,datetime('now')) ON CONFLICT(master_activity_id) DO UPDATE SET applicability='deprecated',condition_text=excluded.condition_text,updated_at=datetime('now')`).bind(id,reason).run()}

async function mergeAllDuplicateMasterTasks(db:D1Database,masterId:string){
 const groups=await db.prepare(`SELECT t.master_work_section_id,lower(trim(t.title)) title_key,COUNT(*) n FROM master_tasks t JOIN master_work_sections s ON s.id=t.master_work_section_id JOIN master_work_areas a ON a.id=s.master_work_area_id WHERE a.master_project_id=? GROUP BY t.master_work_section_id,lower(trim(t.title)) HAVING COUNT(*)>1`).bind(masterId).all();
 for(const group of groups.results as any[]){const tasks=await db.prepare('SELECT id,title,sort_order FROM master_tasks WHERE master_work_section_id=? AND lower(trim(title))=? ORDER BY sort_order,id').bind(group.master_work_section_id,group.title_key).all();const list=tasks.results as any[];if(list.length<2)continue;const keeper=list[0];for(const source of list.slice(1)){const activities=await db.prepare('SELECT id,title,sort_order FROM master_activities WHERE master_task_id=? ORDER BY sort_order,id').bind(source.id).all();for(const activity of activities.results as any[]){const duplicate=await db.prepare(`SELECT a.id FROM master_activities a LEFT JOIN master_activity_contexts ac ON ac.master_activity_id=a.id WHERE a.master_task_id=? AND lower(trim(a.title))=lower(trim(?)) AND COALESCE(ac.applicability,'always')<>'deprecated' ORDER BY a.sort_order,a.id LIMIT 1`).bind(keeper.id,activity.title).first<any>();if(duplicate)await deprecate(db,String(activity.id),`Dublett efter sammanslagning av dubbla Master-momentet ”${keeper.title}” i v20.`);await db.prepare('UPDATE master_activities SET master_task_id=? WHERE id=?').bind(keeper.id,activity.id).run()}try{await db.prepare('INSERT OR IGNORE INTO master_task_modules(master_task_id,module_id) SELECT ?,module_id FROM master_task_modules WHERE master_task_id=?').bind(keeper.id,source.id).run();await db.prepare('DELETE FROM master_task_modules WHERE master_task_id=?').bind(source.id).run()}catch{}await db.prepare('DELETE FROM master_tasks WHERE id=? AND NOT EXISTS(SELECT 1 FROM master_activities WHERE master_task_id=?)').bind(source.id,source.id).run()}}
}

async function extend(db:D1Database,masterId:string){await ensureContextSchema(db);await mergeAllDuplicateMasterTasks(db,masterId);await db.prepare("UPDATE master_projects SET version=CASE WHEN version<20 THEN 20 ELSE version END,updated_at=datetime('now') WHERE id=?").bind(masterId).run()}

export async function ensureMasterV20(db:D1Database,masterId:string){const previous=await ensureMasterV19(db,masterId);await extend(db,masterId);return previous}

export function registerMasterProjectV2UpgradeRoutesV20(app:RouteApp){const proxy:RouteApp={post(path,handler){if(path!=='/api/studio/master-projects/upgrade-fritidshus-v2'){app.post(path,handler);return;}app.post(path,async c=>{const response:any=await handler(c);if(!response||typeof response.clone!=='function'||!response.ok)return response;const data:any=await response.clone().json().catch(()=>null);if(!data?.id)return response;await extend(c.env.DB,String(data.id));return c.json({...data,version:20},response.status)})}};registerMasterProjectV2UpgradeRoutesV19(proxy)}
