type RouteApp={get:(path:string,handler:(c:any)=>unknown)=>void;post:(path:string,handler:(c:any)=>unknown)=>void};
type TableInfo={name:string;pk:number};
type ForeignKey={table:string;from:string;to:string};
type Backup={format:string;version:number;exportedAt:string;sourceProjectId:string;entities:Record<string,Record<string,unknown>[]>;files:Array<{key:string;size:number;etag?:string;contentType?:string}>};
const FORMAT='byggplan-portable-backup';
function ident(v:string){if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(v))throw new Error(`Ogiltigt databasnamn: ${v}`);return `"${v}"`}
async function tables(db:D1Database){const r=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();return (r.results as any[]).map(x=>String(x.name));}
async function info(db:D1Database,table:string){const r=await db.prepare(`PRAGMA table_info(${ident(table)})`).all();return (r.results as any[]).map(x=>({name:String(x.name),pk:Number(x.pk||0)})) as TableInfo[];}
async function fks(db:D1Database,table:string){const r=await db.prepare(`PRAGMA foreign_key_list(${ident(table)})`).all();return (r.results as any[]).map(x=>({table:String(x.table),from:String(x.from),to:String(x.to||'id')})) as ForeignKey[];}
function values(rows:Record<string,unknown>[],column:string){return Array.from(new Set(rows.map(r=>r[column]).filter(v=>v!==null&&v!==undefined)));}
async function selectIn(db:D1Database,table:string,column:string,vals:unknown[]){if(!vals.length)return[];const out:Record<string,unknown>[]=[];for(let i=0;i<vals.length;i+=75){const batch=vals.slice(i,i+75);const r=await db.prepare(`SELECT * FROM ${ident(table)} WHERE ${ident(column)} IN (${batch.map(()=>'?').join(',')})`).bind(...batch).all();out.push(...(r.results as Record<string,unknown>[]));}return out;}
function mergeRows(target:Record<string,unknown>[],rows:Record<string,unknown>[],pk:string){const seen=new Set(target.map(r=>String(r[pk])));let changed=false;for(const row of rows){const key=String(row[pk]);if(!seen.has(key)){target.push(row);seen.add(key);changed=true;}}return changed;}
async function collectProject(db:D1Database,projectId:string){const names=await tables(db);const infos=new Map<string,TableInfo[]>(),links=new Map<string,ForeignKey[]>();for(const t of names){infos.set(t,await info(db,t));links.set(t,await fks(db,t));}
 const entities:Record<string,Record<string,unknown>[]>=Object.fromEntries(names.map(t=>[t,[]]));
 if(names.includes('projects')){const r=await db.prepare('SELECT * FROM projects WHERE id=?').bind(projectId).all();entities.projects=r.results as Record<string,unknown>[];if(!entities.projects.length)throw new Error('Projektet hittades inte.');}
 for(const t of names){if(t==='projects')continue;const cols=infos.get(t)||[];if(cols.some(c=>c.name==='project_id'))entities[t]=await selectIn(db,t,'project_id',[projectId]);}
 let changed=true;for(let pass=0;changed&&pass<20;pass++){changed=false;for(const t of names){const cols=infos.get(t)||[];const pk=cols.find(c=>c.pk===1)?.name||cols.find(c=>c.name==='id')?.name;if(!pk)continue;for(const fk of links.get(t)||[]){const parents=entities[fk.table]||[];if(!parents.length)continue;const vals=values(parents,fk.to);if(!vals.length)continue;const rows=await selectIn(db,t,fk.from,vals);if(mergeRows(entities[t],rows,pk))changed=true;}}}
 for(const t of Object.keys(entities))if(!entities[t].length)delete entities[t];return{entities,infos,links};}
async function listFiles(bucket:R2Bucket,projectId:string){const prefix=`projects/${projectId}/`;const out:Array<{key:string;size:number;etag?:string;contentType?:string}>=[];let cursor:string|undefined;do{const page=await bucket.list({prefix,cursor,limit:1000});for(const o of page.objects)out.push({key:o.key,size:o.size,etag:o.etag,contentType:(o as any).httpMetadata?.contentType});cursor=page.truncated?page.cursor:undefined;}while(cursor);return out;}
function topo(names:string[],links:Map<string,ForeignKey[]>){const set=new Set(names),done:string[]=[],left=new Set(names);while(left.size){let progress=false;for(const t of [...left]){const parents=(links.get(t)||[]).map(f=>f.table).filter(p=>set.has(p)&&p!==t);if(parents.every(p=>done.includes(p))){done.push(t);left.delete(t);progress=true;}}if(!progress){done.push(...left);break;}}return done;}
async function deleteCurrentProjectData(db:D1Database,projectId:string){const collected=await collectProject(db,projectId);const order=topo(Object.keys(collected.entities),collected.links).reverse();for(const t of order){if(t==='projects')continue;const rows=collected.entities[t]||[];const cols=collected.infos.get(t)||[];const pk=cols.find(c=>c.pk===1)?.name||cols.find(c=>c.name==='id')?.name;if(!pk||!rows.length)continue;const ids=values(rows,pk);for(let i=0;i<ids.length;i+=75){const b=ids.slice(i,i+75);await db.prepare(`DELETE FROM ${ident(t)} WHERE ${ident(pk)} IN (${b.map(()=>'?').join(',')})`).bind(...b).run();}}}
function remapValue(value:unknown,sourceProjectId:string,projectId:string){if(typeof value!=='string'||sourceProjectId===projectId)return value;const from=`projects/${sourceProjectId}/`;return value.startsWith(from)?`projects/${projectId}/${value.slice(from.length)}`:value;}
async function insertEntities(db:D1Database,entities:Record<string,Record<string,unknown>[]>,sourceProjectId:string,projectId:string){const names=await tables(db);const nameSet=new Set(names);const links=new Map<string,ForeignKey[]>();for(const t of names)links.set(t,await fks(db,t));const selected=Object.keys(entities).filter(t=>nameSet.has(t));const order=topo(selected,links);for(const t of order){const cols=new Set((await info(db,t)).map(c=>c.name));for(const original of entities[t]||[]){const row:Record<string,unknown>={};for(const[k,v]of Object.entries(original))row[k]=remapValue(v,sourceProjectId,projectId);if('project_id'in row)row.project_id=projectId;if(t==='projects'&&'id'in row)row.id=projectId;const keys=Object.keys(row).filter(k=>cols.has(k));if(!keys.length)continue;const sql=`INSERT OR REPLACE INTO ${ident(t)}(${keys.map(ident).join(',')}) VALUES(${keys.map(()=>'?').join(',')})`;await db.prepare(sql).bind(...keys.map(k=>row[k]??null)).run();}}}
export function registerProjectBackupRoutes(app:RouteApp){
 app.get('/api/studio/projects/:projectId/backup-manifest',async c=>{try{const projectId=c.req.param('projectId');const {entities}=await collectProject(c.env.DB,projectId);const files=c.env.FILES?await listFiles(c.env.FILES,projectId):[];const backup:Backup={format:FORMAT,version:1,exportedAt:new Date().toISOString(),sourceProjectId:projectId,entities,files};return c.json({ok:true,backup});}catch(e){return c.json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
 app.get('/api/studio/projects/:projectId/backup-file',async c=>{const projectId=c.req.param('projectId');const key=String(c.req.query('key')||'');if(!key.startsWith(`projects/${projectId}/`))return c.json({ok:false,error:'Ogiltig filsökväg.'},400);const o=await c.env.FILES.get(key);if(!o)return c.json({ok:false,error:'Backupfilen saknas i lagringen.'},404);const h=new Headers();o.writeHttpMetadata(h);h.set('Content-Type',h.get('Content-Type')||'application/octet-stream');h.set('Cache-Control','no-store');return new Response(o.body,{headers:h});});
 app.post('/api/studio/projects/:projectId/restore-data',async c=>{const projectId=c.req.param('projectId');const body=await c.req.json<{backup?:Backup}>().catch(()=>({}));const backup=body.backup;if(!backup||backup.format!==FORMAT||backup.version!==1||!backup.entities)return c.json({ok:false,error:'Filen är inte en giltig ByggPlan-backup.'},400);try{const existing=await c.env.DB.prepare('SELECT id FROM projects WHERE id=?').bind(projectId).first();if(existing)await deleteCurrentProjectData(c.env.DB,projectId);await insertEntities(c.env.DB,backup.entities,backup.sourceProjectId,projectId);return c.json({ok:true,projectId,tables:Object.keys(backup.entities).length});}catch(e){console.error('restore failed',e);return c.json({ok:false,error:`Återställningen misslyckades: ${e instanceof Error?e.message:String(e)}`},500)}});
 app.post('/api/studio/projects/:projectId/restore-file',async c=>{const projectId=c.req.param('projectId');let form:FormData;try{form=await c.req.raw.formData()}catch{return c.json({ok:false,error:'Kunde inte läsa backupfilen.'},400)}const key=String(form.get('key')||'');const file=form.get('file');if(!key.startsWith(`projects/${projectId}/`))return c.json({ok:false,error:'Ogiltig filsökväg.'},400);if(!file||typeof(file as any).stream!=='function')return c.json({ok:false,error:'Fil saknas.'},400);await c.env.FILES.put(key,(file as any).stream(),{httpMetadata:{contentType:String((file as any).type||'application/octet-stream')}});return c.json({ok:true,key});});
 }
