type RouteApp={post:(path:string,handler:(c:any)=>unknown)=>void};

async function tableExists(db:D1Database,name:string){return Boolean(await db.prepare("SELECT 1 ok FROM sqlite_master WHERE type='table' AND name=?").bind(name).first())}
async function ensureContextSchema(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS activity_contexts(activity_id TEXT PRIMARY KEY,lifecycle_stage TEXT NOT NULL DEFAULT 'build',surface TEXT NOT NULL DEFAULT 'field',applicability TEXT NOT NULL DEFAULT 'always',condition_text TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(activity_id) REFERENCES activities(id) ON DELETE CASCADE)`).run()}
async function deprecate(db:D1Database,id:string,reason:string){await db.prepare(`INSERT INTO activity_contexts(activity_id,lifecycle_stage,surface,applicability,condition_text,updated_at) VALUES(?,'design','studio','deprecated',?,datetime('now')) ON CONFLICT(activity_id) DO UPDATE SET lifecycle_stage='design',surface='studio',applicability='deprecated',condition_text=excluded.condition_text,updated_at=datetime('now')`).bind(id,reason).run()}
async function moveGoverningLinks(db:D1Database,fromId:string,toId:string){if(!await tableExists(db,'governing_item_activity_links'))return;const rows=await db.prepare('SELECT * FROM governing_item_activity_links WHERE activity_id=?').bind(fromId).all();const cols=await db.prepare('PRAGMA table_info(governing_item_activity_links)').all();const names=new Set((cols.results as any[]).map(r=>String(r.name)));for(const row of rows.results as any[]){if(await db.prepare('SELECT 1 ok FROM governing_item_activity_links WHERE governing_item_id=? AND activity_id=? LIMIT 1').bind(row.governing_item_id,toId).first())continue;const fields=['id','governing_item_id','activity_id','link_type','mapping_source','confidence','mapping_comment','created_at','confirmed_at'].filter(x=>names.has(x));const values=fields.map(f=>f==='id'?crypto.randomUUID():f==='activity_id'?toId:row[f]??null);await db.prepare(`INSERT INTO governing_item_activity_links(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')})`).bind(...values).run()}}

export async function cleanupProjectStructureV24(db:D1Database,projectId:string){
 await ensureContextSchema(db);
 const rows=await db.prepare(`SELECT a.id,a.title,t.title task_title,s.name section_name,w.name area_name FROM activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections s ON s.id=t.work_section_id JOIN work_areas w ON w.id=s.work_area_id LEFT JOIN activity_contexts ac ON ac.activity_id=a.id WHERE w.project_id=? AND lower(trim(w.name))=lower(trim('Säkerhet och färdigställande')) AND lower(trim(s.name))=lower(trim('Säkerhet')) AND COALESCE(ac.applicability,'always')<>'deprecated' ORDER BY t.sort_order,a.sort_order,a.id`).bind(projectId).all();
 const list=rows.results as any[];
 const target=list.find(r=>String(r.title).trim().toLowerCase()==='kontrollera fall-, glas-, barn- och tippsäkerhet där det är tillämpligt');
 const duplicate=list.find(r=>String(r.title).trim().toLowerCase()==='kontrollera barnsäkerhet och säkerhet vid användning');
 if(!target||!duplicate||String(target.id)===String(duplicate.id))return{retiredActivities:0,targetFound:Boolean(target),duplicateFound:Boolean(duplicate)};
 await moveGoverningLinks(db,String(duplicate.id),String(target.id));
 await deprecate(db,String(duplicate.id),'Överlappande aktivitet. Ersatt av "Kontrollera fall-, glas-, barn- och tippsäkerhet där det är tillämpligt" i strukturstädning v24.');
 if(await tableExists(db,'project_master_snapshots'))await db.prepare('UPDATE project_master_snapshots SET master_project_version=CASE WHEN master_project_version<24 THEN 24 ELSE master_project_version END WHERE project_id=?').bind(projectId).run();
 return{retiredActivities:1,targetFound:true,duplicateFound:true,targetActivityId:String(target.id),retiredActivityId:String(duplicate.id)};
}

export function registerProjectStructureCleanupV24Routes(app:RouteApp){app.post('/api/studio/projects/:projectId/structure-consolidate-v24',async c=>{const projectId=c.req.param('projectId');if(!await c.env.DB.prepare('SELECT id FROM projects WHERE id=?').bind(projectId).first())return c.json({ok:false,error:'Projektet hittades inte.'},404);try{return c.json({ok:true,runtime:'structure-consolidate-v24',result:await cleanupProjectStructureV24(c.env.DB,projectId)})}catch(error){console.error('structure consolidate v24 failed',error);return c.json({ok:false,error:error instanceof Error?error.message:String(error)},500)}})}
