type RouteApp={post:(path:string,handler:(c:any)=>unknown)=>void};

async function tableExists(db:D1Database,name:string){return Boolean(await db.prepare("SELECT 1 ok FROM sqlite_master WHERE type='table' AND name=?").bind(name).first())}
async function ensureContextSchema(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS activity_contexts(activity_id TEXT PRIMARY KEY,lifecycle_stage TEXT NOT NULL DEFAULT 'build',surface TEXT NOT NULL DEFAULT 'field',applicability TEXT NOT NULL DEFAULT 'always',condition_text TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(activity_id) REFERENCES activities(id) ON DELETE CASCADE)`).run()}
async function deprecate(db:D1Database,id:string,reason:string){await db.prepare(`INSERT INTO activity_contexts(activity_id,lifecycle_stage,surface,applicability,condition_text,updated_at) VALUES(?,'build','field','deprecated',?,datetime('now')) ON CONFLICT(activity_id) DO UPDATE SET applicability='deprecated',condition_text=excluded.condition_text,updated_at=datetime('now')`).bind(id,reason).run()}
async function isDeprecated(db:D1Database,id:string){const r=await db.prepare("SELECT applicability FROM activity_contexts WHERE activity_id=?").bind(id).first<any>();return String(r?.applicability||'always')==='deprecated'}
async function moveGoverningLinks(db:D1Database,fromId:string,toId:string){if(!await tableExists(db,'governing_item_activity_links'))return;const cols=await db.prepare('PRAGMA table_info(governing_item_activity_links)').all();const names=new Set((cols.results as any[]).map(r=>String(r.name)));const rows=await db.prepare('SELECT * FROM governing_item_activity_links WHERE activity_id=?').bind(fromId).all();for(const row of rows.results as any[]){const existing=await db.prepare('SELECT id FROM governing_item_activity_links WHERE governing_item_id=? AND activity_id=? LIMIT 1').bind(row.governing_item_id,toId).first<any>();if(existing)continue;const fields=['id','governing_item_id','activity_id','link_type','mapping_source','confidence','mapping_comment','created_at','confirmed_at'].filter(x=>names.has(x));const values=fields.map(f=>f==='id'?crypto.randomUUID():f==='activity_id'?toId:row[f]??null);await db.prepare(`INSERT INTO governing_item_activity_links(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')})`).bind(...values).run()}}
async function removeNodeLink(db:D1Database,projectId:string,type:string,id:string){if(await tableExists(db,'project_master_node_links'))await db.prepare('DELETE FROM project_master_node_links WHERE project_id=? AND entity_type=? AND entity_id=?').bind(projectId,type,id).run()}

async function mergeActivityInto(db:D1Database,fromId:string,toId:string,reason:string){if(fromId===toId)return 0;await moveGoverningLinks(db,fromId,toId);await deprecate(db,fromId,reason);return 1}

async function mergeTask(db:D1Database,projectId:string,sourceId:string,targetId:string,reason:string){const rows=await db.prepare('SELECT id,title,sort_order FROM activities WHERE task_id=? ORDER BY sort_order,id').bind(sourceId).all();let retired=0;for(const a of rows.results as any[]){const dup=await db.prepare(`SELECT a.id FROM activities a LEFT JOIN activity_contexts ac ON ac.activity_id=a.id WHERE a.task_id=? AND lower(trim(a.title))=lower(trim(?)) AND COALESCE(ac.applicability,'always')<>'deprecated' ORDER BY a.sort_order,a.id LIMIT 1`).bind(targetId,a.title).first<any>();if(dup&&!await isDeprecated(db,String(a.id)))retired+=await mergeActivityInto(db,String(a.id),String(dup.id),reason);await db.prepare('UPDATE activities SET task_id=? WHERE id=?').bind(targetId,a.id).run()}await removeNodeLink(db,projectId,'task',sourceId);await db.prepare('DELETE FROM tasks WHERE id=? AND NOT EXISTS(SELECT 1 FROM activities WHERE task_id=?)').bind(sourceId,sourceId).run();return retired}

async function mergeAliasSection(db:D1Database,projectId:string,areaName:string,sourceName:string,targetName:string){const rows=await db.prepare(`SELECT s.id,s.name FROM work_sections s JOIN work_areas w ON w.id=s.work_area_id WHERE w.project_id=? AND lower(trim(w.name))=lower(trim(?)) AND lower(trim(s.name)) IN (lower(trim(?)),lower(trim(?))) ORDER BY s.sort_order,s.id`).bind(projectId,areaName,sourceName,targetName).all();const sections=rows.results as any[];const target=sections.find(s=>String(s.name).trim().toLowerCase()===targetName.trim().toLowerCase());const sources=sections.filter(s=>String(s.name).trim().toLowerCase()===sourceName.trim().toLowerCase());if(!target||!sources.length)return{movedTasks:0,retiredActivities:0,removedSections:0};let movedTasks=0,retiredActivities=0,removedSections=0;for(const source of sources){if(String(source.id)===String(target.id))continue;const tasks=await db.prepare('SELECT id,title FROM tasks WHERE work_section_id=? ORDER BY sort_order,id').bind(source.id).all();for(const task of tasks.results as any[]){const existing=await db.prepare('SELECT id FROM tasks WHERE work_section_id=? AND lower(trim(title))=lower(trim(?)) ORDER BY sort_order,id LIMIT 1').bind(target.id,task.title).first<any>();if(existing){retiredActivities+=await mergeTask(db,projectId,String(task.id),String(existing.id),`Dublett efter flytt från ”${sourceName}” till ”${targetName}” i strukturstädning v21.`)}else{await db.prepare('UPDATE tasks SET work_section_id=?,section=? WHERE id=?').bind(target.id,targetName,task.id).run()}movedTasks++}await removeNodeLink(db,projectId,'work_section',String(source.id));const del=await db.prepare('DELETE FROM work_sections WHERE id=? AND NOT EXISTS(SELECT 1 FROM tasks WHERE work_section_id=?)').bind(source.id,source.id).run();if((del.meta as any)?.changes)removedSections++}return{movedTasks,retiredActivities,removedSections}}

async function dedupeActivities(db:D1Database,projectId:string){const groups=await db.prepare(`SELECT a.task_id,lower(trim(a.title)) title_key,COUNT(*) n FROM activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections s ON s.id=t.work_section_id JOIN work_areas w ON w.id=s.work_area_id LEFT JOIN activity_contexts ac ON ac.activity_id=a.id WHERE w.project_id=? AND COALESCE(ac.applicability,'always')<>'deprecated' GROUP BY a.task_id,lower(trim(a.title)) HAVING COUNT(*)>1`).bind(projectId).all();let retired=0;for(const g of groups.results as any[]){const rows=await db.prepare(`SELECT a.id,a.title,a.sort_order FROM activities a LEFT JOIN activity_contexts ac ON ac.activity_id=a.id WHERE a.task_id=? AND lower(trim(a.title))=? AND COALESCE(ac.applicability,'always')<>'deprecated' ORDER BY a.sort_order,a.id`).bind(g.task_id,g.title_key).all();const list=rows.results as any[];if(list.length<2)continue;const keeper=list[0];for(const source of list.slice(1))retired+=await mergeActivityInto(db,String(source.id),String(keeper.id),`Exakt aktivitetsdublett konsoliderad i strukturstädning v21.`)}return retired}

async function deprecateIfSpecificExists(db:D1Database,projectId:string,generic:string,specific:string){const target=await db.prepare(`SELECT a.id FROM activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections s ON s.id=t.work_section_id JOIN work_areas w ON w.id=s.work_area_id LEFT JOIN activity_contexts ac ON ac.activity_id=a.id WHERE w.project_id=? AND lower(trim(a.title))=lower(trim(?)) AND COALESCE(ac.applicability,'always')<>'deprecated' ORDER BY a.sort_order,a.id LIMIT 1`).bind(projectId,specific).first<any>();if(!target)return 0;const rows=await db.prepare(`SELECT a.id FROM activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections s ON s.id=t.work_section_id JOIN work_areas w ON w.id=s.work_area_id LEFT JOIN activity_contexts ac ON ac.activity_id=a.id WHERE w.project_id=? AND lower(trim(a.title))=lower(trim(?)) AND COALESCE(ac.applicability,'always')<>'deprecated'`).bind(projectId,generic).all();let n=0;for(const row of rows.results as any[])n+=await mergeActivityInto(db,String(row.id),String(target.id),`Ersatt av ”${specific}” i strukturstädning v21.`);return n}

async function ensureProjectCondition(db:D1Database,projectId:string,title:string,description:string){if(!await tableExists(db,'project_conditions'))return false;const exists=await db.prepare('SELECT id FROM project_conditions WHERE project_id=? AND lower(trim(title))=lower(trim(?)) LIMIT 1').bind(projectId,title).first();if(exists)return false;const cols=await db.prepare('PRAGMA table_info(project_conditions)').all();const names=new Set((cols.results as any[]).map(r=>String(r.name)));const fields=['id','project_id','title','description','source_type','created_at','updated_at'].filter(x=>names.has(x));const values=fields.map(f=>f==='id'?crypto.randomUUID():f==='project_id'?projectId:f==='title'?title:f==='description'?description:f==='source_type'?'master_cleanup':null);await db.prepare(`INSERT INTO project_conditions(${fields.join(',')}) VALUES(${fields.map(f=>f==='created_at'||f==='updated_at'?"datetime('now')":'?').join(',')})`).bind(...values.filter((_,i)=>fields[i]!=='created_at'&&fields[i]!=='updated_at')).run();return true}

async function moveMoistureProtectionToCondition(db:D1Database,projectId:string){const title='Fuktskydda material och konstruktion under byggtid';const rows=await db.prepare(`SELECT a.id,a.description FROM activities a JOIN tasks t ON t.id=a.task_id JOIN work_sections s ON s.id=t.work_section_id JOIN work_areas w ON w.id=s.work_area_id LEFT JOIN activity_contexts ac ON ac.activity_id=a.id WHERE w.project_id=? AND lower(trim(a.title))=lower(trim(?)) AND COALESCE(ac.applicability,'always')<>'deprecated'`).bind(projectId,title).all();if(!(rows.results as any[]).length)return 0;await ensureProjectCondition(db,projectId,title,String((rows.results as any[])[0].description||''));for(const r of rows.results as any[])await deprecate(db,String(r.id),'Flyttad till Projektvillkor i strukturstädning v21.');return (rows.results as any[]).length}

export async function cleanupProjectStructureV21(db:D1Database,projectId:string){await ensureContextSchema(db);const result={movedTasks:0,removedSections:0,retiredActivities:0,convertedConditions:0};for(const [area,source,target] of [['Mark och grund','Vald grundlösning','Grundkonstruktion'],['Bärande stomme','Vald stomtyp','Stomme'],['Tak','Vald takstomme','Takstomme']] as const){const r=await mergeAliasSection(db,projectId,area,source,target);result.movedTasks+=r.movedTasks;result.removedSections+=r.removedSections;result.retiredActivities+=r.retiredActivities}result.retiredActivities+=await dedupeActivities(db,projectId);result.retiredActivities+=await deprecateIfSpecificExists(db,projectId,'Res vald bärande stomme','Res timmerstomme enligt konstruktionshandling');result.retiredActivities+=await deprecateIfSpecificExists(db,projectId,'Kontrollera färdig stomme mot konstruktionshandlingar','Kontrollera färdig timmerstomme mot konstruktionshandling');result.retiredActivities+=await deprecateIfSpecificExists(db,projectId,'Kontrollera fönster och dörrar mot handling, infästning och tätning','Kontrollera fönster och dörrar mot handling, infästning, funktion och tätning');result.retiredActivities+=await deprecateIfSpecificExists(db,projectId,'Utför vald grundkonstruktion','Bygg krypgrund enligt projektering');result.retiredActivities+=await deprecateIfSpecificExists(db,projectId,'Montera vald bärande takkonstruktion','Montera åsar och sparrar enligt konstruktionshandling');result.convertedConditions+=await moveMoistureProtectionToCondition(db,projectId);return result}

export function registerProjectStructureCleanupV21Routes(app:RouteApp){app.post('/api/studio/projects/:projectId/structure-cleanup-v21',async c=>{const projectId=c.req.param('projectId');const project=await c.env.DB.prepare('SELECT id FROM projects WHERE id=?').bind(projectId).first();if(!project)return c.json({ok:false,error:'Projektet hittades inte.'},404);try{return c.json({ok:true,runtime:'structure-cleanup-v21',result:await cleanupProjectStructureV21(c.env.DB,projectId)})}catch(error){console.error('structure cleanup v21 failed',error);return c.json({ok:false,error:error instanceof Error?error.message:String(error)},500)}})}
