type RouteApp={post:(path:string,handler:(c:any)=>unknown)=>void};

async function tableExists(db:D1Database,name:string){return Boolean(await db.prepare("SELECT 1 ok FROM sqlite_master WHERE type='table' AND name=?").bind(name).first())}
async function ensureContextSchema(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS activity_contexts(activity_id TEXT PRIMARY KEY,lifecycle_stage TEXT NOT NULL DEFAULT 'build',surface TEXT NOT NULL DEFAULT 'field',applicability TEXT NOT NULL DEFAULT 'always',condition_text TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(activity_id) REFERENCES activities(id) ON DELETE CASCADE)`).run()}
async function deprecate(db:D1Database,id:string,reason:string){await db.prepare(`INSERT INTO activity_contexts(activity_id,lifecycle_stage,surface,applicability,condition_text,updated_at) VALUES(?,'build','field','deprecated',?,datetime('now')) ON CONFLICT(activity_id) DO UPDATE SET applicability='deprecated',condition_text=excluded.condition_text,updated_at=datetime('now')`).bind(id,reason).run()}

async function moveGoverningLinks(db:D1Database,fromId:string,toId:string){
 if(!await tableExists(db,'governing_item_activity_links'))return;
 const cols=await db.prepare('PRAGMA table_info(governing_item_activity_links)').all();const names=new Set((cols.results as any[]).map(r=>String(r.name)));
 const rows=await db.prepare('SELECT * FROM governing_item_activity_links WHERE activity_id=?').bind(fromId).all();
 for(const row of rows.results as any[]){const existing=await db.prepare('SELECT id FROM governing_item_activity_links WHERE governing_item_id=? AND activity_id=? LIMIT 1').bind(row.governing_item_id,toId).first<any>();if(existing)continue;const fields=['id','governing_item_id','activity_id','link_type','mapping_source','confidence','mapping_comment','created_at','confirmed_at'].filter(x=>names.has(x));const values=fields.map(f=>f==='id'?crypto.randomUUID():f==='activity_id'?toId:row[f]??null);await db.prepare(`INSERT INTO governing_item_activity_links(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')})`).bind(...values).run()}
}

async function mergeAllDuplicateTasks(db:D1Database,projectId:string){
 const groups=await db.prepare(`SELECT t.work_section_id,lower(trim(t.title)) title_key,COUNT(*) n FROM tasks t JOIN work_sections s ON s.id=t.work_section_id JOIN work_areas w ON w.id=s.work_area_id WHERE w.project_id=? GROUP BY t.work_section_id,lower(trim(t.title)) HAVING COUNT(*)>1`).bind(projectId).all();let mergedTasks=0,retiredActivities=0;
 for(const group of groups.results as any[]){const tasks=await db.prepare('SELECT id,title,sort_order FROM tasks WHERE work_section_id=? AND lower(trim(title))=? ORDER BY sort_order,id').bind(group.work_section_id,group.title_key).all();const list=tasks.results as any[];if(list.length<2)continue;const keeper=list[0];for(const source of list.slice(1)){const activities=await db.prepare('SELECT id,title,sort_order FROM activities WHERE task_id=? ORDER BY sort_order,id').bind(source.id).all();for(const activity of activities.results as any[]){const duplicate=await db.prepare(`SELECT a.id FROM activities a LEFT JOIN activity_contexts ac ON ac.activity_id=a.id WHERE a.task_id=? AND lower(trim(a.title))=lower(trim(?)) AND COALESCE(ac.applicability,'always')<>'deprecated' ORDER BY a.sort_order,a.id LIMIT 1`).bind(keeper.id,activity.title).first<any>();if(duplicate){await moveGoverningLinks(db,String(activity.id),String(duplicate.id));await deprecate(db,String(activity.id),`Dublett efter sammanslagning av dubbla momentet ”${keeper.title}” i strukturstädning v20.`);retiredActivities++}await db.prepare('UPDATE activities SET task_id=? WHERE id=?').bind(keeper.id,activity.id).run()}if(await tableExists(db,'project_master_node_links'))await db.prepare("DELETE FROM project_master_node_links WHERE project_id=? AND entity_type='task' AND entity_id=?").bind(projectId,source.id).run();await db.prepare('DELETE FROM tasks WHERE id=? AND NOT EXISTS(SELECT 1 FROM activities WHERE task_id=?)').bind(source.id,source.id).run();mergedTasks++}}
 return {mergedTasks,retiredActivities};
}

export async function cleanupProjectStructureV20(db:D1Database,projectId:string){await ensureContextSchema(db);return mergeAllDuplicateTasks(db,projectId)}

export function registerProjectStructureCleanupV20Routes(app:RouteApp){app.post('/api/studio/projects/:projectId/structure-cleanup-v20',async c=>{const projectId=c.req.param('projectId');const project=await c.env.DB.prepare('SELECT id FROM projects WHERE id=?').bind(projectId).first();if(!project)return c.json({ok:false,error:'Projektet hittades inte.'},404);try{return c.json({ok:true,runtime:'structure-cleanup-v20',result:await cleanupProjectStructureV20(c.env.DB,projectId)})}catch(error){console.error('structure cleanup v20 failed',error);return c.json({ok:false,error:error instanceof Error?error.message:String(error)},500)}})}
