type RouteApp={put:(path:string,handler:(c:any)=>unknown)=>void;post:(path:string,handler:(c:any)=>unknown)=>void};
function text(v:unknown){return typeof v==='string'?v.trim():''}
async function nextOrder(db:D1Database,table:string,parent:string,id:string){const allowed=new Set(['work_sections','tasks','activities']);const parents=new Set(['work_area_id','work_section_id','task_id']);if(!allowed.has(table)||!parents.has(parent))throw new Error('Ogiltig flytt.');const r=await db.prepare(`SELECT COALESCE(MAX(sort_order),0)+10 next_order FROM ${table} WHERE ${parent}=?`).bind(id).first<any>();return Number(r?.next_order||10)}
async function tableExists(db:D1Database,name:string){return Boolean(await db.prepare("SELECT 1 ok FROM sqlite_master WHERE type='table' AND name=?").bind(name).first())}
async function ensureActivityContexts(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS activity_contexts(activity_id TEXT PRIMARY KEY,lifecycle_stage TEXT NOT NULL DEFAULT 'build',surface TEXT NOT NULL DEFAULT 'field',applicability TEXT NOT NULL DEFAULT 'always',condition_text TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(activity_id) REFERENCES activities(id) ON DELETE CASCADE)`).run()}
async function moveGoverningLinks(db:D1Database,fromId:string,toId:string){if(!await tableExists(db,'governing_item_activity_links'))return;const rows=await db.prepare('SELECT * FROM governing_item_activity_links WHERE activity_id=?').bind(fromId).all();const cols=await db.prepare('PRAGMA table_info(governing_item_activity_links)').all();const names=new Set((cols.results as any[]).map(r=>String(r.name)));for(const row of rows.results as any[]){if(await db.prepare('SELECT 1 ok FROM governing_item_activity_links WHERE governing_item_id=? AND activity_id=? LIMIT 1').bind(row.governing_item_id,toId).first())continue;const fields=['id','governing_item_id','activity_id','link_type','mapping_source','confidence','mapping_comment','created_at','confirmed_at'].filter(x=>names.has(x));const values=fields.map(f=>f==='id'?crypto.randomUUID():f==='activity_id'?toId:row[f]??null);await db.prepare(`INSERT INTO governing_item_activity_links(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')})`).bind(...values).run()}}
async function deprecateActivity(db:D1Database,id:string,reason:string){await ensureActivityContexts(db);await db.prepare(`INSERT INTO activity_contexts(activity_id,lifecycle_stage,surface,applicability,condition_text,updated_at) VALUES(?,'control','field','deprecated',?,datetime('now')) ON CONFLICT(activity_id) DO UPDATE SET applicability='deprecated',condition_text=excluded.condition_text,updated_at=datetime('now')`).bind(id,reason).run()}
export function registerProjectStructureEditRoutes(app:RouteApp){
 app.put('/api/studio/structure-move/:kind/:id',async c=>{const kind=c.req.param('kind'),id=c.req.param('id');const body=await c.req.json<{parentId?:string}>().catch(()=>({}));const parentId=text(body.parentId);if(!parentId)return c.json({ok:false,error:'Ny överordnad nod krävs.'},400);if(kind==='section'){if(!await c.env.DB.prepare('SELECT id FROM work_areas WHERE id=?').bind(parentId).first())return c.json({ok:false,error:'Arbetsområdet hittades inte.'},404);const order=await nextOrder(c.env.DB,'work_sections','work_area_id',parentId);const r=await c.env.DB.prepare('UPDATE work_sections SET work_area_id=?,sort_order=? WHERE id=?').bind(parentId,order,id).run();if(!r.meta.changes)return c.json({ok:false,error:'Arbetsavsnittet hittades inte.'},404);return c.json({ok:true})}if(kind==='task'){if(!await c.env.DB.prepare('SELECT id FROM work_sections WHERE id=?').bind(parentId).first())return c.json({ok:false,error:'Arbetsavsnittet hittades inte.'},404);const order=await nextOrder(c.env.DB,'tasks','work_section_id',parentId);const r=await c.env.DB.prepare("UPDATE tasks SET work_section_id=?,sort_order=?,updated_at=datetime('now') WHERE id=?").bind(parentId,order,id).run();if(!r.meta.changes)return c.json({ok:false,error:'Momentet hittades inte.'},404);return c.json({ok:true})}if(kind==='activity'){if(!await c.env.DB.prepare('SELECT id FROM tasks WHERE id=?').bind(parentId).first())return c.json({ok:false,error:'Momentet hittades inte.'},404);const order=await nextOrder(c.env.DB,'activities','task_id',parentId);const r=await c.env.DB.prepare('UPDATE activities SET task_id=?,sort_order=? WHERE id=?').bind(parentId,order,id).run();if(!r.meta.changes)return c.json({ok:false,error:'Aktiviteten hittades inte.'},404);return c.json({ok:true})}return c.json({ok:false,error:'Den här nodtypen kan inte flyttas.'},400)});
 app.put('/api/studio/structure-rename/task/:id',async c=>{const id=c.req.param('id');const body=await c.req.json<{title?:string}>().catch(()=>({}));const title=text(body.title);if(!title)return c.json({ok:false,error:'Nytt momentnamn krävs.'},400);if(title.length>160)return c.json({ok:false,error:'Momentnamnet är för långt.'},400);const task=await c.env.DB.prepare('SELECT id,work_section_id FROM tasks WHERE id=?').bind(id).first<any>();if(!task)return c.json({ok:false,error:'Momentet hittades inte.'},404);const duplicate=await c.env.DB.prepare('SELECT id FROM tasks WHERE work_section_id=? AND lower(trim(title))=lower(trim(?)) AND id<>? LIMIT 1').bind(task.work_section_id,title,id).first();if(duplicate)return c.json({ok:false,error:'Det finns redan ett moment med samma namn i arbetsavsnittet.'},409);await c.env.DB.prepare("UPDATE tasks SET title=?,updated_at=datetime('now') WHERE id=?").bind(title,id).run();return c.json({ok:true,id,title})});
 app.put('/api/studio/structure-rename/activity/:id',async c=>{const id=c.req.param('id');const body=await c.req.json<{title?:string}>().catch(()=>({}));const title=text(body.title);if(!title)return c.json({ok:false,error:'Nytt aktivitetsnamn krävs.'},400);if(title.length>220)return c.json({ok:false,error:'Aktivitetsnamnet är för långt.'},400);const activity=await c.env.DB.prepare('SELECT id FROM activities WHERE id=?').bind(id).first();if(!activity)return c.json({ok:false,error:'Aktiviteten hittades inte.'},404);await c.env.DB.prepare('UPDATE activities SET title=? WHERE id=?').bind(title,id).run();return c.json({ok:true,id,title})});
 app.post('/api/studio/projects/:projectId/refine-vvs-v25',async c=>{const projectId=c.req.param('projectId');const project=await c.env.DB.prepare('SELECT id,name FROM projects WHERE id=?').bind(projectId).first<any>();if(!project)return c.json({ok:false,error:'Projektet hittades inte.'},404);try{
   const tasks=await c.env.DB.prepare(`SELECT t.id,t.title FROM tasks t JOIN work_sections s ON s.id=t.work_section_id JOIN work_areas w ON w.id=s.work_area_id WHERE w.project_id=?`).bind(projectId).all();const byTitle=(title:string)=>(tasks.results as any[]).find(r=>String(r.title).trim().toLowerCase()===title.trim().toLowerCase());
   const renameTask=async(oldTitles:string[],newTitle:string)=>{const row=(tasks.results as any[]).find(r=>oldTitles.some(x=>String(r.title).trim().toLowerCase()===x.toLowerCase()));if(row){await c.env.DB.prepare("UPDATE tasks SET title=?,updated_at=datetime('now') WHERE id=?").bind(newTitle,row.id).run();row.title=newTitle;return String(row.id)}return''};
   const externalWaterId=await renameTask(['Anslut gemensamt vatten','Förlägg och anslut servisledning för vatten'],'Förlägg och anslut servisledning för vatten');
   const internalVvsId=await renameTask(['Utför VVS-installation','Utför invändig VVS-installation'],'Utför invändig VVS-installation');
   const finalVvsId=await renameTask(['Kontrollera VVS-utformning och funktion','Slutkontrollera VVS-utformning och funktion'],'Slutkontrollera VVS-utformning och funktion');
   if(externalWaterId)await c.env.DB.prepare(`UPDATE activities SET title='Förlägg vattenledning och anslut till gemensam servis enligt gemensamhetsanläggningens krav' WHERE task_id=? AND lower(trim(title)) IN (lower(trim('Utför vattenanslutning enligt gemensamhetsanläggningens krav')),lower(trim('Förlägg vattenledning och anslut till gemensam servis enligt gemensamhetsanläggningens krav')))` ).bind(externalWaterId).run();
   if(internalVvsId)await c.env.DB.prepare(`UPDATE activities SET title='Montera invändiga vatten- och spillvatteninstallationer och anslut inkommande servis till huset' WHERE task_id=? AND lower(trim(title)) IN (lower(trim('Montera vatten- och spillvatteninstallationer')),lower(trim('Montera invändiga vatten- och spillvatteninstallationer och anslut inkommande servis till huset')))` ).bind(internalVvsId).run();
   let retired=0;if(finalVvsId){const acts=await c.env.DB.prepare(`SELECT a.id,a.title,CASE WHEN EXISTS(SELECT 1 FROM governing_item_activity_links g WHERE g.activity_id=a.id) THEN 1 ELSE 0 END linked FROM activities a WHERE a.task_id=? AND (lower(a.title) LIKE '%golvbrunn%' OR lower(a.title) LIKE '%legionella%') ORDER BY linked DESC,a.sort_order,a.id`).bind(finalVvsId).all();const list=acts.results as any[];const canonical=list.find(a=>String(a.title).toLowerCase().includes('golvbrunnar, blindledningar, varmvattentemperatur och legionellarisk')&&Number(a.linked)===1)||list.find(a=>String(a.title).toLowerCase().includes('golvbrunnar, blindledningar, varmvattentemperatur och legionellarisk'))||list[0];if(canonical){await c.env.DB.prepare("UPDATE activities SET title='Slutkontrollera golvbrunnar, blindledningar, varmvattentemperatur och legionellarisk',sort_order=10 WHERE id=?").bind(canonical.id).run();for(const a of list){if(String(a.id)===String(canonical.id))continue;await moveGoverningLinks(c.env.DB,String(a.id),String(canonical.id));await deprecateActivity(c.env.DB,String(a.id),'Ersatt av sammanhållen VVS-slutkontroll i strukturförfining v25.');retired++}}}
   return c.json({ok:true,externalWaterId,internalVvsId,finalVvsId,retiredVvsDuplicateActivities:retired});
  }catch(error){console.error('refine vvs v25 failed',error);return c.json({ok:false,error:error instanceof Error?error.message:String(error)},500)}});
}
