type RouteApp={get:(path:string,handler:(c:any)=>unknown)=>void;post:(path:string,handler:(c:any)=>unknown)=>void;put:(path:string,handler:(c:any)=>unknown)=>void;delete:(path:string,handler:(c:any)=>unknown)=>void};
type Body={title?:string;contentText?:string;resourceType?:string};
function text(v:unknown){return typeof v==='string'?v.trim():''}
function safeName(name:string){return name.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').replace(/^[-.]+|[-.]+$/g,'').slice(0,120)||'bilaga'}
function isFile(v:unknown):v is File{return Boolean(v&&typeof v==='object'&&typeof (v as any).stream==='function'&&typeof (v as any).size==='number')}
async function ensureSchema(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS project_node_resources(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,owner_type TEXT NOT NULL CHECK(owner_type IN ('area','section')),owner_id TEXT NOT NULL,resource_type TEXT NOT NULL DEFAULT 'text',title TEXT NOT NULL,content_text TEXT NOT NULL DEFAULT '',sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT (datetime('now')),updated_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE)`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS project_node_support_attachments(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,resource_id TEXT NOT NULL,object_key TEXT NOT NULL UNIQUE,original_name TEXT NOT NULL,content_type TEXT NOT NULL,size_bytes INTEGER NOT NULL DEFAULT 0,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE)`).run();await db.prepare('CREATE INDEX IF NOT EXISTS idx_project_node_resources_owner ON project_node_resources(owner_type,owner_id,sort_order)').run();await db.prepare('CREATE INDEX IF NOT EXISTS idx_project_node_attachments_resource ON project_node_support_attachments(resource_id,sort_order)').run()}
async function ownerProject(db:D1Database,type:string,id:string){if(type==='area')return db.prepare('SELECT project_id FROM work_areas WHERE id=?').bind(id).first<any>();if(type==='section')return db.prepare('SELECT wa.project_id FROM work_sections ws JOIN work_areas wa ON wa.id=ws.work_area_id WHERE ws.id=?').bind(id).first<any>();return null}
async function decorate(db:D1Database,rows:any[]){if(!rows.length)return rows;const marks=rows.map(()=>'?').join(',');const files=await db.prepare(`SELECT id,resource_id,original_name,content_type,size_bytes FROM project_node_support_attachments WHERE resource_id IN (${marks}) ORDER BY resource_id,sort_order,id`).bind(...rows.map(r=>r.id)).all();const map=new Map<string,any[]>();for(const f of files.results as any[]){const list=map.get(String(f.resource_id))||[];list.push({id:f.id,originalName:f.original_name,contentType:f.content_type,sizeBytes:Number(f.size_bytes||0),url:`/api/project-node-support-attachments/${encodeURIComponent(f.id)}`});map.set(String(f.resource_id),list)}return rows.map(r=>({...r,attachments:map.get(String(r.id))||[]}))}
export function registerProjectNodeSupportRoutes(app:RouteApp){
 app.get('/api/studio/project-node-support/:ownerType/:ownerId',async c=>{await ensureSchema(c.env.DB);const type=c.req.param('ownerType'),id=c.req.param('ownerId');if(type!=='area'&&type!=='section')return c.json({ok:false,error:'Ogiltig nodtyp.'},400);const rows=await c.env.DB.prepare('SELECT id,resource_type,title,content_text,sort_order FROM project_node_resources WHERE owner_type=? AND owner_id=? ORDER BY sort_order,id').bind(type,id).all();return c.json({ok:true,resources:await decorate(c.env.DB,rows.results as any[])})});
 app.post('/api/studio/project-node-support/:ownerType/:ownerId',async c=>{await ensureSchema(c.env.DB);const type=c.req.param('ownerType'),ownerId=c.req.param('ownerId');const owner=await ownerProject(c.env.DB,type,ownerId);if(!owner)return c.json({ok:false,error:'Objektet hittades inte.'},404);const body=await c.req.json<Body>().catch(()=>({}));const title=text(body.title);if(!title)return c.json({ok:false,error:'Rubrik krävs.'},400);const order=await c.env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+10 next_order FROM project_node_resources WHERE owner_type=? AND owner_id=?').bind(type,ownerId).first<any>();const id=crypto.randomUUID();await c.env.DB.prepare('INSERT INTO project_node_resources(id,project_id,owner_type,owner_id,resource_type,title,content_text,sort_order) VALUES(?,?,?,?,?,?,?,?)').bind(id,owner.project_id,type,ownerId,text(body.resourceType)||'text',title,text(body.contentText),Number(order?.next_order||10)).run();return c.json({ok:true,id},201)});
 app.put('/api/studio/project-node-support/:id',async c=>{await ensureSchema(c.env.DB);const body=await c.req.json<Body>().catch(()=>({}));const title=text(body.title);if(!title)return c.json({ok:false,error:'Rubrik krävs.'},400);const r=await c.env.DB.prepare("UPDATE project_node_resources SET title=?,content_text=?,resource_type=?,updated_at=datetime('now') WHERE id=?").bind(title,text(body.contentText),text(body.resourceType)||'text',c.req.param('id')).run();if(!r.meta.changes)return c.json({ok:false,error:'Underlaget hittades inte.'},404);return c.json({ok:true})});
 app.delete('/api/studio/project-node-support/:id',async c=>{await ensureSchema(c.env.DB);const id=c.req.param('id');const files=await c.env.DB.prepare('SELECT object_key FROM project_node_support_attachments WHERE resource_id=?').bind(id).all();for(const f of files.results as any[])if(c.env.FILES)await c.env.FILES.delete(String(f.object_key));await c.env.DB.prepare('DELETE FROM project_node_support_attachments WHERE resource_id=?').bind(id).run();const r=await c.env.DB.prepare('DELETE FROM project_node_resources WHERE id=?').bind(id).run();if(!r.meta.changes)return c.json({ok:false,error:'Underlaget hittades inte.'},404);return c.json({ok:true})});
 app.post('/api/studio/project-node-support/:id/attachments',async c=>{await ensureSchema(c.env.DB);const resource=await c.env.DB.prepare('SELECT id,project_id FROM project_node_resources WHERE id=?').bind(c.req.param('id')).first<any>();if(!resource)return c.json({ok:false,error:'Underlaget hittades inte.'},404);if(!c.env.FILES)return c.json({ok:false,error:'Fillagringen är inte tillgänglig.'},503);let form:FormData;try{form=await c.req.raw.formData()}catch{return c.json({ok:false,error:'Kunde inte läsa filen.'},400)}const upload=form.get('file');if(!isFile(upload)||upload.size<=0)return c.json({ok:false,error:'Ingen giltig fil valdes.'},400);if(upload.size>20*1024*1024)return c.json({ok:false,error:'Filen får vara högst 20 MB.'},413);const type=(upload as any).type||'';if(!type.startsWith('image/')&&type!=='application/pdf')return c.json({ok:false,error:'Endast bilder och PDF stöds.'},415);const id=crypto.randomUUID(),original=(upload as any).name||'bilaga',key=`projects/${resource.project_id}/node-support/${resource.id}/${id}-${safeName(original)}`;await c.env.FILES.put(key,(upload as any).stream(),{httpMetadata:{contentType:type||'application/octet-stream'}});const order=await c.env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+10 next_order FROM project_node_support_attachments WHERE resource_id=?').bind(resource.id).first<any>();await c.env.DB.prepare('INSERT INTO project_node_support_attachments(id,project_id,resource_id,object_key,original_name,content_type,size_bytes,sort_order) VALUES(?,?,?,?,?,?,?,?)').bind(id,resource.project_id,resource.id,key,original,type,Number((upload as any).size||0),Number(order?.next_order||10)).run();return c.json({ok:true,id},201)});
 app.get('/api/project-node-support-attachments/:id',async c=>{await ensureSchema(c.env.DB);const f=await c.env.DB.prepare('SELECT object_key,original_name,content_type FROM project_node_support_attachments WHERE id=?').bind(c.req.param('id')).first<any>();if(!f)return c.json({ok:false,error:'Bilagan hittades inte.'},404);const obj=await c.env.FILES.get(f.object_key);if(!obj)return c.json({ok:false,error:'Bilagefilen saknas.'},404);const h=new Headers();obj.writeHttpMetadata(h);h.set('Content-Type',f.content_type||h.get('Content-Type')||'application/octet-stream');h.set('Content-Disposition',`inline; filename="${safeName(f.original_name)}"`);return new Response(obj.body,{headers:h})});
 app.delete('/api/studio/project-node-support-attachments/:id',async c=>{await ensureSchema(c.env.DB);const f=await c.env.DB.prepare('SELECT object_key FROM project_node_support_attachments WHERE id=?').bind(c.req.param('id')).first<any>();if(!f)return c.json({ok:false,error:'Bilagan hittades inte.'},404);if(c.env.FILES)await c.env.FILES.delete(f.object_key);await c.env.DB.prepare('DELETE FROM project_node_support_attachments WHERE id=?').bind(c.req.param('id')).run();return c.json({ok:true})})
}
