type RouteApp={get:(path:string,handler:(c:any)=>unknown)=>void;post:(path:string,handler:(c:any)=>unknown)=>void};
type TableInfo={name:string;pk:number};
type ForeignKey={table:string;from:string;to:string};
type SystemBackup={format:string;version:number;exportedAt:string;scope:'system-master-data';entities:Record<string,Record<string,unknown>[]>};
const FORMAT='byggplan-system-backup';
function ident(v:string){if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(v))throw new Error(`Ogiltigt databasnamn: ${v}`);return `"${v}"`}
async function requireAdmin(c:any){const email=String(c.env.DEV_USER_EMAIL||'');if(!email)return false;const row=await c.env.DB.prepare(`SELECT 1 AS ok FROM users u JOIN global_user_roles r ON r.user_id=u.id WHERE u.email=? AND u.status='active' AND r.role_code='admin' LIMIT 1`).bind(email).first();return Boolean(row)}
async function systemTables(db:D1Database){const r=await db.prepare('PRAGMA table_list').all();return (r.results as any[]).filter(x=>String(x.type||'')==='table'&&String(x.name||'').startsWith('master_')).map(x=>String(x.name)).sort();}
async function info(db:D1Database,table:string){const r=await db.prepare(`PRAGMA table_info(${ident(table)})`).all();return (r.results as any[]).map(x=>({name:String(x.name),pk:Number(x.pk||0)})) as TableInfo[];}
async function fks(db:D1Database,table:string){const r=await db.prepare(`PRAGMA foreign_key_list(${ident(table)})`).all();return (r.results as any[]).map(x=>({table:String(x.table),from:String(x.from),to:String(x.to||'id')})) as ForeignKey[];}
function topo(names:string[],links:Map<string,ForeignKey[]>){const set=new Set(names),done:string[]=[],left=new Set(names);while(left.size){let progress=false;for(const t of [...left]){const parents=(links.get(t)||[]).map(f=>f.table).filter(p=>set.has(p)&&p!==t);if(parents.every(p=>done.includes(p))){done.push(t);left.delete(t);progress=true;}}if(!progress){done.push(...left);break;}}return done;}
async function exportSystem(db:D1Database){const names=await systemTables(db);const entities:Record<string,Record<string,unknown>[]>= {};for(const t of names){const r=await db.prepare(`SELECT * FROM ${ident(t)}`).all();entities[t]=r.results as Record<string,unknown>[];}return entities;}
async function restoreSystem(db:D1Database,entities:Record<string,Record<string,unknown>[]>) {const available=await systemTables(db),set=new Set(available),selected=Object.keys(entities).filter(t=>set.has(t)&&t.startsWith('master_'));if(!selected.length)throw new Error('Backupen innehåller ingen masterdata som kan återställas.');const links=new Map<string,ForeignKey[]>();for(const t of available)links.set(t,await fks(db,t));const order=topo(selected,links);for(const t of [...order].reverse())await db.prepare(`DELETE FROM ${ident(t)}`).run();for(const t of order){const cols=new Set((await info(db,t)).map(c=>c.name));for(const row of entities[t]||[]){const keys=Object.keys(row).filter(k=>cols.has(k));if(!keys.length)continue;await db.prepare(`INSERT INTO ${ident(t)}(${keys.map(ident).join(',')}) VALUES(${keys.map(()=>'?').join(',')})`).bind(...keys.map(k=>row[k]??null)).run();}}return selected;}
export function registerSystemBackupRoutes(app:RouteApp){
 app.get('/api/studio/system/backup-manifest',async c=>{if(!await requireAdmin(c))return c.json({ok:false,error:'Endast administratörer kan skapa systembackup.'},403);try{const entities=await exportSystem(c.env.DB);const backup:SystemBackup={format:FORMAT,version:1,exportedAt:new Date().toISOString(),scope:'system-master-data',entities};return c.json({ok:true,backup});}catch(e){console.error('system backup failed',e);return c.json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
 app.post('/api/studio/system/restore-data',async c=>{if(!await requireAdmin(c))return c.json({ok:false,error:'Endast administratörer kan återställa systemdata.'},403);const body=await c.req.json<{backup?:SystemBackup}>().catch(()=>({}));const backup=body.backup;if(!backup||backup.format!==FORMAT||backup.version!==1||backup.scope!=='system-master-data'||!backup.entities)return c.json({ok:false,error:'Filen är inte en giltig ByggPlan-systembackup.'},400);try{const tables=await restoreSystem(c.env.DB,backup.entities);return c.json({ok:true,tables});}catch(e){console.error('system restore failed',e);return c.json({ok:false,error:`Systemåterställningen misslyckades: ${e instanceof Error?e.message:String(e)}`},500)}});
}
