import {hashPassword,sessionUser} from './auth-session';
import {canAdminWorkspace,ensureWorkspaceSchema,isSystemAdmin,userWorkspaceProfile,workspaceRole} from './workspace-access';

type RouteApp={get:(path:string,handler:(c:any)=>unknown)=>void;post:(path:string,handler:(c:any)=>unknown)=>void;put:(path:string,handler:(c:any)=>unknown)=>void;delete:(path:string,handler:(c:any)=>unknown)=>void};
function text(v:unknown){return typeof v==='string'?v.trim():''}
function email(v:unknown){return text(v).toLowerCase()}

async function requireSystemAdmin(c:any){const user=await sessionUser(c);if(!user)return null;return await isSystemAdmin(c.env.DB,user)?user:null}
async function requireWorkspaceAdmin(c:any,workspaceId:string){const user=await sessionUser(c);if(!user)return null;return await canAdminWorkspace(c.env.DB,user,workspaceId)?user:null}

async function ensureUser(c:any,rawEmail:string,displayName?:string,password?:string){
 const normalized=email(rawEmail);if(!normalized||!normalized.includes('@'))throw new Error('En giltig e-postadress krävs.');
 let user=await c.env.DB.prepare('SELECT id,email,display_name,status FROM users WHERE lower(email)=?').bind(normalized).first<any>();
 const id=user?String(user.id):crypto.randomUUID();
 if(!user){await c.env.DB.prepare(`INSERT INTO users(id,email,display_name,status) VALUES(?,?,?,'active')`).bind(id,normalized,text(displayName)||normalized.split('@')[0]).run();user={id,email:normalized,display_name:text(displayName)||normalized.split('@')[0],status:'active'}}
 if(text(displayName))await c.env.DB.prepare("UPDATE users SET display_name=?,status='active',updated_at=datetime('now') WHERE id=?").bind(text(displayName),id).run();
 if(password){if(password.length<10)throw new Error('Lösenordet måste vara minst 10 tecken.');const h=await hashPassword(password);await c.env.DB.prepare(`INSERT INTO user_credentials(user_id,password_salt,password_hash,iterations,updated_at) VALUES(?,?,?,?,datetime('now')) ON CONFLICT(user_id) DO UPDATE SET password_salt=excluded.password_salt,password_hash=excluded.password_hash,iterations=excluded.iterations,updated_at=datetime('now')`).bind(id,h.salt,h.hash,h.iterations).run();await c.env.DB.prepare('DELETE FROM auth_sessions WHERE user_id=?').bind(id).run()}
 return{id,email:normalized};
}

async function workspaceDetails(db:D1Database,id:string){
 const row=await db.prepare(`SELECT w.id,w.name,w.status,w.created_at,
  (SELECT COUNT(*) FROM projects p WHERE p.workspace_id=w.id) project_count,
  (SELECT COUNT(*) FROM workspace_members wm WHERE wm.workspace_id=w.id AND wm.status='active') member_count
  FROM workspaces w WHERE w.id=?`).bind(id).first<any>();
 if(!row)return null;
 const admins=await db.prepare(`SELECT u.id,u.email,u.display_name,wm.role,CASE WHEN cr.user_id IS NULL THEN 0 ELSE 1 END has_login
  FROM workspace_members wm JOIN users u ON u.id=wm.user_id LEFT JOIN user_credentials cr ON cr.user_id=u.id
  WHERE wm.workspace_id=? AND wm.status='active' AND wm.role='workspace_admin' ORDER BY u.display_name,u.email`).bind(id).all();
 return{id:String(row.id),name:String(row.name),status:String(row.status),createdAt:String(row.created_at),projectCount:Number(row.project_count||0),memberCount:Number(row.member_count||0),admins:(admins.results as any[]).map(a=>({id:String(a.id),email:String(a.email),displayName:String(a.display_name),hasLogin:Boolean(a.has_login)}))};
}

export function registerWorkspaceRoutes(app:RouteApp){
 app.get('/api/workspaces/me',async c=>{const user=await sessionUser(c);if(!user)return c.json({ok:false,error:'Du måste logga in.'},401);return c.json({ok:true,...await userWorkspaceProfile(c.env.DB,user)})});

 app.get('/api/system/workspaces',async c=>{const user=await requireSystemAdmin(c);if(!user)return c.json({ok:false,error:'Systemadministratörsbehörighet krävs.'},403);await ensureWorkspaceSchema(c.env.DB);const rows=await c.env.DB.prepare('SELECT id FROM workspaces ORDER BY name').all();const workspaces=[];for(const r of rows.results as any[]){const item=await workspaceDetails(c.env.DB,String(r.id));if(item)workspaces.push(item)}return c.json({ok:true,workspaces})});

 app.post('/api/system/workspaces',async c=>{const actor=await requireSystemAdmin(c);if(!actor)return c.json({ok:false,error:'Systemadministratörsbehörighet krävs.'},403);await ensureWorkspaceSchema(c.env.DB);const body=await c.req.json<{name?:string;adminEmail?:string;adminDisplayName?:string;adminPassword?:string}>().catch(()=>({}));const name=text(body.name),adminEmail=email(body.adminEmail);if(!name)return c.json({ok:false,error:'Namn på projektytan krävs.'},400);if(!adminEmail)return c.json({ok:false,error:'Administratörens e-postadress krävs.'},400);try{const admin=await ensureUser(c,adminEmail,body.adminDisplayName,body.adminPassword);const id=crypto.randomUUID();await c.env.DB.prepare("INSERT INTO workspaces(id,name,status,created_by) VALUES(?,?,'active',?)").bind(id,name,actor.id).run();await c.env.DB.prepare("INSERT INTO workspace_members(workspace_id,user_id,role,status) VALUES(?,?,'workspace_admin','active')").bind(id,admin.id).run();return c.json({ok:true,workspace:await workspaceDetails(c.env.DB,id)},201)}catch(e){return c.json({ok:false,error:e instanceof Error?e.message:'Kunde inte skapa projektytan.'},400)}});

 app.put('/api/system/workspaces/:id',async c=>{if(!await requireSystemAdmin(c))return c.json({ok:false,error:'Systemadministratörsbehörighet krävs.'},403);await ensureWorkspaceSchema(c.env.DB);const id=String(c.req.param('id')),body=await c.req.json<{name?:string;status?:string}>().catch(()=>({}));const name=text(body.name),status=text(body.status);if(name)await c.env.DB.prepare("UPDATE workspaces SET name=?,updated_at=datetime('now') WHERE id=?").bind(name,id).run();if(['active','archived'].includes(status))await c.env.DB.prepare("UPDATE workspaces SET status=?,updated_at=datetime('now') WHERE id=?").bind(status,id).run();const item=await workspaceDetails(c.env.DB,id);if(!item)return c.json({ok:false,error:'Projektytan hittades inte.'},404);return c.json({ok:true,workspace:item})});

 app.post('/api/system/workspaces/:id/admins',async c=>{if(!await requireSystemAdmin(c))return c.json({ok:false,error:'Systemadministratörsbehörighet krävs.'},403);await ensureWorkspaceSchema(c.env.DB);const workspaceId=String(c.req.param('id'));if(!await c.env.DB.prepare('SELECT id FROM workspaces WHERE id=?').bind(workspaceId).first())return c.json({ok:false,error:'Projektytan hittades inte.'},404);const body=await c.req.json<{email?:string;displayName?:string;password?:string}>().catch(()=>({}));try{const user=await ensureUser(c,email(body.email),body.displayName,body.password);await c.env.DB.prepare(`INSERT INTO workspace_members(workspace_id,user_id,role,status,updated_at) VALUES(?,?,'workspace_admin','active',datetime('now')) ON CONFLICT(workspace_id,user_id) DO UPDATE SET role='workspace_admin',status='active',updated_at=datetime('now')`).bind(workspaceId,user.id).run();return c.json({ok:true,workspace:await workspaceDetails(c.env.DB,workspaceId)})}catch(e){return c.json({ok:false,error:e instanceof Error?e.message:'Kunde inte lägga till administratören.'},400)}});

 app.get('/api/workspaces/:id/members',async c=>{const id=String(c.req.param('id'));if(!await requireWorkspaceAdmin(c,id))return c.json({ok:false,error:'Projektyteadministratörsbehörighet krävs.'},403);await ensureWorkspaceSchema(c.env.DB);const rows=await c.env.DB.prepare(`SELECT u.id,u.email,u.display_name,wm.role,wm.status,CASE WHEN cr.user_id IS NULL THEN 0 ELSE 1 END has_login FROM workspace_members wm JOIN users u ON u.id=wm.user_id LEFT JOIN user_credentials cr ON cr.user_id=u.id WHERE wm.workspace_id=? ORDER BY CASE wm.role WHEN 'workspace_admin' THEN 0 ELSE 1 END,u.display_name,u.email`).bind(id).all();return c.json({ok:true,members:(rows.results as any[]).map(r=>({id:String(r.id),email:String(r.email),displayName:String(r.display_name),role:String(r.role),status:String(r.status),hasLogin:Boolean(r.has_login)}))})});

 app.post('/api/workspaces/:id/members',async c=>{const id=String(c.req.param('id'));if(!await requireWorkspaceAdmin(c,id))return c.json({ok:false,error:'Projektyteadministratörsbehörighet krävs.'},403);const body=await c.req.json<{email?:string;displayName?:string;password?:string;role?:string}>().catch(()=>({}));const role=text(body.role)==='workspace_admin'?'workspace_admin':'member';try{const user=await ensureUser(c,email(body.email),body.displayName,body.password);await c.env.DB.prepare(`INSERT INTO workspace_members(workspace_id,user_id,role,status,updated_at) VALUES(?,?,?,'active',datetime('now')) ON CONFLICT(workspace_id,user_id) DO UPDATE SET role=excluded.role,status='active',updated_at=datetime('now')`).bind(id,user.id,role).run();return c.json({ok:true,userId:user.id})}catch(e){return c.json({ok:false,error:e instanceof Error?e.message:'Kunde inte lägga till användaren.'},400)}});

 app.get('/api/system/system-admins',async c=>{if(!await requireSystemAdmin(c))return c.json({ok:false,error:'Systemadministratörsbehörighet krävs.'},403);await ensureWorkspaceSchema(c.env.DB);const rows=await c.env.DB.prepare(`SELECT s.email,s.created_at,u.id user_id,u.display_name,CASE WHEN cr.user_id IS NULL THEN 0 ELSE 1 END has_login FROM system_admin_emails s LEFT JOIN users u ON lower(u.email)=lower(s.email) LEFT JOIN user_credentials cr ON cr.user_id=u.id ORDER BY s.email`).all();return c.json({ok:true,admins:(rows.results as any[]).map(r=>({email:String(r.email),createdAt:String(r.created_at),userId:r.user_id?String(r.user_id):null,displayName:r.display_name?String(r.display_name):'',hasLogin:Boolean(r.has_login)}))})});

 app.post('/api/system/system-admins',async c=>{const actor=await requireSystemAdmin(c);if(!actor)return c.json({ok:false,error:'Systemadministratörsbehörighet krävs.'},403);await ensureWorkspaceSchema(c.env.DB);const body=await c.req.json<{email?:string}>().catch(()=>({}));const value=email(body.email);if(!value||!value.includes('@'))return c.json({ok:false,error:'En giltig e-postadress krävs.'},400);const u=await c.env.DB.prepare('SELECT id FROM users WHERE lower(email)=?').bind(value).first<any>();await c.env.DB.prepare('INSERT OR IGNORE INTO system_admin_emails(email,user_id,added_by) VALUES(?,?,?)').bind(value,u?.id||null,actor.id).run();return c.json({ok:true})});

 app.delete('/api/system/system-admins/:email',async c=>{const actor=await requireSystemAdmin(c);if(!actor)return c.json({ok:false,error:'Systemadministratörsbehörighet krävs.'},403);await ensureWorkspaceSchema(c.env.DB);const value=email(decodeURIComponent(String(c.req.param('email'))));const count=await c.env.DB.prepare('SELECT COUNT(*) count FROM system_admin_emails').first<any>();if(Number(count?.count||0)<=1)return c.json({ok:false,error:'Det måste finnas minst en systemadministratör.'},409);if(value===email(actor.email))return c.json({ok:false,error:'Du kan inte ta bort din egen systemadministratörsbehörighet medan du är inloggad.'},409);await c.env.DB.prepare('DELETE FROM system_admin_emails WHERE lower(email)=?').bind(value).run();return c.json({ok:true})});

 app.post('/api/system/workspaces/:id/projects/:projectId',async c=>{if(!await requireSystemAdmin(c))return c.json({ok:false,error:'Systemadministratörsbehörighet krävs.'},403);await ensureWorkspaceSchema(c.env.DB);const workspaceId=String(c.req.param('id')),projectId=String(c.req.param('projectId'));if(!await c.env.DB.prepare('SELECT id FROM workspaces WHERE id=?').bind(workspaceId).first())return c.json({ok:false,error:'Projektytan hittades inte.'},404);const result=await c.env.DB.prepare("UPDATE projects SET workspace_id=?,updated_at=datetime('now') WHERE id=?").bind(workspaceId,projectId).run();if(!result.meta.changes)return c.json({ok:false,error:'Projektet hittades inte.'},404);return c.json({ok:true})});
 }
